argoproj/argo-rollouts

manifests/base/argo-rollouts-aggregate-roles.yaml
manifests/base/argo-rollouts-deployment.yaml
manifests/install.yaml
manifests/namespace-install.yaml

Minor changes to address #35 and #38

Rework Manifests

---

controller/bluegreen.go
controller/bluegreen_test.go
controller/controller_test.go
controller/service.go
controller/service_test.go

Prevent early pause before svc change in BG

---

controller/controller.go

Don't requeue 404 errors (#69)

---

controller/canary.go

Cleanup replicasets in canary deployment (#68)

---

controller/bluegreen.go
controller/bluegreen_test.go
controller/controller.go
controller/controller_test.go
controller/pause.go
controller/replicaset.go
controller/service.go
controller/sync.go
manifests/crds/rollout-crd.yaml
manifests/install.yaml
manifests/namespace-install.yaml
pkg/apis/rollouts/v1alpha1/openapi_generated.go
pkg/apis/rollouts/v1alpha1/types.go
utils/replicaset/bluegreen.go
utils/replicaset/bluegreen_test.go
utils/replicaset/replicaset.go

Will solve https://github.com/argoproj/argo-rollouts/issues/74 by unpausing the rollout if there is a template change in the rollout.

Enable fast Rollback in BlueGreen

---

controller/bluegreen.go
controller/bluegreen_test.go

Resolves https://github.com/argoproj/argo-rollouts/issues/81
Working on unit test for this

Fix issue where preview replicaset was not scaled properly during a scaling event

---

controller/bluegreen_test.go
controller/canary.go

Issue #93 - Cleanup old canary replica sets

---

hack/gen-crd-spec/main.go
manifests/crds/rollout-crd.yaml
test/e2e/container-resource-formats.yaml

Resolves https://github.com/argoproj/argo-rollouts/issues/101

Remove Open API validation on resource requests and limits

---

Gopkg.lock
Gopkg.toml
controller/bluegreen.go
controller/bluegreen_test.go
controller/canary.go
controller/canary_test.go
controller/controller.go
controller/controller_test.go
controller/pause.go
controller/service_test.go
controller/sync.go
manifests/crds/rollout-crd.yaml
pkg/client/clientset/versioned/clientset.go
pkg/client/clientset/versioned/fake/clientset_generated.go
pkg/client/clientset/versioned/typed/rollouts/v1alpha1/fake/fake_rollout.go
pkg/client/clientset/versioned/typed/rollouts/v1alpha1/rollout.go
pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
utils/conditions/conditions.go
utils/conditions/conditions_test.go
utils/replicaset/replicaset.go
utils/replicaset/replicaset_test.go

Resolves: https://github.com/argoproj/argo-rollouts/issues/88
The implementation is complete, but I still need to fix and write unit tests for this.

Remove reliance on controller.ComputeHash() for determining changes to pod template spec

---

docs/kustomize.md
docs/kustomize/guestbook-svc.yaml
docs/kustomize/guestbook.yaml
docs/kustomize/kustomization.yaml
docs/kustomize/rollout-transform.yaml

Resolves https://github.com/argoproj/argo-rollouts/issues/111

Add documentation on how to use kustomize transformers

---

docs/index.md

Fix installation link

---

docs/features/kustomize/rollout-transform.yaml

Fix invalid Kustomize transformer configurations for `Rollout`.

FIx `rollout-transform.yaml` in Kustomize doc

---

experiments/controller.go
experiments/controller_test.go
rollout/controller.go
rollout/controller_test.go

fixes https://github.com/argoproj/argo-rollouts/issues/109

Honor DeletionTimestamp in rollout and experiment

---

pkg/apis/rollouts/v1alpha1/openapi_generated.go
pkg/apis/rollouts/v1alpha1/types.go
rollout/bluegreen.go
rollout/bluegreen_test.go
rollout/controller_test.go
rollout/replicaset.go
rollout/service.go

fixes https://github.com/argoproj/argo-rollouts/issues/128

Attach independent scaleDownDelays to older ReplicaSets

---

manifests/crds/rollout-crd.yaml
pkg/apis/rollouts/v1alpha1/openapi_generated.go
pkg/apis/rollouts/v1alpha1/types.go
pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go
rollout/bluegreen.go
rollout/controller_test.go
utils/conditions/conditions.go
utils/conditions/rollouts_test.go
utils/replicaset/replicaset.go
utils/replicaset/replicaset_test.go

Addresses https://github.com/argoproj/argo-rollouts/issues/129

Add ScaleDownDelayLimit

---

docs/getting-started.md

docs: specified type for kubectl patch

---

experiments/conditions.go
experiments/controller.go
experiments/experiment.go
experiments/replicaset.go

This refactors the experiment controller to use a new experimentContext object.

Refactor experiment controller to use a context object

---

utils/conditions/conditions.go
utils/conditions/rollouts_test.go

Closes https://github.com/argoproj/argo-rollouts/issues/214

Ignore old running rs for RolloutCompleted status

---

analysis/analysis.go
analysis/analysis_test.go
manifests/crds/analysis-run-crd.yaml
manifests/install.yaml
manifests/namespace-install.yaml
pkg/apis/rollouts/v1alpha1/analysis_types.go
pkg/apis/rollouts/v1alpha1/openapi_generated.go
pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go

Closes https://github.com/argoproj/argo-rollouts/issues/182

Implement ResumeAt logic

---

rollout/controller.go
rollout/controller_test.go

Closes https://github.com/argoproj/argo-rollouts/issues/212

Add pause condition migration

---

analysis/analysis.go
analysis/analysis_test.go
analysis/sync.go
experiments/analysisrun_test.go
experiments/controller.go
experiments/experiment.go
pkg/apis/rollouts/v1alpha1/analysis_types.go
pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go
pkg/kubectl-argo-rollouts/info/analysisrun_info.go
rollout/analysis.go
rollout/analysis_test.go
rollout/canary.go
rollout/controller.go
rollout/sync.go
utils/analysis/helpers.go
utils/analysis/helpers_test.go

Built off of https://github.com/argoproj/argo-rollouts/pull/230. Review that first.

AnalysisRun.Status is no longer a pointer

---

.dockerignore
Dockerfile
Makefile
hack/build-release-plugins.sh

`make release` also include plugin builds under dist

Add make target to release plugins

---

pkg/kubectl-argo-rollouts/info/rollout_info.go

Closes https://github.com/argoproj/argo-rollouts/issues/302

Fix a delete by zero in get command

---

docs/getting-started.md

Fixes https://github.com/argoproj/argo-rollouts/issues/312

Fix incorrect patch on getting started guide

---

rollout/context.go

Create one background analysis per revision

---

docs/CONTRIBUTING.md
docs/features/index.md

FIx typo and improve document format.
(This PR don't affect any features)

docs: Fix some typos and format

---

cmd/rollouts-controller/main.go

fix: Add namespace restriction to job informer

---

rollout/analysis.go
rollout/bluegreen.go
rollout/bluegreen_test.go
rollout/canary.go
rollout/controller.go
rollout/experiment.go
rollout/pause.go
rollout/sync.go

fixes https://github.com/argoproj/argo-rollouts/issues/351

fix: Fix honoring autoPromotionSeconds

---

pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go
pkg/kubectl-argo-rollouts/cmd/get/get_test.go
pkg/kubectl-argo-rollouts/info/info.go
pkg/kubectl-argo-rollouts/info/info_test.go
pkg/kubectl-argo-rollouts/info/replicaset_info.go

Display time remaining until BlueGreen replicaset scale down deadline

feat: Show scale down time for bluegreen replicasets

---

experiments/analysisrun_test.go
experiments/experiment.go
experiments/replicaset.go
rollout/experiment.go
utils/template/template.go
utils/template/template_test.go

closes https://github.com/argoproj/argo-rollouts/issues/380 and https://github.com/argoproj/argo-rollouts/issues/383

feat: Refactor Experiment handling of pod hashes

---

docs/features/hpa-support.md

Fixed doc to address issue brought up in this Slack comment: https://argoproj.slack.com/archives/CKTN88XFH/p1580707732022900

docs: Corrected HPA doc

---

docs/getting-started.md

fix: typo in getting started docs

---

hack/gen-crd-spec/main.go
manifests/crds/analysis-run-crd.yaml
manifests/crds/analysis-template-crd.yaml
manifests/crds/experiment-crd.yaml
manifests/crds/rollout-crd.yaml
manifests/install.yaml
manifests/namespace-install.yaml

Closes https://github.com/argoproj/argo-rollouts/issues/479 by removing validation for requests and limits

fix: Remove validation for limits and requests

---

docs/features/analysis.md

Created documentation for Secret Referencing feature in Analysis objects.

docs: Create documentation for Secret Referencing Feature

---

utils/analysis/helpers_test.go

fix: Do not assume array order in test

---

README.md

docs: add PayPay to list of Users

---

utils/analysis/factory.go
utils/analysis/factory_test.go

fix: Fix analysis validation to include Kayenta

---

docs/features/specification.md

Really minor edit to keep the comment aligned with actual spec

docs: Correct comment in rollout spec

---

.github/dependabot.yml

https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

chore: enable Dependabot v2

---

pkg/apis/rollouts/validation/validation.go
rollout/sync.go

Change `BadValue` field in Validation to prevent continuous loop

fix: Change BadValue to prevent continuous loop

---

README.md

We're using in production!
https://ubie.life/

docs: add Ubie to list of Users

---

cmd/kubectl-argo-rollouts/main.go
cmd/rollouts-controller/main.go
go.sum

Resolves: https://github.com/argoproj/argo-rollouts/issues/449

fix: support azure auth

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_proposal.md
.github/ISSUE_TEMPLATE/question.md
.github/no-response.yml
.github/pull_request_template.md

Enables:
* issue templates
* pr templates
* no-response bot

chore: enable issue templates, pr templates, and no-response bot

---

cmd/rollouts-controller/main.go
controller/controller.go
manifests/base/argo-rollouts-role.yaml
manifests/cluster-install/argo-rollouts-clusterrole.yaml
manifests/crds/rollout-crd.yaml
manifests/install.yaml
manifests/namespace-install.yaml
rollout/controller.go
rollout/controller_test.go
rollout/trafficrouting.go
rollout/trafficrouting/istio/istio.go
rollout/trafficrouting/istio/istio_test.go
rollout/trafficrouting_test.go
utils/istio/istio.go
utils/istio/istio_test.go

Create an Istio Virtual Service lister so that we can avoid making unnecessary API calls to get Istio Virtual Services.

perf: Create IstioVirtualServiceLister

---

docs/features/analysis.md

- So that users reading how to use ClusterAnalysisTemplates are aware that default values for args can be specified in them
- Ensure corresponding AnalysisTemplate example has same arg and default value for comparison
Checklist:

docs: Add arg with default value to example for ClusterAnalysisTemplates

---

.codecov.yml
Makefile
docs/CONTRIBUTING.md
go.mod
hack/gen-crd-spec/main.go
pkg/kubectl-argo-rollouts/cmd/abort/abort.go
pkg/kubectl-argo-rollouts/cmd/promote/promote.go
pkg/kubectl-argo-rollouts/cmd/restart/restart.go
pkg/kubectl-argo-rollouts/cmd/retry/retry.go
pkg/kubectl-argo-rollouts/cmd/set/set_image.go
pkg/kubectl-argo-rollouts/cmd/set/set_test.go
pkg/kubectl-argo-rollouts/info/info_test.go
pkg/kubectl-argo-rollouts/info/rollout_info.go
pkg/kubectl-argo-rollouts/options/fake/fakeoptions.go
pkg/kubectl-argo-rollouts/options/options.go
pkg/kubectl-argo-rollouts/options/options_test.go
test/e2e/canary_test.go
test/e2e/functional/alb-template.yaml
test/e2e/functional/basic.yaml
test/e2e/functional_test.go
test/fixtures/common.go
test/fixtures/e2e_suite.go
test/fixtures/given.go
test/fixtures/then.go
test/fixtures/when.go
utils/unstructured/unstructured.go
utils/unstructured/unstructured_test.go

Adds e2e testing framework with some initial tests.
Also resolves: https://github.com/argoproj/argo-rollouts/issues/572

test: add e2e testing framework

---

docs/features/traffic-management/istio.md

I fix broken itemize list in https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/#rollout-ownership-over-the-virtual-service .
Checklist:

docs: fix itemize list

---

.github/workflows/e2e.yaml
.github/workflows/go.yml
controller/controller.go
rollout/controller.go
test/e2e/canary_test.go
test/fixtures/common.go
test/fixtures/given.go
test/fixtures/then.go
test/fixtures/when.go

GitHub action to:
* start k3s
* start the controller
* run e2e tests

chore: Add github action to run e2e tests in k3s

---

.github/workflows/gh-pages.yaml
CHANGELOG.md

Update changelog and fix missing plugin docs on site.

docs: update CHANGELOG.md for v0.9.1

---

controller/metrics/rollout_test.go
controller/metrics/rollouts.go

---
Opening this in case you folks decide to move forward with #748 
Checklist:
** not there yet :)

feat(metrics): Adding rollout_info_replicas_desired metric. Fixes #748

---

README.md

We started to use the `Argo Rollouts` in production environment at October 5, 2020.
So I added the `VISITS Technologies` of own organization to users.
Thank you for your contribution to our product:)
---
Checklist:

docs: add VISITS Technologies to users

---

.github/workflows/docker-publish.yml

Resolves https://github.com/argoproj/argo-rollouts/issues/698

chore: github action to publish images to github container registry

---

docs/features/analysis.md

Fix incorrect indentation of yaml in doc

---

pkg/apis/rollouts/validation/validation.go
pkg/apis/rollouts/validation/validation_references_test.go
pkg/apis/rollouts/validation/validation_test.go

Resolves https://github.com/argoproj/argo-rollouts/issues/796

fix(controller): validation should not consider securityContext.privileged

---

analysis/controller_test.go
experiments/controller_test.go
go.mod
go.sum
pkg/kubectl-argo-rollouts/cmd/list/list_test.go
rollout/controller_test.go

Resolves https://github.com/argoproj/argo-rollouts/issues/424

chore: migrate off bouk/monkey to go-mpatch

---

README.md

A quick overview with a hands-on demo

feat: YouTube video

---

CHANGELOG.md

docs: update changelog for v0.9

---

test/fixtures/when.go

chore: increase e2e reliability by retrying conflict patches

---

.github/workflows/go.yml
hack/update-codegen.sh

Add checks to ensure codegen was executed

chore: add check to verify codegen

---

README.md

Add Quipper.
My organization is currently running argo-rollouts in a production environment
Checklist:

docs: add users

---

CHANGELOG.md
docs/features/analysis.md
docs/features/specification.md

Also fixes some other doc bugs
Resolves https://github.com/argoproj/argo-rollouts/issues/839

docs: update CHANGELOG for v0.10.0

---

CHANGELOG.md
manifests/install.yaml
manifests/namespace-install.yaml
manifests/role/argo-rollouts-clusterrole.yaml

fix: controller was not given privileges to update status subresource

---

rollout/restart.go
rollout/restart_test.go

Resolves https://github.com/argoproj/argo-rollouts/issues/845

fix: restart was restaring too much when available > spec.replicas

---

docs/index.md

Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Checklist:

docs: fix broken link to getting started

---

test/e2e/canary_test.go
test/e2e/functional/nginx-template.yaml

fix: Change e2e test ingress from ALB to Nginx

---

rollout/controller.go

fix: Correct Istio VirtualService updates immediately

---

README.md

docs: fix broken getting-started link

---

.github/workflows/docker-publish.yml
Dockerfile

feat(build): support ARM builds, remove unused components in Dockerfile

---

.github/workflows/e2e.yaml
CHANGELOG.md

docs: update CHANGELOG.md for v0.10.1

---

README.md

docs: add user Devtron labs

---

utils/unstructured/unstructured.go

Signed-off-by: zhaozhiqiang <zhaozhiqiang@lixiang.com>
Checklist:

unstructured.go  word fix objet to Object

---

README.md
USERS.md

Checklist:
* [ X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ x ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ DCA ] I've signed the CLA.
* [ N/A ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ x ] My builds are green. Try syncing with master if they are not. 
* [ x ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

chore: Separating out USERS list from README

---

README.md
docs/security.md
mkdocs.yml

chore: add CII badge

---

docs/features/bluegreen.md
examples/rollout-bluegreen.yaml
examples/rollout-canary.yaml
examples/traffic-management/rollout-linkerd.yaml

docs: fix text for resuming a rollout. Fixes #1030

---

USERS.md

I'm part of the "Dev-Tools" team in the PayPal organization where we've been maintaining/helping onboard teams to utilize canaries via Argo-Rollouts.
Checklist:

Add PayPal to users.md

---

docs/features/analysis.md
docs/features/traffic-management/alb.md
docs/getting-started/alb/index.md
docs/getting-started/alb/ingress.yaml
docs/getting-started/alb/rollout.yaml
docs/getting-started/alb/services.yaml
manifests/install.yaml
manifests/namespace-install.yaml

Resolves https://github.com/argoproj/argo-rollouts/issues/955

docs: improve ALB docs to encourage use of root-service. remove incorrect examples

---

docs/FAQ.md

docs: clarify relationship of Rollouts with Argo CD and GitOps

---

README.md

docs: more community content

---

README.md

docs: adding Keptn Argo Rollout tutorial video

---

docs/analysis/prometheus.md
docs/features/controller-metrics.md
docs/features/traffic-management/alb.md
mkdocs.yml

docs: Dedicated prometheus page, fixes #1057

---

.github/workflows/gh-pages.yaml
Dockerfile

PR fixes broken  Deploy-Docs and Docker CI tasks

chore: fix broken Deploy-Docs and Docker CI tasks

---

ui/src/app/shared/services/rollout.ts

fix: promise rejection error on rollouts list on initial load

---

docs/dashboard.md
ui/src/app/components/action-button/action-button.scss
ui/src/app/components/header/header.tsx
ui/src/app/components/tooltip/tooltip.scss
ui/src/app/components/tooltip/tooltip.tsx

feat: Add button that links to docs to header

---

pkg/apis/rollouts/validation/validation_references.go
pkg/apis/rollouts/validation/validation_references_test.go
utils/analysis/helpers.go

fix: Improve validation for AnalysisTemplates referenced by RO

---

Dockerfile
Makefile

chore: Add make target to publish kubectl plugin image

---

mkdocs.yml

docs: Add Ambassador doc links in the menu

---

docs/installation.md

docs: mention docker image for CLI

---

.github/workflows/release.yaml

fix: release-images job did not push tags properly

---

Makefile

fix: ui assets were not copied properly

---

rollout/trafficrouting/ambassador/ambassador.go
rollout/trafficrouting/ambassador/ambassador_test.go

fix: better handle the deletion of ambassador canary mapping

---

docs/roadmap.md

docs: fix missing apiVersion and selector lables in workloadRef

---

docs/features/bluegreen.md

docs: clarifications for blue/green. Fixes #1112

---

docs/getting-started/ambassador/index.md

docs: update Ambassador doc link to the official website

---

ui/src/app/components/rollout/rollout.tsx

fix(ui): Dashboard crashes when rollout has no containers

---

cmd/rollouts-controller/main.go

feat: add print version flag to rollouts-controller

---

hack/gen-plugin-docs/main.go

fix: handling error on f.close

---

rollout/trafficrouting/istio/istio.go

fix: unhandled error patchVirtualService

---

docs/features/controller-metrics.md

fix: Rename doc references with graphana to grafana

---

controller/controller.go
docs/migrating.md
rollout/context.go

docs: fix some comments in code and update workloadRef

---

docs/index.md

docs: clarifications in front page. Fixes #1111

---

pkg/kubectl-argo-rollouts/cmd/promote/promote.go
test/e2e/functional_test.go

Also refactor promote logic for clarity

test: improve e2e test to cover promote during an analysis run

---

docs/CONTRIBUTING.md
docs/FAQ.md
docs/features/canary.md
docs/features/traffic-management/alb.md
docs/features/traffic-management/istio.md

docs: minor formatting corrections. Fixes #1113

---

metricproviders/webmetric/webmetric.go
metricproviders/webmetric/webmetric_test.go

feat: WebMetric to support string body responses

---

examples/workload-ref/workload-ref.yaml

Signed-off-by: ajayk <ajaykemparaj@gmail.com>
Checklist:

fix: Fix examples/workload-ref/workload image to dockerhub registry 

---

hack/update-manifests.sh
manifests/dashboard-install.yaml
manifests/dashboard-install/dashboard-clusterrole.yaml
manifests/dashboard-install/dashboard-clusterrolebinding.yaml
manifests/dashboard-install/dashboard-deployment.yaml
manifests/dashboard-install/dashboard-service.yaml
manifests/dashboard-install/dashboard-serviceaccount.yaml
manifests/dashboard-install/kustomization.yaml

feat: rollouts dashboard-install manifests

---

docs/FAQ.md

fix: Correct typo on FAQ page

---

docs/features/helm.md
docs/migrating.md
examples/helm-blue-green/.helmignore
examples/helm-blue-green/Chart.yaml
examples/helm-blue-green/README.md
examples/helm-blue-green/templates/NOTES.txt
examples/helm-blue-green/templates/_helpers.tpl
examples/helm-blue-green/templates/rollout.yaml
examples/helm-blue-green/templates/services.yaml
examples/helm-blue-green/values.yaml
mkdocs.yml

docs: Mention Helm support. Fixes #1119

---

README.md
docs/index.md

docs: list new metric provider integrations

---

USERS.md

doc: update users list

---

Makefile

docs: Preview docs locally. Fixes #1319

---

.github/workflows/gh-pages.yaml
.github/workflows/go.yml

fix: github action to publish docs using incorrect make target

---

docs/features/specification.md
docs/index.md

docs: Link examples in documentation. Fixes #1233

---

Dockerfile.dev
Makefile

fix: make image using Dockerfile.dev works

---

server/server.go
ui/src/app/App.tsx

Resolves https://github.com/argoproj/argo-rollouts/issues/1334
Checklist:

fix: Show individual rollout in other namespace

---

USERS.md

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
Checklist:

docs: Add Alibaba and Ant Group to USERS.md

---

manifests/base/argo-rollouts-notification-secret.yaml
manifests/base/kustomization.yaml
manifests/install.yaml
manifests/namespace-install.yaml

fix: add missing notification secret to suppress error message

---

docs/architecture.md

I believe this is a chore. I made a minor correction in the docs. Please correct me if I am wrong.
Signed-off-by: Damans227 <Damans227@gmail.com>
Checklist:

docs: minor grammar corrections

---

USERS.md

This PR adds Databricks to the users list in lexicographical order.
**Checklist:**

chore: Update USERS.md

---

rollout/bluegreen.go

Resolves https://github.com/argoproj/argo-rollouts/issues/1359

fix: nil pointer dereference when reconciling paused blue-green rollout

---

.github/workflows/release.yaml

chore: github release action was using incorect docker cache

---

cmd/rollouts-controller/main.go
controller/controller.go

chore: rename variables for clarification

---

docs/installation.md

When Using custom namespace with offical spc, may cause rbac error. So I add a tips.

docs: add tip when using custom namespace

---

controller/metrics/rollout_test.go
controller/metrics/rollouts.go
rollout/controller_test.go
utils/conditions/conditions.go

fix: remove unused  ServiceNotFound condition

---

docs/installation.md

docs: Clarify quay releases. Fixes #1408

---

docs/features/specification.md

docs: clarify the setCanaryScale bahavior

---

docs/architecture.md

docs: clarify analysis. Fixes #1234

---

docs/features/traffic-management/index.md

fix: small typo

---

manifests/cluster-install/argo-rollouts-clusterrolebinding.yaml
manifests/install.yaml
manifests/namespace-install.yaml
manifests/namespace-install/argo-rollouts-rolebinding.yaml
manifests/namespace-install/clusterrole-to-role.yaml
manifests/namespace-install/kustomization.yaml
manifests/role/argo-rollouts-clusterrole.yaml

fix: Remove the type from the resource name

---

pkg/kubectl-argo-rollouts/cmd/set/set.go

chore: fix missing container in set image example text

---

pkg/apis/rollouts/validation/validation_references.go
pkg/apis/rollouts/validation/validation_references_test.go

**Signed-off-by:** Rohit Agrawal <rohit.agrawal@databricks.com>
This PR fixes the errors in `validation_reference` around Istio VirtualService validation as the current state expects at least one HTTP route to be present in the VS which is no longer true after we introduced the support for TLS routes in [this PR](https://github.com/argoproj/argo-rollouts/pull/1380). 
This leads to the following error if only TLS routes are present in the VirtualService:
```
time="2021-08-26T22:19:51Z" level=error msg="Recovered from panic: runtime error: index out of range [0] with length 0\ngoroutine 451 [running]:\nruntime/debug.Stack(0xc002a1ed98, 0x1ff5d60, 0xc003d510c8)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1.1. …
```

chore: Fix istio vs validation reference errors

---

docs/features/analysis.md

docs: analysis results - handling empty array

---

mkdocs.yml

- add scaledown-aborted-rs.md to toc
Checklist:

docs: fix missing link in toc

---

.github/workflows/release.yaml
Dockerfile
Makefile
hack/build-release-plugins.sh

build: create windows version for CLI. Fixes #654.

---

docs/CONTRIBUTING.md

docs: make it clear that kustomize is required for unit tests

---

docs/installation.md

Checklist:
See https://github.com/argoproj/argo-rollouts/pull/1478 for the actual feature.

docs: document shell completion feature

---

.github/workflows/docker-publish.yml
.github/workflows/release.yaml

PR updates release workflow to publish new release artifacts

chore: publish notifications-install.yaml and rollout_cr_schema.json as part of release

---

USERS.md
metricproviders/datadog/datadog.go
metricproviders/datadog/datadog_test.go

fix(metricproviders): Check and handle invalid server URL. Fixed #1444

---

rollout/trafficrouting/istio/istio.go

Fixes https://github.com/argoproj/argo-rollouts/issues/1552
Checklist:

fix: Fix the VS new object creation when tls route nil

---

rollout/temlateref.go
utils/annotations/annotations.go

fix: use patch to update workload-generation annotation

---

docs/assets/versions.css
docs/assets/versions.js
mkdocs.yml

Checklist:
See how it looks at https://argo-rollouts.readthedocs.io/en/doc-versioning/

docs: Use readthedocs versioning. Closes #1518

---

docs/features/notifications.md

docs: mention default notification templates

---

USERS.md

docs: Add Ibotta to the list of users

---

utils/record/record.go
utils/record/record_test.go

Resolves https://github.com/argoproj/argo-rollouts/issues/1611
Because we remarshal the rollout before sending to the notification engine, `record.go` drops the `spec.template` and `spec.selector` fields before the notification engine gets the rollout object. This caused notifications to not work with rollouts using the workloadRef feature.
This fix makes it such that if a rollout is using workloadRef, it will still be populated with the `template` and `selector` fields.

fix: notifications using workloadRef did not have access to pod template

---

ui/src/app/components/rollout/containers.tsx

fix(ui): Truncate long container names

---

ui/src/app/App.tsx

fix(ui): Requesting cluster scoped namespaces does not fail gracefully in UI

---

OWNERS

Updating docs to reflect updated membership.
Thank you @huikang @agrawroh @kostis-codefresh @harikrongali !

docs: update membership information

---

Makefile
docs/CONTRIBUTING.md

fix: remove non-existent target in makefile

---

README.md

docs: Added ArgoCon 21 presentation

---

rollout/canary.go

fix: scale up and down old replicas. Fixes #1822

---

.github/workflows/release.yaml

chore: generate and upload sbom during release

---

docs/security.md

docs: Update security.md

---

cmd/rollouts-controller/main.go

feat: Add logformat flag to rollouts-controller

---

docs/features/specification.md

fix(docs): Updated the case of properties according to actual property name

---

.github/workflows/release.yaml

chore: Generate spdx file for the docker image

---

.github/workflows/release.yaml

chore: fix spdx image generation

---

USERS.md

Fixes docs: Add SAP Concur
Signed-off-by: Tomas Valasek tomas.valasek@sap.com
Checklist:

docs: Add SAP Concur

---

server/server.go
ui/src/app/components/rollout/rollout.scss
ui/src/app/components/rollout/rollout.tsx
ui/src/models/rollout/generated/api.ts

feat: Dashboard now displaying name, specRef and weight in the experimental step.

---

docs/features/vpa-support.md
mkdocs.yml

Fixes: https://github.com/argoproj/argo-rollouts/issues/1801, https://github.com/argoproj/argo-rollouts/issues/1670
Checklist:

docs: vpa for rollouts

---

controller/controller.go
controller/metrics/metrics.go
controller/metrics/prommetrics.go
docs/features/notifications.md
go.mod
go.sum
metricproviders/prometheus/mock_test.go
utils/record/record.go
utils/record/record_test.go

Fixes: https://github.com/argoproj/argo-rollouts/issues/1782
Checklist:

feat: Report notification metrics for rollouts

---

docs/migrating.md

Signed-off-by: Hui Kang <huikang209@gmail.com>
Checklist:

docs: steps to rollback to deployment kinds

---

docs/migrating.md

docs: add selector to migrating page

---

ui/src/models/rollout/generated/api.ts

fix: UI codegen

---

utils/record/record.go
utils/record/record_test.go

fixes: https://github.com/argoproj/argo-rollouts/issues/1962
Checklist:

fix: notifications when condition

---

OWNERS

Add myself (zachaller) and Leo (leoluz) to OWNERS file.

Update membership permissions.

---

pkg/apis/rollouts/validation/validation.go

fix: High reconciliation activity and CPU load for invalid rollout

---

USERS.md
ui/src/app/App.tsx
ui/src/app/components/header/header.tsx
ui/src/app/components/rollouts-list/rollouts-list.tsx

Implementation for https://github.com/argoproj/argo-rollouts/issues/1538.
In particular:
* Add support for the endpoints  `/rollouts/:namespace?q=...` and `/rollout/:namespace/:name` that allow specifying a namespace and a search query in argo-rollouts links, effectively allowing to share links between collaborators
* Update links on the dashboard to use these new endpoints, so that one can directly copy/paste a link to share it
* Automatically update the `?q=...` query parameter when typing searches, so that one can directly copy/paste a link to share it
* The older endpoints are still supported
I'm reaaaally new to React:
* I didn't see existing unit tests for the React code base, but let me know if you'd like me to add some. It might take a bit to figure out how to test things with …

feat: support `/rollouts/:namespace?q=...` and `/rollout/:namespace/:name` (#1538)

---

manifests/dashboard-install.yaml
manifests/dashboard-install/dashboard-clusterrole.yaml

fix(dashboard): Add list and watch verbs to clusterrole. Fixes #2141

---

hack/gen-crd-spec/main.go
pkg/apis/rollouts/v1alpha1/analysis_types.go
pkg/apis/rollouts/v1alpha1/generated.proto

chore: use controler-gen for cluster analysis template scope

---

analysis/analysis.go

fixes https://github.com/argoproj/argo-rollouts/issues/2024

fix: nil pointer access in analysis run due to ignored error

---

docs/releasing.md

docs: update release doc with brew formula details

---

rollout/controller.go
utils/conditions/conditions.go

feat: emit rollout delete event

---

server/server.go

fix: rootPath support so that it uses the embedded files system

---

USERS.md

Signed-off-by: michaelchoi210 <michael.choi@opensurvey.co.kr>
Checklist:

docs: add Opensurvey to USERS.md

---

ingress/alb.go
ingress/alb_test.go
pkg/apis/rollouts/validation/validation.go
pkg/apis/rollouts/validation/validation_test.go
rollout/trafficrouting/alb/alb.go
rollout/trafficrouting/alb/alb_test.go
test/e2e/aws_test.go
test/e2e/header-routing/alb-header-route.yaml
utils/defaults/defaults.go
utils/defaults/defaults_test.go
utils/ingress/ingress.go
utils/ingress/ingress_test.go
utils/ingress/wrapper.go
utils/ingress/wrapper_test.go

feat: Allow Traffic shaping through header based routing for ALB

---

pkg/kubectl-argo-rollouts/cmd/dashboard/dashboard.go
server/server.go

chore(cli): Use standard cli format for dashboard root path

---

docs/features/controller-metrics.md

docs: Fix the controller annotation to enable data scrapping

---

USERS.md

Signed-off-by: sat-devopsnow <sat@opsverse.io>
OpsVerse uses Argo Rollouts (in conjunction with CD) across its cloud native infrastructure and is an [advocate](https://docs.opsverse.io/deploynow/deployments/blue-green/) for it within its [community](https://opsverse.io/join-our-community/).
Checklist:
N/A on the rest of the checklist

docs: add OpsVerse as an official user (USERS.md)

---

docs/FAQ.md

Answering some questions for rollbacks that I see multiple people asking over and over in the Slack channels.
Checklist:

docs: common questions for Rollbacks

---

.github/workflows/dependabot_automerge.yml

Add auto merge for dependabot

---

README.md

Part of https://github.com/argoproj/argo-rollouts/issues/2329

docs: add artifact badge

---

.github/workflows/release.yaml
hack/build-release-plugins.sh

build: add sha256 checksums for all released bins

---

.github/workflows/pr-title-check.yml

ci: Add github action for PR Conventional Commits

---

.github/workflows/stale-issues-pr.yml
.github/workflows/waiting-issues.yml

ci: add auto close to issues and prs

---

.github/workflows/dependabot_automerge.yml

part of https://github.com/argoproj/argo-rollouts/issues/2329

ci: move perms to job for clomonitor

---

.github/workflows/pr-title-check.yml

ci: fix pr lint check

---

.github/workflows/stale-issues-pr.yml
.github/workflows/waiting-issues.yml

ci: adjust settings for stale pr and issues

---

docs/features/traffic-management/index.md

docs(trafficrouting): fix docs warning to github style markdown

---

README.md

Signed-off-by: Ariel Simhon <ariel_simhon@intuit.com>
Checklist:

docs: Added blog post for minimize impact in Kubernetes using Progressive Delivery and customer side impact

---

ui/package.json
ui/src/app/components/pods/pods.tsx
ui/yarn.lock

chore(deps): upgrade ui deps to fix high security cve's

---

USERS.md

Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>
Checklist:

chore: add getyourguide to users

---

utils/template/template.go

feat(experiments): add support for getting the replicaset name via templating

---

docs/features/ephemeral-metadata.md
docs/features/traffic-management/alb.md

also, normalize all blocks with a space before the keyword.
Checklist:

docs: fix !important block typo

---

README.md

Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>
Checklist:

docs: add progressive delivery with gitops demo for openshift

---

mkdocs.yml

docs: add apisix docs to menu

---

.github/workflows/release.yaml

build: use fixed docker repository because we can't reach accross jobs

---

.github/workflows/release.yaml

chore: use correct image for plugin container

---

USERS.md

RallyHealth (part of Optum) & Optum are using Argo Rollouts and have features we have created in our fork we would like to contribute back upstream if the community wants them. First, we need to add ourselves to the User list!
Checklist:

chore: add optum to users list

---

docs/features/specification.md
docs/requirements.txt

This fixes bad rendering:
Fixed here: https://argo-rollouts-zachaller.readthedocs.io/en/fix-docs-spec/features/specification/
Broken here: https://argo-rollouts.readthedocs.io/en/stable/features/specification/

docs: fix rendering by upgrading deps

---

examples/traffic-management/rollout-linkerd.yaml

fix(example): linkerd traffic routing

---

CHANGELOG.md

docs: manually add changelog due to github action failure

---

docs/features/bluegreen.md

Signed-off-by: KipsasJaujoj <vaidotas.slavinskas@vinted.com>
Checklist:

docs: fix incorrect description for autoPromotionSeconds. Fixes #2000

---

manifests/notifications-install.yaml
manifests/notifications/on-scaling-replica-set.yaml

docs: fix spelling in example notification templates

---

USERS.md

docs: add Tuhu to users

---

metricproviders/prometheus/prometheus.go

Revision of #2489 
Checklist:
* [ b] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [c ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ X] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ X] My builds are green. Try syncing with master if they are not. 
* [ X] My organization is added to …

fix(analysis): Nil Pointer Fixes #2458

---

docs/analysis/plugins.md
docs/features/traffic-management/plugins.md
docs/plugins.md

fixes #2720 
Checklist:
* [n/a] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

refactor: change plugin naming pattern #2720

---

docs/features/traffic-management/plugins.md

docs: Add contour trafficrouter plugin

---

docs/assets/versions.js

Fix drop down via same pr argocd used https://github.com/argoproj/argo-cd/pull/13102

docs: copy argo cd docs drop down fix

---

OWNERS

chore: add zachaller as lead in owers file

---

docs/analysis/prometheus.md

Checklist:
Adds a section in the docs for analysis using Amazon Managed Prometheus, which was added in #2458 
* [ c ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ b ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ x ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)

docs: Add docs for Amazon Managed Prometheus

---

docs/features/traffic-management/traefik.md

Clarifies https://github.com/argoproj/argo-rollouts/issues/2890
Checklist:

docs: mirroring support in Traefik is not implemented yet

---

manifests/install.yaml
manifests/namespace-install.yaml
manifests/role/argo-rollouts-clusterrole.yaml

this permissions is required for ingresses to be updated

fix: add required ingress permission

---

USERS.md

chore: add WeLab Bank to users.md

---

docs/features/analysis.md

docs: Remove rogue apostrophe in features/analysis.md

---

pkg/kubectl-argo-rollouts/cmd/promote/promote.go
pkg/kubectl-argo-rollouts/cmd/promote/promote_test.go

fix: analysis step should be ignored after promote

---

USERS.md

chore: Update users doc with CircleCI

---

go.mod
go.sum

Reverts: https://github.com/argoproj/argo-rollouts/pull/3090
https://twitter.com/antonmedv/status/1711740187561033793
https://twitter.com/antonmedv/status/1711714550200807602

fix: revert repo change to expr

---

.github/workflows/image-reuse.yaml
.github/workflows/release.yaml

chore: upgrade cosign

---

README.md

chore: add OpenSSF Scorecard badge

---

docs/features/traffic-management/smi.md

Closes https://github.com/argoproj/argo-rollouts/issues/3254
Checklist:

docs: mention archival of the SMI spec

---

docs/generated/notification-services/awssqs.md
docs/generated/notification-services/github.md
docs/generated/notification-services/googlechat.md
docs/generated/notification-services/opsgenie.md
docs/generated/notification-services/pagerduty.md
docs/generated/notification-services/pagerduty_v2.md
docs/generated/notification-services/slack.md
docs/generated/notification-services/teams.md
docs/generated/notification-services/webhook.md
go.mod
go.sum

This will give us retries on notification engine webhooks

chore: bump notification engine lib

---

README.md

docs: Guides for popular use-cases

---

docs/features/traffic-management/plugins.md

docs: added Consul plugin support to website

---

manifests/base/argo-rollouts-deployment.yaml
manifests/install.yaml
manifests/namespace-install.yaml

chore: fix PodSecurity warning

---

USERS.md

chore: added organization to users.md

---

docs/best-practices.md

docs: more best practices

---

docs/best-practices.md

As it seems there are several questions around the topic, adding it in the doc.
Checklist:

docs: Add technique for ConfigMap change detection in Rollout

---

docs/features/analysis.md

fix: Change indentation to properly render Markdown - fixes #3509

---

docs/features/bluegreen.md

Looks like this sentence is incomplete. Might I suggest this change to make it read more naturally?

docs: copy omission in rollout docs

---

USERS.md

chore: Add Cloudflare to users

---

USERS.md

docs: add Priceline to USERS.md

---

rollout/controller.go

fix: replicaSet not scaled down due to incorrect annotations (#3762)

---

docs/features/analysis.md

docs: Clarify analysis count with value 0

---

USERS.md

docs: add TBC Bank to USERS.md

---

ui/src/app/components/analysis-modal/transforms.test.ts
ui/src/app/components/analysis-modal/transforms.ts
ui/src/app/components/pods/pods.tsx

fix(dashboard): analysis modal crashed when value not valid

---

USERS.md
docs/analysis/plugins.md

Opensearch plugin is added to the documentation.
Checklist:

docs(analysis): new plugin is added to the documentation

---

docs/analysis/plugins.md

docs(analysis): plugin url is changed and redirected to argoproj-labs project

---

USERS.md

docs: add CarGurus to users.md

---

docs/features/specification.md

docs: document dynamicStableScale

---

server/server_static.go
server/server_static_test.go

fix(dashboard): No redirect loop when running on root. Fixes #3967

---

docs/features/notifications.md

docs: add descriptions for additional default trigger templates

---

.github/workflows/docker-publish.yml
.github/workflows/gh-pages.yaml
.github/workflows/go.yml
.github/workflows/release.yaml
.github/workflows/testing.yaml
Dockerfile
go.mod

chore(deps): update golang to 1.23

---

docs/features/notifications.md

- Fix external reference urls.
Checklist:

docs: fix broken links

---

docs/generated/notification-services/github.md
go.mod
go.sum

chore: security fix https://nvd.nist.gov/vuln/detail/CVE-2023-46402

---

pkg/kubectl-argo-rollouts/info/pod_info.go

https://github.com/argoproj/argo-rollouts/issues/3366#issuecomment-2637220183

fix: redo PR 3639

---

USERS.md

chore: Add Verkada to the list of users

---

go.mod

chore(deps): Updated go version in go.mod file

---

USERS.md

chore: Add Doubble to official USERS.md

---

docs/CONTRIBUTING.md

docs: mention existing test suite names

---

USERS.md

docs: Added Yuno to the USERS.md

---

USERS.md

Checklist:
[x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

docs: Update USERS.md - adding Schneider Electric

---

rollout/controller.go
rollout/pause.go
rollout/replicaset.go
rollout/service.go
rollout/sync.go
rollout/trafficrouting.go

Adds rollout info in existing logs and adds more logs useful for large installations of Argo Rollouts.
Checklist:

feat: Improve logging

---

.github/workflows/go.yml
.golangci.yml
Dockerfile

ci: bump golangci-lint to v2

---

USERS.md
hack/gen-crd-spec/main.go
manifests/crds/analysis-run-crd.yaml
manifests/crds/analysis-template-crd.yaml
manifests/crds/cluster-analysis-template-crd.yaml
manifests/crds/experiment-crd.yaml
manifests/crds/rollout-crd.yaml
manifests/install.yaml

fixes https://github.com/argoproj/argo-rollouts/issues/1272
Checklist:

fix: remove preserveUnknownFields to avoid OutOfSync in ArgoCD. Fixes #1272

---

docs/FAQ.md

docs: explain skew policy between the kubectl plugin and the controller

---

docs/proposals/parameterized-build-system.md

docs: proposal for parameterized build system

---

USERS.md

Checklist:
* [YES] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

chore: Adding Red Hat to the list

---

USERS.md

docs: add batumbu to USERS.md

---

rollout/trafficrouting/service_helper.go

- Correct a typo in the comment for the GetStableAndCanaryServices method.
Checklist:

fix: correct typo

---

docs/features/hpa-support.md

docs: Add properties usage for Blue/Green and Canary Rollouts with HPA
