Gopkg.lock, controller/bluegreen.go, controller/controller.go, controller/metrics/metrics.go, controller/metrics/metrics_test.go, controller/sync.go, examples/dashboard.json, manifests/base/argo-rollouts-metrics-service.yaml, manifests/base/kustomization.yaml, manifests/install.yaml, manifests/namespace-install.yaml, utils/defaults/defaults.go, utils/defaults/defaults_test.go
Addresses https://github.com/argoproj/argo-rollouts/issues/29 by introducing a framework to expose Prothemeus metrics.  Adds metrics for the following:
- Reconciliation times for individual rollouts
- Reconciliation Error counters
- Invalid Spec counters
- Rollout creation time
- General Golang metrics
This PR did not include metrics on switching services and incrementing step index counters.  This will be incorporated with the work done with https://github.com/argoproj/argo-rollouts/issues/32
=> Add Initial Prometheus Metrics

controller/bluegreen.go, controller/bluegreen_test.go, controller/canary.go, controller/canary_test.go, controller/controller.go, controller/controller_test.go, controller/service.go, controller/service_test.go, controller/sync.go, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, utils/conditions/conditions.go, utils/conditions/conditions_test.go, utils/defaults/defaults.go, utils/defaults/defaults_test.go
Additionally, I simplified the testing framework to allow developers to test specific fields within the objects sent to the Kubernetes API instead of the entire object.
=> Add ProgressDeadlineSeconds

controller/bluegreen.go, controller/bluegreen_test.go, controller/controller_test.go, controller/service.go, controller/service_test.go, controller/sync.go, utils/conditions/conditions.go, utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go
Make available condition more clear for BlueGreen and Canary.
A BlueGreen rollout is available when the replicaset that is receiving traffic from the active selector has the min availability of pods.
A Canary Rollout is available when the sum of available pods from all replicasets is greater than or equal to the rollout's replica count.
Note: Before this PR, the HPA selector in the status wasn't being updated when the activeSelector was switched. That was okay previously because the controller would have enqueued the rollout again and change the HPA selector on the second reconciliation. Part of this implementation includes the selector change in the first reconciliation.
=> Improve Available Condition

controller/bluegreen.go, controller/bluegreen_test.go, controller/replicaset.go, controller/replicaset_test.go, controller/sync.go, utils/replicaset/bluegreen.go, utils/replicaset/bluegreen_test.go, utils/replicaset/replicaset.go
Solves the second half of https://github.com/argoproj/argo-rollouts/issues/70 by scaling down and deleting old replicasets at any point of the rollout instead of just at the end.
=> Scale down older RS on non-happy path

controller/bluegreen.go, controller/bluegreen_test.go, controller/pause.go, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go
Resolves https://github.com/argoproj/argo-rollouts/issues/66
* Rename autoPromoteActiveServiceDelaySeconds to autoPromotionSeconds
* Improve and fix documentation for various fields
=> Rename autoPromoteActiveServiceDelaySeconds to autoPromotionSeconds

cmd/rollouts-controller/main.go, controller/controller.go, controller/controller_test.go, controller/service.go, controller/service_test.go, utils/log/log.go
=> Issue #71 - Add back service informer to handle Service recreations quicker

Dockerfile.dev, Gopkg.lock, Gopkg.toml, Makefile, controller/controller.go
Resolves: https://github.com/argoproj/argo-rollouts/issues/85
We were using a `k8s.io/apimachinery` version which somehow was using glog where it did not honor the `logtostderr` flag in glog. This caused the controller to log to `/tmp` in certain cases, which crashed the controller since /tmp does not exist in scratch containers.
This change also allows a dev version of the controller image, for much faster docker builds:
```
make image DEV_IMAGE=true
```
=> Fix controller crash caused by glog attempting to write to /tmp

Gopkg.lock, controller/bluegreen.go, controller/bluegreen_test.go, controller/pause.go, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, utils/defaults/defaults.go, utils/defaults/defaults_test.go
address https://github.com/argoproj/argo-rollouts/issues/80
=> Add autoPromotionEnabled with default value of true

Gopkg.lock, Gopkg.toml, controller/bluegreen_test.go, controller/canary.go, controller/canary_test.go, controller/controller_test.go, controller/service.go, controller/service_test.go, manifests/crds/rollout-crd.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go
=> Issue #91 - Ability to specify canaryService Service object to reach only canary pods

utils/conditions/conditions.go, utils/conditions/conditions_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/103
=> Change step hashing function to derive hash from json representation of steps

manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/types.go
+kubebuilder:printcolumn annotations are used to generate the additionalPrinterColumns field of a CRD to define the set of columns used in server-side printing.
The columns added are the same as those of deployment, i.e. desired, current, up-to-date and available.
Resolves https://github.com/argoproj/argo-rollouts/issues/27.
=> Add +kubebuilder:printcolumn annotations to the Rollout type

Gopkg.lock, utils/conditions/conditions.go, utils/conditions/conditions_test.go
=> Fix maxSurge maxUnavailable zero check

rollout/canary.go, rollout/canary_test.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
Fixes https://github.com/argoproj/argo-rollouts/issues/139
=> Honor MaxSurge and MaxUnavailable after last step

utils/conditions/conditions.go, utils/conditions/rollouts_test.go
Since the scaleDownDelay is attached to individual RS and a rollout can be complete without the old RS scaling down, the progressDeadlineSeconds is now independent of the scaleDownDelaySeconds
=> Don't validate scaleDownDelay > progressingDeadline

manifests/base/argo-rollouts-role.yaml, manifests/cluster-install/argo-rollouts-clusterrole.yaml, manifests/install.yaml, manifests/namespace-install.yaml
Controller was hitting the following error:
```
E0910 23:45:08.441072       1 controller.go:287] [replicasets.apps "istio-rollout-67fb48cc58" is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot patch resource "replicasets" in API group "apps" in the namespace "istio-rollout", replicasets.apps "istio-rollout-7bffb4d96b" is forbidden: Use
r "system:serviceaccount:argo-rollouts:argo-rollouts" cannot patch resource "replicasets" in API group "apps" in the namespace "istio-rollout"]
```
=> ClusterRole missing patch privileges on replicasets

analysis/analysis.go, analysis/analysis_test.go, manifests/crds/analysis-run-crd.yaml, manifests/crds/analysis-template-crd.yaml, pkg/apis/rollouts/v1alpha1/analysis_types.go, pkg/apis/rollouts/v1alpha1/openapi_generated.go, utils/analysis/analysis.go, utils/analysis/analysis_test.go
This adds a metric field `maxInconclusive`, which allows user to specify a maximum number of times a metric is allowed to measure Inconclusive, before making the entire metric Inconclusive.
=> Add metric knob for maxInconclusive

.circleci/config.yml, Gopkg.lock, Gopkg.toml, Makefile, cmd/kubectl-argo-rollouts/main.go, manifests/crds/analysis-run-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/analysis_types.go, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/cmd_test.go, pkg/kubectl-argo-rollouts/cmd/pause/pause.go, pkg/kubectl-argo-rollouts/cmd/pause/pause_test.go, pkg/kubectl-argo-rollouts/cmd/resume/resume.go, pkg/kubectl-argo-rollouts/cmd/resume/resume_test.go, pkg/kubectl-argo-rollouts/cmd/version/version.go, pkg/kubectl-argo-rollouts/cmd/version/version_test.go, pkg/kubectl-argo-rollouts/options/fake/fakeoptions.go, pkg/kubectl-argo-rollouts/options/options.go, pkg/kubectl-argo-rollouts/options/options_test.go, utils/version/version.go
See below for examples:
```bash
$ kubectl argo rollouts version
kubectl-argo-rollouts: v0.5.0+71cfcca
BuildDate: 2019-10-11T09:33:48Z
GitCommit: 71cfcca753186304cfc39bc602d77358e7ad12ab
GitTreeState: clean
GoVersion: go1.13.1
Compiler: gc
Platform: darwin/amd64
$ kubectl argo rollouts resume canary-demo -n default
rollout 'canary-demo' resumed
$ kubectl argo rollouts pause canary-demo -n default
rollout 'canary-demo' paused
$ kubectl argo rollouts -v=6 resume doesnt-exist
I1011 02:36:12.660302   81169 loader.go:375] Config loaded from file:  /Users/jsuen/.kube/config
I1011 02:36:13.135455   81169 round_trippers.go:443] PATCH https://35.235.69.198/apis/argoproj.io/v1alpha1/namespaces/argo/rollouts/doesnt-exist 404 Not Found in 474 milliseconds
Error: rollouts.argoproj.io "doesnt-exist" not …
```
=> Implement argo rollouts kubectl plugin

analysis/controller_test.go, experiments/controller_test.go, metricproviders/job/job.go, rollout/canary.go, rollout/canary_test.go, rollout/controller_test.go, rollout/pause.go, rollout/sync.go
If a rollout was paused, it would go into syncReplicasOnly() which would call syncRolloutStatusCanary() which had no code path to unpause it ever, even after the specified duration. This change will allow it to progress to the next step after the pause duration by advancing the current step index.
Note that this change allows metadata to be updated (e.g. advancing of currentStepIndex, marking the rollout complete, etc...). This should be safe to do since we never touch replicasets weights (aside from whatever happens from scaling events).
=> Fix regression where canary would not progress past a pause step

Gopkg.lock, pkg/apis/rollouts/v1alpha1/types.go, pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/list/list.go, pkg/kubectl-argo-rollouts/cmd/list/list_test.go, pkg/kubectl-argo-rollouts/cmd/list/rollloutinfo.go, pkg/kubectl-argo-rollouts/cmd/list/rolloutinfo_test.go
Example output:
```
$ go run cmd/kubectl-argo-rollouts/main.go list --all-namespaces
NAMESPACE      NAME                         STRATEGY    STATUS        STEP  SET-WEIGHT  READY  DESIRED  UP-TO-DATE  AVAILABLE
default        canary-demo                  Canary      Progressing   2/3   20          5/5    5        1           5
default        rollout-test-helm-guestbook  BlueGreen   Healthy       -     -           1/1    1        1           1
istio-rollout  istio-rollout                Canary      Degraded      1/2   20          5/5    5        1           5
nginx-rollout  nginx-rollout                Canary      Degraded      1/2   20          5/5    5        1           5
```
=> Implement list command in kubectl plugin

docs/features/analysis.md, manifests/crds/analysis-run-crd.yaml, manifests/crds/analysis-template-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, metricproviders/prometheus/prometheus.go, metricproviders/prometheus/prometheus_test.go, pkg/apis/rollouts/v1alpha1/analysis_types.go, pkg/apis/rollouts/v1alpha1/openapi_generated.go, test/e2e/expectedfailures/analysis-run-prometheus-bad-server.yaml
This is a simple field rename from prometheus.server to prometheus.address, as this is the same terminology that the Prometheus API client uses.
=> Rename prometheus.server to address to better reflect API client interface

docs/CONTRIBUTING.md
`following guide` should be a link.
=> Fixed a markdown

manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, utils/conditions/conditions.go, utils/conditions/rollouts_test.go
closes https://github.com/argoproj/argo-rollouts/issues/149
=> Make active service required

manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/kubectl-argo-rollouts/cmd/abort/abort.go, pkg/kubectl-argo-rollouts/cmd/abort/abort_test.go, pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/retry/retry.go, pkg/kubectl-argo-rollouts/cmd/retry/retry_test.go, rollout/analysis.go, rollout/analysis_test.go, rollout/canary.go, rollout/canary_test.go, rollout/controller_test.go, rollout/experiment.go, rollout/experiment_test.go, rollout/pause.go, rollout/sync.go, utils/conditions/conditions.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
Future work:
- add abort status into the list kubectl plugin command
=> Add abort functionality

examples/rollout-analysis-step.yaml, examples/rollout-background-analysis.yaml, examples/rollout-baseline-vs-canary.yaml, examples/rollout-bluegreen.yaml, examples/rollout-canary-preview.yaml, examples/rollout-canary.yaml, examples/rollout-experiment-step.yaml, examples/rollout-rolling-update.yaml, rollout/analysis.go, rollout/analysis_test.go, rollout/controller_test.go, rollout/experiment.go, rollout/experiment_test.go, rollout/sync.go, utils/analysis/filter.go, utils/analysis/helpers.go, utils/analysis/helpers_test.go, utils/experiment/experiment.go, utils/experiment/experiment_test.go, utils/experiment/filter_test.go
Experiments and analysis runs created from rollout objects will have deterministic names, preventing duplicates from being created.
Resolves https://github.com/argoproj/argo-rollouts/issues/243
=> Use deterministic names for experiments and analysis

manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/kubectl-argo-rollouts/info/experiment_info.go, rollout/analysis.go, rollout/canary.go, rollout/experiment.go, rollout/experiment_test.go, rollout/sync.go
Built ontop of https://github.com/argoproj/argo-rollouts/pull/255. 
View last commit only.
Resolves https://github.com/argoproj/argo-rollouts/issues/253
=> Pause and abort a rollout upon inconclusive and failed experiment

experiments/analysisrun_test.go, experiments/controller_test.go, experiments/experiment.go, rollout/controller_test.go, rollout/experiment_test.go
This change makes analysis runs created from experiments deterministic.
Builds on https://github.com/argoproj/argo-rollouts/pull/258. Look at last commit only.
=> Use deterministic names for analysisruns created in experiments

experiments/controller_test.go, experiments/replicaset.go, experiments/replicaset_test.go, rollout/analysis.go, rollout/experiment.go
This annotates replicasets with the experiment name and template name, instead of labeling them. Labels are subject to 63 character limits. 
To associate replicasets to templates, the new logic is to list all replicaset in the namespace, then filter out only the ones with the same owner UID, and then associate by the annotations.
=> Annotate instead of label experiment names in replicasets

metricproviders/prometheus/prometheus.go, metricproviders/prometheus/prometheus_test.go
Closes https://github.com/argoproj/argo-rollouts/issues/180
=> Treat NaN as inconclusive

experiments/controller_test.go, experiments/replicaset.go, experiments/replicaset_test.go, pkg/apis/rollouts/v1alpha1/experiment_types.go, pkg/kubectl-argo-rollouts/info/experiment_info.go, pkg/kubectl-argo-rollouts/info/info.go, pkg/kubectl-argo-rollouts/info/replicaset_info.go, pkg/kubectl-argo-rollouts/info/rollout_info.go
1. Removes the pod template hash from replicasets created from experiments
2. Surface any running images of experiments to the CLI
=> Simplify experiment replicaset names. Surface experiment images to CLI

pkg/kubectl-argo-rollouts/cmd/get/get.go, pkg/kubectl-argo-rollouts/cmd/get/get_experiment.go, pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/get/get_test.go, pkg/kubectl-argo-rollouts/info/analysisrun_info.go, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-demo.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-exp-analysis-job-pod.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-exp-analysis-job.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-exp-analysis.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-exp-pod.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-exp-rs.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-exp.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-rs.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/stable-pod1.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/stable-pod2.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/stable-pod3.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/stable-pod4.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/stable-pod5.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/stable-rs.yaml, pkg/kubectl-argo-rollouts/info/testdata/testdata.go, rollout/sync.go, utils/analysis/helpers.go, utils/replicaset/canary.go
* Show running jobs as part of analysis runs. 
* Fix degraded check to consider experiment/analysis steps
=> Show failed/running jobs as part of analysis runs. Fix degraded checks

rollout/analysis.go, rollout/analysis_test.go
This incorporates the step index into the analysisrun name so that collisions are minimized
=> Incorporate the step index into the analysisrun name to prevent name collision

pkg/kubectl-argo-rollouts/cmd/set/set_image.go, pkg/kubectl-argo-rollouts/cmd/set/set_test.go
Adds the following capability:
```
$ kubectl argo rollouts set image rollout-baseline-vs-canary "*=argoproj/rollouts-demo:purple"
rollout "rollout-baseline-vs-canary" image updated
```
This matches the behavior of `kubectl set image`, e.g.:
```
kubectl set image daemonset abc *=nginx:1.9.1
```
=> Add ability to `kubectl argo rollouts set image *=myrepo/myimage`

experiments/experiment.go, pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/create/create.go, pkg/kubectl-argo-rollouts/cmd/create/create_test.go, pkg/kubectl-argo-rollouts/cmd/create/testdata/analysis-template.json, pkg/kubectl-argo-rollouts/cmd/create/testdata/analysis-template.yaml, pkg/kubectl-argo-rollouts/cmd/get/get.go, pkg/kubectl-argo-rollouts/cmd/get/get_experiment.go, pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/get/get_test.go, pkg/kubectl-argo-rollouts/cmd/promote/promote.go, pkg/kubectl-argo-rollouts/info/analysisrun_info.go, pkg/kubectl-argo-rollouts/info/testdata/testdata.go, rollout/analysis.go, utils/analysis/helpers.go, utils/analysis/helpers_test.go
1. Introduce `kubectl argo rollouts create -f file.yaml` with a `-w` watch option
2. Introduce `kubectl argo rollouts create analysisrun` with ` --from=templatename` or ` --from-file=template.yaml`
3. Made generating an AnalysisRun from a AnalysisTemplate into a helper
4. Always show the last job when displaying analysis jobs (not just the failed ones)
=> Introduce 'kubectl argo rollouts create' command

.circleci/config.yml, rollout/bluegreen.go, rollout/bluegreen_test.go, rollout/replicaset.go
Solves https://github.com/argoproj/argo-rollouts/issues/301 by removing the scaling preview ReplicaSet section in the`scaleBlueGreen` method. That section would scale up the preview ReplicaSet to the `.spec.Replicas` count without taking the rollout pause status into account (https://github.com/argoproj/argo-rollouts/compare/fix-infinite-loop?expand=1#diff-cfad87918ee0d3175ebd8e47f5efd159L309 vs https://github.com/argoproj/argo-rollouts/blob/master/utils/replicaset/replicaset.go#L89). The rollout should only scale to the `.spec.Replicas` count when the rollout is paused and the ScaleUpPreviewCheckPoint is set to true.
The `scaleBlueGreen` method also scales the new ReplicaSet. Since the new ReplicaSet is the same as the preview ReplicaSet, the controller scales it to the …
=> Fix Infinite loop with PreviewReplicaCount set

rollout/bluegreen.go, rollout/controller_test.go, utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go
- solves https://github.com/argoproj/argo-rollouts/issues/311 .
- allow users to replace preview service's replica sets under Bluegreen type rollouts without prior abortion 
In the course of bug fixing, I found that it is impossible for users to update preview service/replica with the new replica set of different template when the current preview service is not empt (i.e., rollout resource is paused). As of now, to achieve the replacement, users must set `status.abort` prior to try new templates.
To make matters worse, argo-rollouts controller would be panic if we do so (this is the same reason as https://github.com/argoproj/argo-rollouts/issues/311).
=> Bluegreen: allow preview service/replica sets to be replaced and fix sg fault in syncReplicasOnly

rollout/canary.go, rollout/canary_test.go, rollout/context.go, rollout/sync.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
=> Set StableRS hash to current if replicaset does not actually exist

rollout/sync.go, rollout/sync_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/329
Also the unit test was not verifying that the correct number of deletes were happening, only that when a delete did happen, it was to an expected replicaset.
=> fix: omitted revisionHistoryLimit was not defaulting to 10

utils/controller/controller.go
This log message does not offer any insights into the various resources being synced and pollutes the logs with hundreds of `Successfully synced` messages. Most of these messages come from the service controller that has to process all the services in the cluster regardless if they are used by the rollout.
=> Remove loud log message

pkg/apis/rollouts/v1alpha1/types.go, rollout/canary.go, rollout/canary_test.go, rollout/controller_test.go, rollout/service.go
Add `.spec.strategy.canary.stableSvc` field so users can specify a service that will be modified to only serve traffic to the stable ReplicaSet.
=> feat: Add stableService field

docs/features/traffic-management/index.md, docs/features/traffic-management/istio.md, docs/features/traffic-management/nginx.md, mkdocs.yml
This PR adds the initial documentation for integrating Istio and Argo Rollouts. It talks at a high level about how the controller modifies Istio resources to achieve traffic splitting with configuration from a Rollout object.
=> docs: Add Istio docs

rollout/context.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go, utils/replicaset/replicaset.go
The controller calls the GetStableRS function to calculate the stable RS and the older RSs from the new RS and the list of other ReplicaSets. The GetStableRS function assumes that the list of other ReplicaSets does not have the new RS in it. However, if the stableRS is the same as the new RS (which happens when the Rollout finishes progressing through the steps), the new RS would be included in the list of older RSs. 
If the user scaled their rollout with only a stable RS, the controller counted the stable RS in the list of old RSs and pass the max surge limit. As a result, the rollout wouldn't be able to make any progress. This issue would reported [here](https://github.com/argoproj/argo-rollouts/issues/332)
The fix separated the get the Stable RS and older RSs logic into two separate …
=> fix: Prevent StableRS from being counted in olderRS

Gopkg.lock, cmd/rollouts-controller/main.go, controller/controller.go, experiments/analysisrun_test.go, experiments/controller_test.go, experiments/experiment.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/kubectl-argo-rollouts/cmd/create/create.go, pkg/kubectl-argo-rollouts/cmd/create/create_test.go, rollout/analysis.go, rollout/analysis_test.go, rollout/experiment.go, rollout/experiment_test.go, utils/analysis/factory.go, utils/analysis/factory_test.go, utils/analysis/helpers.go, utils/analysis/helpers_test.go, utils/controller/controller.go, utils/controller/controller_test.go
Closes https://github.com/argoproj/argo-rollouts/issues/304
Adds a new flag to the controller called `--instance-id`. This flag indicates that the controller should only operate on Argo Rollout objects that have that label `argo-rollouts.argoproj.io/controller-instance-id` with the same value passed into the flag. If the flag is not listed, the controller operates on any Argo Rollout object that does not have the `argo-rollouts.argoproj.io/controller-instance-id` label.
=> feat: Support instance ids for rollout controller segregation

docs/features/analysis.md
The AnalysisTemplate examples provided don't validate against the latest
CRD schema. The provider configurations should be nested under the
`provider` key.
=> docs: Fix analysis template examples

rollout/trafficrouting.go, rollout/trafficrouting/istio/istio.go, rollout/trafficrouting/istio/istio_test.go
Checks that the Virtual Service modified by the rollout has:
1. All the routes listed in Rollout
2. Each route only has two hosts and they are the stable and canary services
=> feat: Add validation to istio virtual services

docs/features/analysis.md, docs/features/experiment.md
* use `args` instead of `arguments` and `inputs` in specs
* update template placeholders to use `args.*` instead of `inputs.*`
* fix some bullet list rendering issues
* fix "Job Metrics" example
- move `metrics.job` to `metrics.provider.job`
- move `job.template` to `job.spec.template`
=> docs: fix analysis template args examples

manifests/crds/analysis-run-crd.yaml, manifests/crds/analysis-template-crd.yaml, manifests/crds/experiment-crd.yaml, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml
Looks like the https://github.com/argoproj/argo-rollouts/pull/318 merge, a merge conflict with the manifests get in and that commit used a different version of the codegen. This PR fixes the merge conflict and uses the older version of the codegen (the same version the maintainers are using). I will open up another issue to standardize the version of the code generator.
=> chore: Rerun codegen and gen manifests

docs/CONTRIBUTING.md, docs/features/analysis.md
* update web metrics example
* fix toc for analysis page by correcting CRD heading
* include command to view docs locally using docker
=> docs: update web metrics section

manifests/crds/analysis-run-crd.yaml, manifests/crds/analysis-template-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/analysis_types.go, pkg/apis/rollouts/v1alpha1/experiment_types.go, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go
Closes https://github.com/argoproj/argo-rollouts/issues/225
=> feat: Add patchMergeKey and patchStrategy struct tags and comments

utils/controller/controller.go
Reduced message from error to warning since this is a common error when clusters don't have Istio installed.
=> chore: Reduce log from error to warning

.gitignore
When we deploy the documentation to https://argoproj.github.io/argo-rollouts/, the mkdocs command creates a directory called `site/`. Since this directory is auto-generated from the docs folder, there is no reason for us to keep the code in Git.
=> chore: Add autogenerated sites/ to gitignore

docs/features/analysis.md, utils/template/template.go, utils/template/template_test.go
This feature better enables the Kayenta use case by dynamically setting the Start and End times for the Kayenta query.
=> feat: Allow ex to use availableAt and end Time as args

docs/features/kubectl-plugin.md, pkg/kubectl-argo-rollouts/cmd/get/get_experiment.go, pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/get/get_test.go, pkg/kubectl-argo-rollouts/cmd/list/list_experiments.go, pkg/kubectl-argo-rollouts/cmd/list/list_rollouts.go, pkg/kubectl-argo-rollouts/cmd/list/list_test.go, pkg/kubectl-argo-rollouts/cmd/retry/retry.go, pkg/kubectl-argo-rollouts/cmd/retry/retry_test.go, pkg/kubectl-argo-rollouts/cmd/terminate/terminate_test.go
Add resource aliases consistent with crds to kubectl plugin commands (`get`, `list`, `retry`, `terminate`)
- Rollout = rollouts, rollout, ro
- Experiment = experiments, experiment, exp
- AnalysisRun = analysisruns, analysisrun, ar
Closes #402
=> feat: Add more command aliases in kubectl plugin

rollout/canary_test.go, rollout/sync.go
Closes https://github.com/argoproj/argo-rollouts/issues/412 by allowing the controller to update ReplicaSet if RS's annotations need to be changed.
Noticed that we implemented this fix in https://github.com/argoproj/argo-rollouts/pull/388, but that PR is too large for a patch release.
=> fix: Update RS if RS's annotations need to be changed

docs/features/analysis.md
The `valueFrom` attribute for analysis args is `podTemplateHashValue`.
See: https://godoc.org/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1#ArgumentValueFrom
=> docs: Use correct podTemplateHashValue attribute for valueFrom

docs/CONTRIBUTING.md
Fixes the issue where a new developer would run `make codegen` and the mockery binary wouldn't be downloaded.
=> fix: Add Go mod download command to contributor docs

.gitignore, Makefile, docs/CONTRIBUTING.md, docs/features/analysis.md, docs/features/bluegreen.md, docs/features/canary.md, docs/features/kubectl-plugin.md, docs/features/traffic-management/istio.md, docs/features/traffic-management/nginx.md, docs/getting-started.md, hack/gen-plugin-docs/main.go, mkdocs.yml, pkg/kubectl-argo-rollouts/cmd/get/get.go, pkg/kubectl-argo-rollouts/cmd/list/list.go
add new `make plugin-docs` command that generates kubectl plugin docs to
`docs/generated`. a new navigation item is added under the 'Kubectl Plugin'
section that points to generated docs.
closes #327
=> docs: generate kubectl plugin docs

pkg/kubectl-argo-rollouts/cmd/list/list_test.go
This addresses a test failure introduced in #422
=> fix: TestListCmdUsage test passes

.codecov.yml, docs/features/canary.md, docs/features/index.md, hack/update-codegen.sh, hack/update-openapigen.sh, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/types_test.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, pkg/kubectl-argo-rollouts/cmd/list/list_test.go, pkg/kubectl-argo-rollouts/info/info_test.go, rollout/canary.go, rollout/canary_test.go, rollout/pause.go, utils/conditions/conditions.go, utils/conditions/rollouts_test.go
Support declaring pause duration as string with optional time
unit (i.e. "s", "m", "h"). If no time unit or value is an integer,
seconds are inferred.
closes #292
=> feat: pause duration as string with time unit

manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/kubectl-argo-rollouts/info/info_test.go, pkg/kubectl-argo-rollouts/info/replicaset_info.go, pkg/kubectl-argo-rollouts/info/rollout_info.go, pkg/kubectl-argo-rollouts/info/testdata/canary/canary-rollout.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-analysis/rollout-experiment-analysis.yaml, pkg/kubectl-argo-rollouts/info/testdata/experiment-step/canary-demo.yaml, rollout/analysis.go, rollout/analysis_test.go, rollout/bluegreen.go, rollout/bluegreen_test.go, rollout/canary.go, rollout/canary_test.go, rollout/controller.go, rollout/controller_test.go, rollout/experiment_test.go, utils/conditions/conditions.go, utils/conditions/rollouts_test.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
Created a follow up issue to remove the deprecated .status.canary.stableRS field [here](https://github.com/argoproj/argo-rollouts/issues/440)
=> chore: Add StableRS to rolloutStatus

manifests/base/argo-rollouts-role.yaml, manifests/cluster-install/argo-rollouts-clusterrole.yaml, manifests/install.yaml, manifests/namespace-install.yaml
And ran `make manifests` to update consolidated manifests.
=> fix: Update Role/ClusterRole for Ingress access

manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, pkg/kubectl-argo-rollouts/cmd/get/get_test.go, pkg/kubectl-argo-rollouts/info/replicaset_info.go, rollout/analysis.go, rollout/analysis_test.go, rollout/bluegreen.go, rollout/canary.go, rollout/context.go, rollout/controller_test.go, rollout/replicaset.go, rollout/trafficrouting/nginx/nginx.go, utils/analysis/factory.go, utils/analysis/factory_test.go, utils/analysis/filter.go, utils/analysis/filter_test.go
Closes #348.
Add the ability for a BlueGreen Rollout to launch an AnalysisRun after the active Service's selector is switched.
=> feat: Add Blue Green Post Promotion Analysis

controller/controller.go, pkg/apis/rollouts/v1alpha1/types.go, rollout/analysis_test.go, rollout/bluegreen_test.go, rollout/canary_test.go, rollout/controller_test.go, rollout/service.go, rollout/service_test.go, service/service.go, service/service_test.go, utils/conditions/conditions.go, utils/service/service.go, utils/service/service_test.go
Closes https://github.com/argoproj/argo-rollouts/issues/443 by introducing a new annotation called `argo-rollouts.argoproj.io/managed-by-rollouts` that indicates a Service is managed by a Rollout.
=> feat: Use managed-by annotation

docs/features/analysis.md, docs/features/bluegreen.md, docs/features/canary.md, docs/features/index.md, go.mod, hack/gen-plugin-docs/main.go, mkdocs.yml, pkg/kubectl-argo-rollouts/cmd/abort/abort.go, pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/create/create.go, pkg/kubectl-argo-rollouts/cmd/get/get.go, pkg/kubectl-argo-rollouts/cmd/get/get_experiment.go, pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/list/list.go, pkg/kubectl-argo-rollouts/cmd/list/list_experiments.go, pkg/kubectl-argo-rollouts/cmd/list/list_rollouts.go, pkg/kubectl-argo-rollouts/cmd/list/list_test.go, pkg/kubectl-argo-rollouts/cmd/pause/pause.go, pkg/kubectl-argo-rollouts/cmd/promote/promote.go, pkg/kubectl-argo-rollouts/cmd/retry/retry.go, pkg/kubectl-argo-rollouts/cmd/set/set.go, pkg/kubectl-argo-rollouts/cmd/set/set_image.go, pkg/kubectl-argo-rollouts/cmd/terminate/terminate.go, pkg/kubectl-argo-rollouts/cmd/version/version.go
- remove "not implemented" warning for BG postPromotionAnalysis
- add missing postPromotionAnalysis property from BG
- add long descriptions to each command for synopsis section
- normalize cmd examples
- update gen-plugin-docs script to
- update mkdocs nav with command list
- friendlier titles
=> docs: plugin command enhancements

pkg/kubectl-argo-rollouts/cmd/abort/abort.go, pkg/kubectl-argo-rollouts/cmd/abort/abort_test.go, pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/create/create.go, pkg/kubectl-argo-rollouts/cmd/get/get_experiment.go, pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/list/list_experiments.go, pkg/kubectl-argo-rollouts/cmd/list/list_rollouts.go, pkg/kubectl-argo-rollouts/cmd/pause/pause.go, pkg/kubectl-argo-rollouts/cmd/pause/pause_test.go, pkg/kubectl-argo-rollouts/cmd/promote/promote.go, pkg/kubectl-argo-rollouts/cmd/retry/retry.go, pkg/kubectl-argo-rollouts/cmd/retry/retry_test.go, pkg/kubectl-argo-rollouts/cmd/set/set.go, pkg/kubectl-argo-rollouts/cmd/set/set_image.go, pkg/kubectl-argo-rollouts/cmd/terminate/terminate.go, pkg/kubectl-argo-rollouts/cmd/terminate/terminate_test.go, pkg/kubectl-argo-rollouts/options/options.go
This changeset compliments #454 by making the cli flags more
readable in documentation and usage help.
The options AddKubectlFlags is only applied to the the root
argo rollouts command and has been removed from all the child
commands. The result of this from a documentation perspective
is options are now split between options specific to the command
and options inherited from parent.
One side effect of this is tests that use inherited args need to call
`o.AddKubectlFlags(cmd)` explicitly.
=> chore: set kubectl flags on root command

analysis/controller.go, analysis/controller_test.go, controller/controller.go, controller/metrics/analysis.go, controller/metrics/analysis_test.go, controller/metrics/client.go, controller/metrics/client_test.go, controller/metrics/experiment_test.go, controller/metrics/experiments.go, controller/metrics/metrics.go, controller/metrics/metrics_test.go, controller/metrics/rollout_test.go, controller/metrics/rollouts.go, docs/features/controller-metrics.md, experiments/controller.go, experiments/controller_test.go, ingress/ingress_test.go, metricproviders/metricproviders.go, rollout/controller.go, rollout/controller_test.go, service/service_test.go, utils/controller/controller.go, utils/controller/controller_test.go
Closes https://github.com/argoproj/argo-rollouts/issues/173 and https://github.com/argoproj/argo-rollouts/issues/457
=> feat: Improve Prometheus metrics

Dockerfile
Copy only go.mod and go.sum and download the dependencies _before_ running the build. This way if the source files change but _not_ the dependencies, the docker build will leverage layer caching and not re-download the go dependencies.
=> chore: Download go deps explicitly in Dockerfile

metricproviders/wavefront/wavefront.go, metricproviders/wavefront/wavefront_test.go, service/service.go
Closes #452 by
* Grabbing the datapoint closest to the startTime and records which Epoch was used in the metadata
* Adds an Endtime equal to the StartTime so that the query is easily reproducible (where before the EndTime was null which wavefront treats as now)
* Adds the warning if the response includes them
This PR also changes the service controller to use a merge patch instead of a JSON patch.
=> feat: Improve wavefront provider

analysis/analysis.go, analysis/controller.go, analysis/controller_test.go, analysis/sync.go, controller/controller.go, experiments/controller.go, experiments/controller_test.go, experiments/replicaset.go, hack/update-codegen.sh, rollout/analysis.go, rollout/bluegreen.go, rollout/canary.go, rollout/canary_test.go, rollout/context.go, rollout/controller.go, rollout/controller_test.go, rollout/experiment.go, rollout/pause.go, rollout/replicaset.go, rollout/replicaset_test.go, rollout/service.go, rollout/sync.go, rollout/sync_test.go, rollout/trafficrouting.go, rollout/trafficrouting_test.go, service/service.go, service/service_test.go
Starting in #426 we changed the constructors for the new ingress controller, and the one for the `service` controller to accept a config struct to avoid potential issues with out of order parameters.
This extends that change to the remaining controllers and also removes "stuttering" (`analysis.AnalysisController -> analysis.Controller`)
=> chore: Consistently use Config struct for controller constructors

manifests/cluster-install/argo-rollouts-clusterrole.yaml, manifests/install.yaml
=> fix: Add missing clusterrole for deleting pods

ingress/alb.go, rollout/trafficrouting/alb/alb.go, rollout/trafficrouting/alb/alb_test.go, utils/ingress/ingress.go
=> fix: Ensure ALB action has weight 0 marshalled correctly

docs/getting-started.md, docs/index.md
Closes https://github.com/argoproj/argo-rollouts/issues/476. This issue occurs because Argo Rollouts v0.8 is starting to use the `x-kubernetes-int-or-string` in the validation, which is not available before v1.15.
=> docs: Update install caveat to include v1.14

docs/features/kustomize/rollout-transform.yaml, test/kustomize/rollout/expected.yaml, test/kustomize/rollout/rollout.yaml
Adds support for:
* Ingress (extensions/networking.k8s.io) name references in ALB and NGINX
* AnalysisTemplate name references in Rollout and Experiment
* ConfigMap/Secret/ServiceAccount/etc... name references in Experiments
* ConfigMap/Secret/ServiceAccount/etc... name references in AnalysisTemplate jobs
* Rollout name reference from a HPA scaleTargetRef
=> feat: kustomize support for Rollouts v0.8 and Experiment/AnalysisTemplates

utils/analysis/helpers.go, utils/analysis/helpers_test.go
=> fix: Modify arg verification to check ValueFrom

Dockerfile, manifests/base/argo-rollouts-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml
Use numeric user in Dockerfile. This allows the use of a security context in kubernetes with `runAsNonRoot: true`, because kubernetes can inspect the image and see that the USER is != 0.
Removed user and group creation, it isn't necessary to get a working docker image. Also when running in openshift, the user in the docker image is usually ignored and a random user is used to run the image.
=> feat: add security context to run as non-root

manifests/base/argo-rollouts-role.yaml, manifests/cluster-install/argo-rollouts-clusterrole.yaml, manifests/install.yaml, manifests/namespace-install.yaml
When running Rollouts with AnalysisTemplates in OpenShift clusters, I
found that I needed extra RBAC rules to get Rollouts and
AnalysisTemplates to work properly.
The update permission for rollouts/finalizers is required because of
this error message in the Rollout's status.conditions[].message:
Failed to create new replica set "cddemo-65c4c84fb": replicasets.apps
"cddemo-65c4c84fb" is forbidden: cannot set blockOwnerDeletion if an
ownerReference refers to a resource you can't set finalizers on: no RBAC
policy matched, <nil>
The update permission for analysisruns/finalizers is required because of
this error message in the AnalysisRun's status.message:
metric "smoketest" assessed Error due to consecutiveErrors (5) >
consecutiveErrorLimit (4): "Error Message: jobs.batch …
=> fix: add the update RBAC verb for some finalizers

rollout/controller.go, service/service.go, service/service_test.go, utils/service/service.go, utils/service/service_test.go
close https://github.com/argoproj/argo-rollouts/issues/506
=> Fix: remove hash selector after switching from bg to canary

docs/features/analysis.md
The property `backoffLimit` should be in `.job.spec.backoffLimit` rather than `.job.backoffLimit`.
=> docs: Fix backoffLimit in wrong place

docs/features/analysis.md
Fix the placement of `backoffLimit` field usage in example analysis job.
Should be on the same level as job spec.
Otherwise this defaults to 6.
https://kubernetes.io/docs/concepts/workloads/controllers/job/
=> docs: fix backoffLimit placement in example analysis job

go.mod, go.sum
make codegen results in the following error for developers with go 1.14
```bash
make codegen
./hack/update-mocks.sh
2020/06/25 18:48:45 internal error: package "fmt" without types was imported from "github.com/argoproj/argo-rollouts/metricproviders"
exit status 1
make: *** [mocks] Error 1
```
The issue appears to be with an upstream Golang library (per this [issue](https://github.com/golang/go/issues/37617#issuecomment-619184447). Upgrading the github.com/vektra/mockery upgrades the broken dependency without any changes to the mocks.
=> fix: Update mockery dependency to fix go 1.14 issue

rollout/controller_test.go, utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go
closes https://github.com/argoproj/argo-rollouts/issues/555.
@jessesuen do you know why we defaulted checkStepHashChange to return false if the currentStepHash is empty?
=> fix: Set the currentStepIndex to max after bg to canary

controller/metrics/rollout_test.go, controller/metrics/rollouts.go, docs/features/controller-metrics.md, go.sum
close #507
I've added two controller metrics.
* `rollout_info_replicas_available`
* `rollout_info_replicas_unavailable`
Rollout is a custom resource and therefore no metrics are provided by kube-state-metrics.
I think the replicas metrics are useful and well used.
I would be happy to provide replicas metrics in the Rollout controller.
=> feat: Add Rollout replicas metrics (#507)

.github/workflows/go.yml
The following PR is failing CI at the listing step [here](https://github.com/argoproj/argo-rollouts/pull/560/checks?check_run_id=854578360) 
Per this https://github.com/golangci/golangci-lint-action/issues/23#issuecomment-647177770 issue, the golangci maintainer recommends running the golangci as a separate job.
=> ci: Run Linting as a separate job

pkg/kubectl-argo-rollouts/info/rollout_info.go
https://github.com/argoproj/argo-rollouts/issues/568
As described in the issue, the `ActualWeight` for canary was wrong, so I've fixed it to show the right weight.
=> fix: Fix ActualWeight for canary

.github/workflows/gh-pages.yaml
Using the following example to auto-publish our docs on every master commit: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-ssh-private-key-deploy_key
=> doc: Add publish docs action

pkg/kubectl-argo-rollouts/cmd/list/list_rollouts.go
kubectl's `--all-namespaces` has an shortened alias `-A`.
It would be nice if kubectl-argo-rollouts has the same alias.
=> feat: add shortened option -A for --all-namespaces

rollout/controller.go, rollout/controller_test.go
The return statement at the end of syncHandler below will not execute as if both canary and bluegreen are nil, the validation on the spec will fail earlier.
https://github.com/argoproj/argo-rollouts/blob/fc0c05410702267062cdd766f7bb20876aca337b/rollout/controller.go#L376
https://github.com/argoproj/argo-rollouts/blob/fc0c05410702267062cdd766f7bb20876aca337b/pkg/apis/rollouts/validation/validation.go#L126
https://github.com/argoproj/argo-rollouts/blob/fc0c05410702267062cdd766f7bb20876aca337b/rollout/controller.go#L325-L326
Therefore, removing the unreachable statement at the end. Also added unit test for covering the case where strategy is not on the spec.
Ran make test and make test-bdd
=> fix: Remove unreachable code at rollout/controller

docs/features/analysis.md
Resolves https://github.com/argoproj/argo-rollouts/issues/363
Prometheus should use result[0] since it is accessing an array.
=> docs: fix analysis template docs for prometheus examples

utils/controller/controller.go
Resolves https://github.com/argoproj/argo-rollouts/issues/651
=> fix: add missing log message when a controller's syncHandler returns error

docs/FAQ.md, docs/features/analysis.md, docs/features/traffic-management/smi.md, docs/getting-started/smi/index.md, mkdocs.yml
The `yaml tab="Rollout"	` syntax must have stopped working at some point and the docs are formatted incorrectly. This fixes the problem.
=> docs: tab issues in analysis docs

.gitignore, Makefile, cmd/rollouts-controller/main.go, docs/CONTRIBUTING.md, pkg/apis/rollouts/v1alpha1/register.go, test/e2e/expectedfailures/malformed-analysisrun.yaml, test/e2e/expectedfailures/malformed-analysistemplate.yaml, test/e2e/expectedfailures/malformed-clusteranalysistemplate.yaml, test/e2e/expectedfailures/malformed-experiment.yaml, test/e2e/expectedfailures/malformed-rollout.yaml, test/util/util.go, utils/log/log.go, utils/log/log_test.go, utils/tolerantinformer/analysisrun.go, utils/tolerantinformer/analysistemplate.go, utils/tolerantinformer/clusteranalysistemplate.go, utils/tolerantinformer/experiment.go, utils/tolerantinformer/rollout.go, utils/tolerantinformer/tolerantinformer_test.go, utils/tolerantinformer/tollerantinformer.go
Resolves https://github.com/argoproj/argo-rollouts/issues/389, https://github.com/argoproj/argo-rollouts/issues/517
Uses a new, specialized "tolerant" dynamic informer which tolerates malformed objects that cannot unmarshal properly, preventing the issue where a unmarshallable object renders the entire controller unusable. When an object is discovered to be malformed, the informer will return a best effort version of the object via json unmarshalling (dropping all fields which could not be marshalled properly). This allows the controller to proceed as if the mistake was never made.
A consequence of this change is that the malformed field is silently dropped. But this is at least better behavior than stopping the controller.
=> fix: make controllers tolerant to spec marshalling errors

docs/features/specification.md
Hello,
Thank you for let me add some description to Rollout specification in #655 .
At the time I didn't understand that `paused` is not usually assumed to be used in the manifest (<- Is it right?).
So, I tried to add some more words to the description.
Thank you.
---
Checklist:
=> docs: Update description of paused field in specification

docs/features/kustomize/rollout-transform.yaml
canary.trafficRouting.alb.rootService was recently added, but we never added the kustomize name transformer to understand this field references a Service
=> fix: add missing Service name reference in trafficRouting/alb/rootService

rollout/analysis.go, rollout/bluegreen.go, rollout/bluegreen_test.go, rollout/canary.go, rollout/canary_test.go, rollout/context.go, rollout/controller.go, rollout/controller_test.go, rollout/experiment.go, rollout/pause.go, rollout/replicaset.go, rollout/replicaset_test.go, rollout/restart.go, rollout/restart_test.go, rollout/service.go, rollout/service_test.go, rollout/sync.go, rollout/sync_test.go, rollout/trafficrouting.go, rollout/trafficrouting_test.go, test/fixtures/e2e_suite.go, test/fixtures/when.go, utils/annotations/annotations.go
The Rollout Controller struct is currently overloaded. This change does the following:
1. removes all reconciliation logic in the Controller struct, and moves it into the existing rolloutContext object.
2. the rolloutContext object is no longer passed around from method to method, since all reconciliation functions are now member functions of the rolloutContext and can access the rollout fields/objects directly.
3. when a rolloutContext is instantiated, it gathers all objects associated with the rollout from the listers at the point of instantiation, rather than during the reconciliation
4. eliminates canaryCtx and blueGreenCtx objects, since they can be superseded by rolloutContext
There's probably more simplifications that can be done, but was already a huge refactor.
=> refactor: move reconciliation logic into rolloutContext

Makefile
Checklist:
I'm keeping this as a DRAFT PR because this is _just_ a change I did to run the docs locally (while the site is not fixed, see #707). I understand it's not ideal since it adds extra load on every `make serve-docs`. Feel free to close if you think it's the wrong approach. This is my first time using `mkdocs` or navigating the Argo project repositories so I'm very unfamiliar with the tooling and how it's used here.
This is related to #707 but I don't think it's the fix. I suspect the fix requires extra improvements on the `release-docs` task in the makefile but I'd not sure how to test the contents produced are the expected output.
=> [fix] Adds dependency to generate plugin-docs when serving locally (#707)

analysis/analysis.go, analysis/analysis_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/723
=> fix: analysis controller could get into a hotloop with terminated run

docs/getting-started/setup/values-grafana-istio.yaml
Istio dashboard links were broken, which broke our getting started examples
=> docs: fix grafana values to use compatible grafana dashboard

rollout/analysis.go, rollout/analysis_test.go, test/e2e/analysis_test.go, test/e2e/functional/analysistemplate-echo-job.yaml, test/e2e/functional/analysistemplate-web-background.yaml, test/e2e/functional/rollout-inline-analysis.yaml, test/fixtures/common.go, test/fixtures/e2e_suite.go, test/fixtures/then.go, test/fixtures/when.go
Resolves https://github.com/argoproj/argo-rollouts/issues/714
The check for detecting an initial deploy and conditionally creating a background analysisrun was incomplete. It did not catch a scenario where `Rollout.Status.StableRS == ""`. Not sure why this is true in v0.9. but not v0.8
This is stacked ontop of another PR so only look at https://github.com/argoproj/argo-rollouts/pull/722/commits/9d1424e117b1a8a400cad885c76760f200b96235
=> fix: do not create background analysisruns with initial deploy

rollout/canary.go, rollout/canary_test.go, rollout/context.go, rollout/controller.go, rollout/controller_test.go, rollout/service.go, rollout/sync.go, rollout/trafficrouting.go, test/fixtures/common.go, test/fixtures/e2e_suite.go, test/fixtures/given.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go, utils/replicaset/replicaset.go
Resolves https://github.com/argoproj/argo-rollouts/issues/721
The refactor to the rolloutContext introduced a problem with canary rollouts where the revision annotated on the ReplicaSet and Rollout was under by one. This is because it calculated the revision number by the count of older RSs, which was not calculated correctly during the refactor.
This change also makes it possible for E2E tests to run without an instanceID, so that they may run against a normally installed cluster controller.
NOTE: this PR is layered ontop of 9d1424e so only look at last commit
=> fix: revision annotation was off-by-one for canary rollouts

rollout/context.go, rollout/controller.go, rollout/controller_test.go, rollout/sync.go
Resolves https://github.com/argoproj/argo-rollouts/issues/720
Currently the rollout controller may operate on stale information in the informer cache. This can easily happen when a rollout is requeued into the workqueue while already in the middle of reconciliation. When this happens, the controller immediately re-reconciles the rollout, but this time operating on a stale version of the rollout in the cache (it is stale because the changes to the rollout saved in first reconciliation, have not yet made the round trip into the cache).
At best, this simply duplicates work. At worst, it causes incorrect behavior (such as re-pausing after an unpause as in #720)
There is a technique which argo workflows uses that writes back the updated resource back into the informer cache. Using this …
=> feat: writeback rollout updates to informer to prevent stale data

Makefile, hack/gen-crd-spec/main.go, hack/update-codegen.sh, manifests/crds/analysis-run-crd.yaml, manifests/crds/analysis-template-crd.yaml, manifests/crds/cluster-analysis-template-crd.yaml, manifests/crds/experiment-crd.yaml, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml
Setting `preserveUnknownFields: false` makes validation strict and can prevent nesting mistake like the following:
```yaml
strategy:
steps: [...]
```
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning
Checklist:
* I think this is a chore
=> chore: Set preserveUnknownFields: false to prevent mistake

pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/get/get_test.go, pkg/kubectl-argo-rollouts/info/info_test.go, pkg/kubectl-argo-rollouts/info/rollout_info.go, pkg/kubectl-argo-rollouts/info/testdata/rollout-aborted/analysisrun.yaml, pkg/kubectl-argo-rollouts/info/testdata/rollout-aborted/pod1.yaml, pkg/kubectl-argo-rollouts/info/testdata/rollout-aborted/rollout.yaml, pkg/kubectl-argo-rollouts/info/testdata/rollout-aborted/rs1.yaml, pkg/kubectl-argo-rollouts/info/testdata/rollout-aborted/rs2.yaml, pkg/kubectl-argo-rollouts/info/testdata/rollout-invalid/rollout-invalid.yaml, pkg/kubectl-argo-rollouts/info/testdata/testdata.go
The plugin will now show Errors such as InvalidSpec reason or when analysis fails. Examples:
```
Name:            rollout-invalid
Namespace:       default
Status:          ⚠ InvalidSpec
Strategy:        Canary
Step:
SetWeight:     100
ActualWeight:  100
Replicas:
Desired:       1
Current:       0
Updated:       0
Ready:         0
Available:     0
Errors:
* The Rollout "rollout-invalid" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"doesnt-match"}: `+"`selector`"+` does not match template `+"`labels`"+`
NAME               KIND     STATUS         AGE  INFO
⟳ rollout-invalid  Rollout  ⚠ InvalidSpec  7d
```
```
Name:            rollout-background-analysis
Namespace:       default
Status:          ✖ Degraded
Strategy:        Canary
Step:          0/2 …
```
=> feat: plugin now surfaces InvalidSpec errors and failed analysisrun messages

docs/features/analysis.md, manifests/crds/analysis-run-crd.yaml, manifests/crds/analysis-template-crd.yaml, manifests/crds/cluster-analysis-template-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, metricproviders/webmetric/webmetric.go, metricproviders/webmetric/webmetric_test.go, pkg/apis/rollouts/v1alpha1/analysis_types.go, pkg/apis/rollouts/v1alpha1/openapi_generated.go, test/e2e/functional/analysistemplate-web-background.yaml, test/fixtures/given.go, utils/evaluate/evaluate.go, utils/evaluate/evaluate_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/728, https://github.com/argoproj/argo-rollouts/issues/718, https://github.com/argoproj/argo-rollouts/issues/717
1. When using jsonPath, the web metric always converted the result into a string. This is why the `asFloat` and `asInt` helpers were introduced, in to convert these strings into numbers so that mathematical comparison could be performed. This change preserves the original types so that `asFloat` and `asInt` are no longer necessary (as long as the original data types are numeric).
2. Previously, `jsonPath` was a required field. This change allows `jsonPath` to be omitted, in which case the entire body is the payload.
3. Added an `insecure: true` field that allows the web metric to disable TLS host verification when making …
=> feat: web metrics preserve data types, allow insecure tls, and make jsonPath optional

rollout/analysis_test.go, rollout/bluegreen.go, rollout/bluegreen_test.go, rollout/controller_test.go, test/e2e/analysis_test.go, test/e2e/functional/rollout-bluegreen.yaml, test/e2e/functional_test.go, test/fixtures/common.go, test/fixtures/then.go, test/fixtures/when.go
Resolves https://github.com/argoproj/argo-rollouts/issues/750
Changes behavior of blue-green replica calculation to derive information from the active replicaset (if available). Otherwise, they are derived from all replicasets.
=> fix(controller): calculate bluegreen available replicas from active ReplicaSet

test/e2e/functional_test.go, test/fixtures/then.go
Adds two e2e test to:
* verify the bluegreen previewReplicaCount feature
* verify behavior when switching strategies from blue-green to canary
=> test: add e2e test for previewReplicaCount and bluegreen-to-canary

README.md
=> chore: add spotify as a user to readme

pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/get/get_test.go, pkg/kubectl-argo-rollouts/cmd/list/rollloutinfo.go, pkg/kubectl-argo-rollouts/info/info_test.go, pkg/kubectl-argo-rollouts/info/rollout_info.go, test/e2e/analysis_test.go, test/e2e/functional_test.go, test/fixtures/when.go
Resolves https://github.com/argoproj/argo-rollouts/issues/756
Unlike canary, in the case of blue-green, the plugin should **_not_** consider a Rollout as still Progressing if it has more Status.Replicas than Status.UpdatedReplicas. This is because the blue-green has a scaleDownDelay, where it can leave old replicasets scaled up for a long time. These scaled up replicasets do not impact the service (unlike canary) because they are not reachable from the active service. This logic is already in Argo CD Rollout health check, but not in the plugin.
Also, this PR changes the output of the plugin such that messages and errors show up in a new "messages" row, in a consistent manner like Argo CD. See below examples:
```
Name:            canary-demo
Namespace:       jesse-test
Status:          ◌ …
```
=> fix: blue-green scaleDownDelay was delaying Healthy status

docs/migrating.md
I think I'd have benefited of a stronger warning on the chance of downtime when migrating if not following the advice of having the Deployment next to the Rollout for the migration.
=> docs: Being a bit more clear on the chance of downtime when migrating Deployment->Rollout

docs/CONTRIBUTING.md, pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/get/get_test.go, pkg/kubectl-argo-rollouts/info/info_test.go, pkg/kubectl-argo-rollouts/info/replicaset_info.go, pkg/kubectl-argo-rollouts/info/testdata/blue-green/bluegreen-rollout.yaml, rollout/analysis.go, rollout/analysis_test.go, rollout/bluegreen.go, rollout/bluegreen_test.go, rollout/pause.go, test/e2e/analysis_test.go, test/fixtures/then.go, test/fixtures/when.go, utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go, utils/service/service.go, utils/service/service_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/774
The major change here is that we were using status.activeRS == currentPodHash to determine if rollout was fully promoted. However this is no longer true, because we now use status.stableRS == currentPodHash. 
fix: postPromotionAnalysis was broken
fix: blue-green fast-tracked rollbacks would still start analysis templates
fix: prePromotionAnalysis with previewReplicaCount did not start prePromotionAnalysis
feat(plugin): indicate the stable ReplicaSet for blue-green rollouts in plugin
=> fix(controller): blue-green with analysis was broken

test/e2e/analysis_test.go, test/e2e/canary_test.go, test/e2e/functional_test.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/777
The calculation change made in https://github.com/argoproj/argo-rollouts/pull/739, only accounted for the case when we were scaling up the canary, but not when we were scaling down the canary (e.g. in the case of abort). This caused a regression where we did not honor maxUnavailable during an abort.
=> fix(controller): controller did not honor maxUnavailable during abort

test/e2e/functional_test.go, test/fixtures/when.go, utils/service/service.go, utils/service/service_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/800
Checklist:
=> fix(controller): fix unhandled panic from malformed rollout

docs/features/kustomize/rollout-transform.yaml, test/kustomize/rollout/expected.yaml, test/kustomize/rollout/rollout.yaml
The rollout-transform was incorrect and didn't match our type definitions. AnalysisTemplates reference use the field `templateName:` and not `name:`
=> fix: rollout kustomize transform analysis ref should use templateName instead of name

pkg/apis/rollouts/validation/validation.go, pkg/apis/rollouts/validation/validation_references.go, pkg/apis/rollouts/validation/validation_references_test.go, rollout/analysis_test.go, rollout/context.go, rollout/controller.go, rollout/controller_test.go, test/e2e/functional_test.go, test/fixtures/then.go
Resolves https://github.com/argoproj/argo-rollouts/issues/754, https://github.com/argoproj/argo-rollouts/issues/713
1. When a Rollout has an InvalidSpec, we will requeue the Rollout every ~20 seconds to detect if the situation has fixed itself (e.g. the referenced Service was created).
2. BackgroundAnalysis was not being verified
3. Rename CanaryStep to InlineAnalysis
=> fix: background analysis refs were not verified. requeue InvalidSpec rollouts

docs/features/bluegreen.md, rollout/bluegreen.go, rollout/bluegreen_test.go, test/e2e/functional_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/813
We were scaling down old ReplicasSets prematurely (by 1), not honoring scaleDownDelayRevisionLimit
=> fix: scaleDownDelayRevisionLimit was off by one

pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/undo/undo.go, pkg/kubectl-argo-rollouts/cmd/undo/undo_test.go
I created `kubectl argo rollouts undo` command in the same way as `kubectl rollout undo` command.
I referred to the following program.
https://github.com/kubernetes/kubectl/blob/master/pkg/polymorphichelpers/rollback.go
Refs #575 
Checklist:
=> feat: Add undo command in kubectl plugin. Fixes #575

Makefile, docs/features/analysis.md, docs/features/canary.md, go.sum, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, rollout/canary.go, rollout/canary_test.go, rollout/context.go, rollout/controller_test.go, rollout/restart.go, rollout/sync.go, test/e2e/canary_test.go, test/e2e/functional/ephemeral-labels.yaml, test/fixtures/common.go, test/fixtures/then.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go, utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/455
Adds support for setting ephemeral metadata (annotations/labels) which get updated on the Pods/ReplicaSets during an update. Example syntax:
```yaml
spec:
strategy:
canary:
stableMetadata:
labels:
role: stable
canaryMetadata:
labels:
role: canary
steps:
- setWeight: 50
- pause: {}
```
Checklist:
=> feat(controller): add support for canary/stable ephemeral metadata

analysis/analysis.go, analysis/analysis_test.go, analysis/controller.go, analysis/controller_test.go, cmd/rollouts-controller/main.go, controller/controller.go
Using a list cache of secrets is not needed as we do not need to react
to any changes and we can always fetch the individual secrets we need
for analysis arguments when the time comes. For large kubernetes
clusters with thousands of secrets this causes the argo-rollouts
controller to be unbootable.
Checklist:
=> fix: (controller boot) Do not cache all cluster Secrets - fetch them on demand. Fixes #798

analysis/controller_test.go, experiments/controller_test.go, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/kubectl-argo-rollouts/cmd/promote/promote.go, pkg/kubectl-argo-rollouts/cmd/promote/promote_test.go, rollout/analysis.go, rollout/analysis_test.go, rollout/bluegreen.go, rollout/canary.go, rollout/canary_test.go, rollout/controller_test.go, rollout/experiment.go, rollout/service.go, rollout/sync.go, rollout/sync_test.go, test/e2e/analysis_test.go, test/e2e/functional_test.go, test/fixtures/common.go, test/fixtures/when.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/573
Introduces the `--full` flag to the `promote` command, for fully promoting a rollout which is in the middle of update, including blue-green rollouts. Adds controller changes to support it. Fully promoting a rollout will cause the rollout to ignore Abort and Pause conditions, steps, and skip analysis. 
```shell
kubectl argo rollouts promote --full ROLLOUT
```
Implementation details: full promotion is accomplished by introducing:
```yaml
status:
promoteFull: true
```
which the plugin (and eventually Argo CD) will set to true when full promotion is desired. The controller understands when this flag is set, and skips abort/pause/analysis to get to the new version ASAP.
=> feat(controller): add full rollout promotion (skip analysis, pause, steps)

docs/features/restart.md, rollout/restart.go, rollout/restart_test.go, test/e2e/functional_test.go
When restarting pods (using canary strategy), rollouts will restart up to maxUnavailable pods at a time.
=> feat(controller): restart pods up to maxUnavailable at a time

pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/lint/lint.go, pkg/kubectl-argo-rollouts/cmd/lint/lint_test.go, pkg/kubectl-argo-rollouts/cmd/lint/testdata/invalid.yml, pkg/kubectl-argo-rollouts/cmd/lint/testdata/valid.yml
This allows a user to lint the rollout objects via the CLI, in order to
catch mistakes before applying or committing to a git repo.
I didn't write any unit tests for this because there are already comprehensive unit tests for the actual validation libraries. I didn't think unit tests for wrapping the validation libraries in a cobra cmd were necessary. If my assumption was wrong, please let me know!
Closes #695
Checklist:
=> feat: Implement kubectl argo rollouts lint

pkg/kubectl-argo-rollouts/info/info_test.go, pkg/kubectl-argo-rollouts/info/rollout_info.go
Checking for numeric observedGeneration is not a reliable indicator of a v0.9 rollout. We also have to check if that observedGeneration is > metadata.generation, since that would indicate that `metadata.generation` isn't being used as observedGeneration.
=> fix: plugin incorrectly treated v0.9 rollout as v0.10 when it had numeric observedGeneration

.github/workflows/docker-publish.yml
Fix broken image push due to extra parens in echo command. 
Signed-off-by: Jonah Back <jonah@jonahback.com>
Checklist:
=> fix(build): remove extra set of parens in echo command

hack/update-manifests.sh, manifests/namespace-install.yaml, manifests/namespace-install/kustomization.yaml
This supersedes https://github.com/argoproj/argo-rollouts/pull/877 and fixes update-manifests.sh to use `kubectl kustomize` to generate output for consistency.
=> fix(manifests): Add missing RoleBinding file

docs/features/experiment.md, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/experiment_types.go, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, rollout/experiment.go, test/e2e/functional/rollout-experiment-analysis.yaml
Resolves https://github.com/argoproj/argo-rollouts/issues/878
The type definitions for a canary experiment step was missing the `requiredForCompletion` field, and so it was impossible to use this feature for an Experiment which was launched by a Rollout. The fix is to add the `requiredForCompletion` field to RolloutExperimentStepAnalysisTemplateRef, and carry over the value when creating the Experiment.
E2E test has been updated to exercise this feature. 
=> fix: requiredForCompletion did not work for an experiment started by a rollout

docs/getting-started/setup/index.md, rollout/canary.go, rollout/sync.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go, utils/replicaset/replicaset.go
Resolves https://github.com/argoproj/argo-rollouts/issues/883
The ephemeral metadata injection feature did not account for mutating webhooks when it modified pods. The incorrect implementation was blindly copying the ReplicaSet's `spec.template.metadata` to the child Pods, not considering that the Pod could have had metadata injected by a mutating webhook (e.g. istio sidecar injector).
This change makes it such that when removing metadata, the rollout controller will only remove metadata that it had previously injected. 
=> fix: ephemeral metadata injection was dropping metadata injected by mutating webhooks

CHANGELOG.md, docs/features/restart.md, hack/update-manifests.sh, manifests/install.yaml, manifests/namespace-install.yaml, manifests/role/argo-rollouts-clusterrole.yaml, rollout/restart.go, rollout/restart_test.go, rollout/sync.go, test/e2e/functional_test.go, test/fixtures/common.go, test/fixtures/e2e_suite.go, test/fixtures/when.go
Resolves https://github.com/argoproj/argo-rollouts/issues/908
This change switches the controller to use the evict API instead of the delete API for the pod restart feature. By using evict instead of delete, any PodDisruptionBudget targeting rollout pods will be honored.
=> fix: switch pod restart to use evict API to honor PDBs

pkg/kubectl-argo-rollouts/cmd/create/create.go
Signed-off-by: zhouchencheng <zhouchencheng@bilibili.com>
affected by #932, rollout cli can not get rollout in other namespaces except default.    
Checklist:
=> bugfix: get rollout always return not found except default namespace

docs/features/bluegreen.md, docs/features/restart.md, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, utils/defaults/defaults.go, utils/defaults/defaults_test.go, utils/replicaset/replicaset.go
=> feat: Add ability to restart maxUnavailable pods to BlueGreen strategy

.github/pull_request_template.md
Signed-off-by: Laurent Benchimol <laurent_benchimol@intuit.com>
Checklist:
* [x ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x ] I've signed the CLA.
* [ x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x ] My builds are green. Try syncing with master if they are not. 
* [ x] My organization is added to …
=> chore: Change PR template to reflect CLA->DCO

utils/replicaset/canary.go
Signed-off-by: zhouchencheng <zhouchencheng@bilibili.com>
https://github.com/argoproj/argo-rollouts/blob/master/utils/replicaset/replicaset.go#L54
if no modified occur, `SyncReplicaSetEphemeralPodMetadata ` func does not return a copy rs. 
And this rs in memory may be modified in `RemoveInjectedAntiAffinityRule`.
Checklist:
=> fix: should use copy rs before modify fields.

README.md, USERS.md, docs/features/ephemeral-metadata.md, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, rollout/bluegreen.go, rollout/canary.go, rollout/canary_test.go, rollout/ephemeralmetadata.go, rollout/ephemeralmetadata_test.go, rollout/sync.go, test/e2e/bluegreen_test.go, test/e2e/canary_test.go
=> feat(controller): Add support for  ephemeral metadata on BlueGreen rollouts. Fixes #973

docs/features/canary.md, pkg/apis/rollouts/v1alpha1/types.go, utils/defaults/defaults.go, utils/defaults/defaults_test.go, utils/replicaset/replicaset.go
=> fix: Set Canary Strategy default maxUnavailable to 25%

Makefile, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, pkg/apis/rollouts/validation/validation_test.go, rollout/analysis_test.go, rollout/bluegreen.go, rollout/bluegreen_test.go, rollout/canary.go, rollout/pause.go, rollout/service.go, test/e2e/analysis_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/990
Fixes an issue where blue-green would be paused prematurely during prePromotionAnalysis.
=> fix: blue-green rollouts could pause prematurely during prePromotionAnalysis

USERS.md, rollout/canary_test.go, rollout/service.go
feat: Wait for first batch of new RS pods to be ready before adding canary selector label to an SVC. Fixes #1026
- Last commit does a bit of extra refactoring for the `reconcileStableAndCanaryService` function (can easily be reversed if not desirable).
- Moves a bit of duplicated logic, previously executed for both canary and stable SVCs and RSs, into it's own function `ensureSVCTargets`.
- Adds a new function `newRSReady` which needs to return `true` before the canary SVC gets the newRS selector label.
- The newRS needs to exist, not have `ReadyReplicas` < `Replicas` and not have `0` `ReadyReplicas`, thereby ensuring the first batch of Pods are ready before targeting the newRS.
(Was also considering perhaps making this label addition an optional `step` so when specified, the user can …
=> feat: Wait for canary RS to have ready replicas before shifting labels

analysis/analysis.go, analysis/analysis_test.go, metricproviders/datadog/datadog.go, metricproviders/newrelic/newrelic.go, metricproviders/prometheus/prometheus.go, metricproviders/wavefront/wavefront.go, metricproviders/wavefront/wavefront_test.go, metricproviders/webmetric/webmetric.go, utils/evaluate/evaluate.go, utils/evaluate/evaluate_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/1012
Resolves https://github.com/argoproj/argo-rollouts/issues/1006
Resolves https://github.com/argoproj/argo-rollouts/issues/1008
fix: Wavefront query will now allow data points to return outside the time window
fix: expr evaluation errors were not surfaced in the message
fix: metrics which errored, were not retried at 10s error interval
Also, datapoint drift is calculated as a convenience for debugging.
=> fix: wavefront queries would return no datapoints. surface evaluate errors. retry errors faster

pkg/kubectl-argo-rollouts/cmd/create/create.go
modify before:
[root@k8s-master-1 argo-rollouts]# grep namespace examples/rollout-canary.yaml
namespace: base
[root@k8s-master-1 argo-rollouts]# kubectl argo create -f  examples/rollout-canary.yaml
Error: the namespace of the provided object does not match the namespace sent on the request
modify after:
[root@k8s-master-1 argo-rollouts]# grep namespace examples/rollout-canary.yaml
namespace: base
[root@k8s-master-1 argo-rollouts]# kubectl argo create -f  examples/rollout-canary.yaml
rollout.argoproj.io/rollout-canary created
[root@k8s-master-1 argo-rollouts]#
Signed-off-by: zhaozhiqiang <zhaozhiqiang@lixiang.com>
Checklist:
=> bugfix:argo create command not support namespace in yaml file

pkg/apis/rollouts/validation/validation_references.go, pkg/apis/rollouts/validation/validation_references_test.go
Signed-off-by: zhouchencheng <zhouchencheng@bilibili.com>
fix #1032
Checklist:
=> fix analysis template arguments validate

pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/status/status.go, pkg/kubectl-argo-rollouts/cmd/status/status_test.go
Closes #596
This replicates the `kubectl rollout status deployment [--watch] <name>` command, but for Rollouts.
This is implemented as:
```
kubectl argo rollouts status --watch=false <name>
kubectl argo rollouts status --watch <name>
```
The flags and defaults for them replicate the `kubectl rollout status deployment <name>` command. As in it, `--watch` is default and the default timeout is 5 minutes.
---
Checklist:
* (a) See #596
=> feat: Implement rollout status command. Fixes #596

docs/analysis/newrelic.md, metricproviders/newrelic/newrelic.go, metricproviders/newrelic/newrelic_test.go
Enables use of the provider by people accessing new relic via a proxy. Users should set either a `region` key or a `base-url` key in their new relic secret, and if neither is provided the provider will continue to default to the US region.
Checklist:
=> feat: support a custom base URL for the new relic provider

rollout/controller.go, test/e2e/expectedfailures/malformed-rollout-ephemeral.yaml, test/e2e/functional_test.go, utils/tolerantinformer/tolerantinformer_test.go, utils/unstructured/unstructured.go
Resolves https://github.com/argoproj/argo-rollouts/issues/1045
Fixes a controller panic recently introduced in pre-v1.0
=> fix: controller panic with ephemeral containers with bad resource qty

utils/replicaset/canary.go
Signed-off-by: zhouchencheng <zhouchencheng@bilibili.com>
Checklist:
=> fix: calculate scale down count.

pkg/apis/rollouts/validation/validation_references.go, pkg/apis/rollouts/validation/validation_references_test.go
- return error if arguments do not match between rollout spec and analysis template
close #1052
=> fix: verify analysis arguments name with those in the rollout

hack/gen-crd-spec/main.go, manifests/crds/analysis-run-crd.yaml, manifests/crds/analysis-template-crd.yaml, manifests/crds/cluster-analysis-template-crd.yaml, manifests/crds/experiment-crd.yaml, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml
Resolves https://github.com/argoproj/argo-rollouts/issues/1067
After switching from v1beta1 to v1 CRD, the default value of `spec.preserveUnknownFields` in Kubernetes went from true to false. Because this field is unmanaged in our previous and current set of manifests, when upgrading from the v1beta1 CRD version to v1, it would encounter the following error:
> spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
This is because when the v1 CRD was attempted to be applied (over the existing v1beta1 version), K8s rejected the update stating the value must be false (since a v1 manifest was being applied). This change explicitly sets it to false so that upgrades can happen from v0.10 to v1.0
Also removes our removeDescriptions workaround now …
=> fix: spec.preserveUnknownFields must be explicitly false to allow upgrades from apiextensions.k8s.io/v1beta1

.github/workflows/docker-publish.yml, Makefile, manifests/base/argo-rollouts-deployment.yaml, manifests/base/kustomization.yaml, manifests/install.yaml, manifests/namespace-install.yaml
Publish controller and plugin images automatically to quay using github actions
=> chore: publish plugin image automatically. move to quay.io

.dockerignore
=> chore: Add node_modules to dockerignore

Makefile, docs/features/kustomize/rollout-transform.yaml, test/kustomize/rollout/expected.yaml, test/kustomize/rollout/rollout.yaml, test/kustomize/test.sh
Teaches kustomize about:
* istio DestinationRule references
* workload references to Deployments
* ambassador Mapping references
Also updates kustomize test to assume v4.0
=> feat: add new v1.0 features to kustomize transformer configuration

pkg/apis/rollouts/validation/validation_references.go, pkg/apis/rollouts/validation/validation_references_test.go, rollout/analysis.go, test/e2e/analysis_test.go, utils/analysis/helpers.go, utils/analysis/helpers_test.go, utils/experiment/experiment.go, utils/experiment/experiment_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/1107
When we create an AnalysisRun from the AnalysisTemplate, we were inadvertently randomizing the list of metrics and arguments from the merged AnalysisTemplate. This caused a problem where we would create many AnalysisTemplates, since when we compared the existing run to the run we want to create, it was considered different and we would recreate the run.
This change also partially reverts https://github.com/argoproj/argo-rollouts/commit/ee06d5cc0969049427e1044110ed3a6b2a4a2320, which caused a regression where multiple analysis templates could not be merged properly.
=> fix: AnalysisRuns could be created continuously due to non-deterministic specs

.github/workflows/docker-publish.yml, .github/workflows/release.yaml
* fix: `latest` docker tag will now be built from `master` branch. 
* fix: the release build still did not prefix `v` in the image tag
=> fix: build 'latest' tag from master. prefix 'v' in release builds

test/e2e/functional_test.go
- the deployment uses labels: app: rollout-ref-deployment,
while the service use app:rollout-bluegreen. The PR fixes
the mismatch
=> fix: e2e test mismatch service selected lables to the deployment

pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/types_test.go, utils/annotations/annotations.go, utils/annotations/annotations_test.go
Use trconv.ParseInt method with fixed-size 32 bit int instead of Atoi to avoid undesirable program behavior
Checklist:
=> fix: parse string to fixed-size int32

README.md
Added reference to a DoorDash blog post about a custom Kubernetes Controller built on top of Argo Rollouts to achieve a gradual code release process.
Checklist:
=> Add DoorDash blog post reference

rollout/controller.go, rollout/controller_test.go, test/e2e/functional_test.go, test/fixtures/e2e_suite.go
- the rollout status is set to degraded if the referenced
deployment doesn't exist, while the replicaset of the
rollout remains
Address #1123
=> fix: set rollout status to degraded for non-existent deploy 

.github/workflows/codeql.yml
Fixes the following errors with the code scanning action:
```
Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
...
...
Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
```
=> chore: don't run code scanning on PR push events

controller/metrics/rollouts.go, experiments/replicaset.go, rollout/analysis_test.go, rollout/bluegreen_test.go, rollout/canary_test.go, rollout/controller_test.go, rollout/sync.go, rollout/sync_test.go, rollout/trafficrouting_test.go, test/e2e/functional_test.go, test/fixtures/common.go, test/fixtures/e2e_suite.go, utils/conditions/conditions.go, utils/record/record.go, utils/record/record_test.go
This emits kubernetes events for:
* when a rollout becomes paused by the controller (RolloutPaused)
* when a rollout automatically resumes after a pause (RolloutResumed)
Also adds more details about events for NewReplicaSetCreated and ScalingReplicaSet
=> feat: record events for RolloutPaused and RolloutResumed

pkg/kubectl-argo-rollouts/cmd/lint/lint.go, pkg/kubectl-argo-rollouts/cmd/lint/lint_test.go, pkg/kubectl-argo-rollouts/cmd/lint/testdata/invalid-multiple-docs.yml, pkg/kubectl-argo-rollouts/cmd/lint/testdata/invalid-unknown-field.yml
- to support use cases where the yaml file may contain other objects like
deploy, service, etc
The current lint implementation does not report error if an invalid rollout yaml contains another valid resource like service - added example in unit test.
=> feat: lint supporting rollout in multiple doc

pkg/kubectl-argo-rollouts/cmd/status/status.go, pkg/kubectl-argo-rollouts/cmd/status/status_test.go
=> fix: timeout should take a string

Dockerfile, USERS.md
Checklist:
* [x ] My builds are green. Try syncing with master if they are not.
=> chore: use a base image that has a shell for the kubectl plugin image

USERS.md, rollout/trafficrouting.go, rollout/trafficrouting/ambassador/ambassador.go, rollout/trafficrouting/ambassador/ambassador_test.go
=> fix: Add edge case handling to traffic routing

pkg/kubectl-argo-rollouts/cmd/lint/lint.go, pkg/kubectl-argo-rollouts/cmd/lint/lint_test.go, pkg/kubectl-argo-rollouts/cmd/lint/testdata/valid-with-another-empty-object.yml
- empty object may appear in the yaml file (e.g., helm2)
In this case, go-yaml will decode to null, which will
be interrepted as "null" in json. In this case,
yaml.UnmarshalStrict will fail.
Checklist:
=> fix: lint valid file with another empty object

docs/features/traffic-management/istio.md
Based on my understanding, I think this the destination rule comment should contains `stable` instead of `canary`. 
I will close the PR if the existing comment is correct, or change it to make more clear like `during rollout it will be replaced as stable pod hash, once rollout is completed then it will be replaced by canary pod hash (which is now the new stable)`.
Checklist:
=> Updates (istio.md): changes the comment in DR 

analysis/analysis.go, analysis/analysis_test.go, pkg/apis/rollouts/validation/validation_references.go, pkg/apis/rollouts/validation/validation_references_test.go, test/e2e/analysis_test.go, test/e2e/functional/rollout-secret.yaml, utils/analysis/factory.go, utils/analysis/factory_test.go
=> fix: AnalysisRun args could not be resolved from secret

rollout/controller.go
=> fix: make function call consistent with otherRSs definition

rollout/controller.go, rollout/controller_test.go
=> fix: Fix error check in validation for AnalysisTemplates not found

pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/validation/validation.go, pkg/apis/rollouts/validation/validation_test.go, rollout/temlateref.go, rollout/temlateref_test.go, test/e2e/functional_test.go
=> fix: workload rollout spec is invalid template is not empty

controller/metrics/analysis.go, controller/metrics/analysis_test.go, controller/metrics/prommetrics.go
Will fix: 
Checklist: https://github.com/argoproj/argo-rollouts/issues/1239
=> fix: analysis with multiple metrics

Dockerfile
=> fix: avoid using root user in plugin container

examples/dashboard.json
=> fix: the wrong panel title of the sample dashboard

go.mod, rollout/trafficrouting/istio/istio.go, rollout/trafficrouting/istio/istio_test.go, rollout/trafficrouting/istio/istio_types.go
- add Extra to DestinationRule to hold any other fields from istio's
destinationRule
- handle any extra fields that could be introduced to the subsets
in istio's destinationRule fields
- unit test added
close #1238 
Checklist:
=> fix: missing fields in destinationrule

pkg/kubectl-argo-rollouts/cmd/status/status.go, rollout/analysis_test.go, rollout/bluegreen_test.go, rollout/canary_test.go, rollout/controller_test.go, rollout/sync.go, test/e2e/functional_test.go, test/fixtures/when.go
=> fix: rollout paused longer than progressDeadlineSeconds would briefly degrade

docs/features/specification.md, docs/features/traffic-management/istio.md, docs/getting-started/istio/index.md, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apiclient/rollout/rollout.swagger.json, pkg/apis/rollouts/v1alpha1/generated.proto, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/validation/validation.go, rollout/trafficrouting/istio/istio.go, rollout/trafficrouting/istio/istio_test.go, test/e2e/functional_test.go, test/e2e/istio/istio-subset-split-single-route.yaml, test/e2e/istio_test.go
Currently, the istio configuration in the rollout requires a VirtualService HTTPRoute name to be explicitly specified.
This change makes it possible to infer the HTTP route in the event that there is only a single route specified, simplifying the Rollout config. e.g.:
```yaml
strategy:
canary:
trafficRouting:
istio:
virtualService: 
name: istio-subset-split-single-route-vsvc
destinationRule:
name: istio-subset-split-single-route-destrule
canarySubsetName: canary
stableSubsetName: stable
```
=> feat: allow VirtualService HTTPRoute to be inferred if there is single route

ui/src/app/components/rollout/rollout.tsx
=> fix(ui): UI crashes on rollout view due to undefined status

hack/gen-crd-spec/main.go
- openAPIV3Schema is the only validation schema
Checklist:
=> chore: remove unused code of crd generation

pkg/kubectl-argo-rollouts/cmd/undo/undo.go, pkg/kubectl-argo-rollouts/cmd/undo/undo_test.go, pkg/kubectl-argo-rollouts/info/testdata/canary/canary-ref-deploy.yaml, pkg/kubectl-argo-rollouts/info/testdata/canary/canary-rollout2.yaml, pkg/kubectl-argo-rollouts/info/testdata/canary/canary-rollout3.yaml, pkg/kubectl-argo-rollouts/info/testdata/canary/canary-rs.yaml, pkg/kubectl-argo-rollouts/info/testdata/canary/old-rs.yaml, pkg/kubectl-argo-rollouts/info/testdata/canary/stable-rs.yaml, pkg/kubectl-argo-rollouts/info/testdata/testdata.go
- rollback by patching the referenceed object, e.g., deployment, replicaset
- unit test is added
close #1254 
Checklist:
=> fix: undo referenced object for workloadRef rollout

controller/controller.go
- dynamicClientSet is redundant
Checklist:
=> fix: remove unused field in Manager struct

manifests/install.yaml, manifests/namespace-install.yaml, manifests/role/argo-rollouts-clusterrole.yaml
=> fix: missing rbac for configmaps and secrets

rollout/controller.go
- defaulting replica after workload ref is resolved
close #1302 
Checklist:
=> fix: avoid invalid replica in workloadRef

controller/controller.go, docs/migrating.md, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apiclient/rollout/rollout.swagger.json, pkg/apis/rollouts/v1alpha1/types.go, rollout/sync.go, rollout/sync_test.go, rollout/temlateref.go, rollout/temlateref_test.go, test/e2e/canary_test.go, test/e2e/functional_test.go, utils/annotations/annotations.go, utils/annotations/annotations_test.go, utils/rollout/rolloututil.go, utils/rollout/rolloututil_test.go
- Add a "rollout.argoproj.io/workload-generation" annotation to
the rollout metadata, which equals to the generation of reference
workload
- workload-generation is updated when the referenced workload is
updated.
- status.workloadObservedGeneration records the observed generation
of the rollout
- e2e test is updated
close #1189 
Checklist:
=> feat: add workload-ref/generation to rollout

pkg/apis/rollouts/validation/validation.go, pkg/apis/rollouts/validation/validation_test.go, pkg/kubectl-argo-rollouts/cmd/lint/lint_test.go, pkg/kubectl-argo-rollouts/cmd/lint/testdata/valid-workload-ref.yaml
=> fix: lint subcommand for workload ref rollout

manifests/base/argo-rollouts-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml
=> chore: add liveness and readiness probe to install manifest

docs/getting-started/ambassador/index.md, manifests/install.yaml, manifests/namespace-install.yaml, manifests/role/argo-rollouts-clusterrole.yaml, rollout/trafficrouting/ambassador/ambassador.go, rollout/trafficrouting/ambassador/ambassador_test.go, utils/defaults/defaults.go
Signed-off-by: Alix Cook <alixcook@datawire.io>
Allow argo rollouts to work with emissary and edge stack v2, recently announced as developer preview.
See [our release notes](https://www.getambassador.io/docs/edge-stack/2.0/release-notes) for more information.
I'd like to merge this feature, and then update our docs and the argo-docs in a subsequent PR so that I don't have to worry about releasing these things in lockstep.
Checklist:
=> feat: argo rollout compatibility with emissary and edge stack v2.0

test/e2e/istio_test.go, utils/replicaset/canary.go
=> fix: abort scaledown stable RS for canary with traffic routing

examples/dashboard.json
- Switch to stat panel
- fix missing labels in some metrics on example dashboard
- add job label to avoid interference with service discovery results
- replace deprecated rollout_phase with rollout_info
Checklist:
=> feat: example dashboard - add rollout stat row

docs/features/scaledown-aborted-rs.md, docs/features/specification.md, manifests/crds/rollout-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apiclient/rollout/rollout.swagger.json, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, rollout/bluegreen_test.go, rollout/replicaset.go, rollout/replicaset_test.go, rollout/sync.go, test/e2e/analysis_test.go, test/e2e/canary_test.go, test/e2e/functional/canary-scaledownonabort.yaml, test/e2e/functional/canary-unscaledownonabort.yaml, test/e2e/functional_test.go, test/fixtures/then.go, utils/defaults/defaults.go, utils/defaults/defaults_test.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
=> feat: introduce abortScaleDownDelaySeconds to control scale down of preview/canary upon abort

utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go
Partially fixes https://github.com/argoproj/argo-rollouts/issues/1356
=> fix: unsolicited rollout after upgrade from v0.10->v1.0 when pod was using service account

test/e2e/istio/istio-rollout-abort-delete-all-canary-pods.yaml, test/e2e/istio_test.go, utils/replicaset/canary.go
Signed-off-by: Chinmoy Samant chinmoy.samant@salesforce.com
fixes #1337 
Checklist:
=> fix: Abort rollout removes all canary pods for setCanaryScale. Fixes #1337

rollout/replicaset.go, rollout/replicaset_test.go, rollout/sync.go, test/e2e/istio_test.go, utils/defaults/defaults.go, utils/defaults/defaults_test.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
Recent PR did not rebase ontop of new scaledowndelay on abort behavior and the two caused a conflict in behavior
=> fix: zero-value abortScaleDownDelay was not honored with setCanaryScale

test/e2e/bluegreen_test.go, test/e2e/functional_test.go, test/fixtures/when.go, utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/1383
=> fix: Promote full did not work against BlueGreen with previewReplicaCount

.github/workflows/release.yaml
=> chore: release workflow docker build context should use local path and not git context

docs/features/bluegreen.md, rollout/analysis_test.go, rollout/bluegreen.go, rollout/bluegreen_test.go, rollout/canary_test.go, rollout/ephemeralmetadata_test.go, rollout/experiment_test.go, rollout/sync.go, rollout/sync_test.go, test/e2e/functional_test.go, utils/conditions/conditions.go
Resolves https://github.com/argoproj/argo-rollouts/issues/1151
This change implements the following behavior when creating the preview service and changing selectors.
1. create preview replicaset with size 0
2. retarget preview service to replicaset hash
3. scale up the preview replicaset
Previously we would create the preview replicaset with the desired size (without the separate create and scale steps). This will allow *all* pods of the preview to be considered for readiness gate injection by the AWS LoadBalancer controller
=> fix: retarget blue-green preview service before scaling up preview replicaset

pkg/kubectl-argo-rollouts/cmd/create/create.go
=> fix: nil pointer in create analysisrun cmd

docs/getting-started/istio/index.md, test/e2e/istio/istio-host-http-tls-split.yaml, test/e2e/istio_test.go
- remove localhost in example as incompabile with virtual host
Checklist:
=> fix: missing e2e test for istio tls route in rollout

analysis/analysis.go, test/e2e/analysis_test.go, test/e2e/functional/analysistemplate-multiple-job.yaml, test/e2e/functional/analysistemplate-sleep-job.yaml, test/e2e/functional/rollout-inline-analysis.yaml, test/e2e/functional/rollout-inline-multiple-analysis.yaml, test/fixtures/then.go
Signed-off-by: hari rongali <hari_rongali@intuit.com>
fixes https://github.com/argoproj/argo-rollouts/issues/1360
Checklist:
=> fix: analysis runs to wait for all metrics to complete

OWNERS
@huikang has been nominated (sponsors: @jessesuen, @alexmt) and has been approved as a reviewer for his contributions to argo-rollouts. Welcome @huikang!
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
=> docs: add @huikang as a reviewer

test/e2e/canary_test.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
Signed-off-by: hari rongali <hari_rongali@intuit.com>
fixes https://github.com/argoproj/argo-rollouts/issues/1415
Checklist:
=> fix: canary scaledown with maxsurge

.github/workflows/e2e.yaml
PR fixes e2e tests CI configuration. See title.
=> chore: skip e2e only if workflow started manually with debug enabled

docs/getting-started/istio/index.md
This PR adds some more clarification around handling of TLS/HTTPS routes in Istio-based Argo Rollouts.
[Preview Link](https://github.com/argoproj/argo-rollouts/blob/ac1ab679f5993fa0831fa1a5f4484ca306bd69d4/docs/getting-started/istio/index.md)
**Checklist:**
=> chore: Add some more explanation around TLS routes in Istio-based Rollouts README

docs/features/kustomize.md, docs/features/kustomize/rollout_cr_schema.json, go.mod, hack/gen-crd-spec/main.go, manifests/cluster-install/kustomization.yaml, test/kustomize/rollout/expected.yaml, test/kustomize/rollout/kustomization.yaml
- openAPI schema for kustomize rollout
close #1210 
Checklist:
=> feat: kustomize rollout: add openapi to doc and examples

rollout/canary.go, rollout/canary_test.go, rollout/service.go, utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go
This fixes an issue (that exists only in master) where a ReplicaSet count would flap from 0 to N when an update was interrupted by an apply of a third pod spec. The scenario is:
1. Traffic routed canary Rollout is in middle of updating from V1 -> V2
2. V3 version of Rollout was applied
3. The ReplicaSet for V2 would flap from 0 to N on different reconciliations
The fix is that we should choose to leave V2 up and running until we believe it is safe to scale it down (because V1 and V3 have reached full readiness).
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
=> fix: replicaset count would flap when interrupting update with new pod spec

pkg/kubectl-argo-rollouts/cmd/create/create.go, pkg/kubectl-argo-rollouts/cmd/create/create_test.go, pkg/kubectl-argo-rollouts/cmd/create/testdata/analysis-template-no-name.yaml, utils/analysis/helpers.go, utils/analysis/helpers_test.go
- set templateName if analsysit template has name in metadata
- remove resourceVersion and fix spec.args 
fix #1473 
Checklist:
=> fix: create analysisrun cmd using template generated name

Dockerfile.dev, docs/features/traffic-management/alb.md, utils/aws/aws.go, utils/aws/aws_test.go
The v1.1 AWS target group verification feature was not working when the service was using named instead of numeric ports.
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
=> fix: target group verification did not work with named ports

mkdocs.yml, pkg/kubectl-argo-rollouts/cmd/cmd.go, pkg/kubectl-argo-rollouts/cmd/completion/completion.go, pkg/kubectl-argo-rollouts/cmd/completion/completion_test.go
=> feat: provide shell completion. Closes #619

pkg/kubectl-argo-rollouts/cmd/promote/promote.go, pkg/kubectl-argo-rollouts/cmd/promote/promote_test.go
Relates to https://github.com/argoproj/argo-rollouts/issues/1487
- Fix promote nil pointer error where there are no steps
- Add test to validate nil pointer bug on promoting canary with no steps
Checklist:
=> fix: Nil pointer error while promoting canary with no steps. Fixes #1487

docs/features/notifications.md, utils/record/record.go
- template and trigger should be included in the argo-rollouts-notification-configmap
- add debug message for missing notification message
Checklist:
=> docs: clarify the service in notificatioin.md

docs/features/traffic-management/alb.md
Signed-off-by: Noam Gal <noam.gal@codefresh.io>
Checklist:
* [ x My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).
=> fix(docs): minor mis-type fix, and formatting

USERS.md, rollout/experiment.go, rollout/experiment_test.go
Fixes #1596 
When re-creating an experiment, which has labels defined, from an already on-going canary, the `GetExperimentFromTemplate` is changing the experiment `specRef` replica set `template labels leading to errors:
```yaml
time="2021-10-19T07:49:57Z" level=error msg="roCtx.reconcile err ReplicaSet.apps \"infrastructure-kubernetes-asfvalidator-74f9778454\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/instance\":\"infrastructure-kubernetes-asfvalidator-zerotraffic\", \"app.kubernetes.io/name\":\"asfvalidator-zerotraffic\", \"rollouts-pod-template-hash\":\"74f9778454\"}: `selector` does not match template `labels`" generation=31 namespace=infrastructure-kubernetes resourceVersion=253727 rollout=infrastructure-kubernetes-asfvalidator …
```
=> fix: rollout experiment template changing reference rs template labels. Fixes #1596

analysis/controller_test.go, cmd/rollouts-controller/main.go, controller/controller.go, controller/controller_test.go, controller/healthz.go, controller/healthz_test.go, controller/metrics/analysis_test.go, controller/metrics/client_test.go, controller/metrics/experiment_test.go, controller/metrics/metrics.go, controller/metrics/metrics_test.go, controller/metrics/rollout_test.go, experiments/controller_test.go, ingress/ingress_test.go, manifests/base/argo-rollouts-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml, rollout/controller_test.go, service/service_test.go, utils/controller/controller_test.go
- distinguish between exposed healthz port and metrics port
- liveness probe uses healthz port
readiness probe uses metrics port
In HA mode, only the primary instance is ready to accept request
and the metrics queries
close #1522 
Checklist:
=> feat: add healthz probe port and update the install.yaml

controller/controller_test.go, pkg/kubectl-argo-rollouts/cmd/status/status.go, pkg/kubectl-argo-rollouts/cmd/status/status_test.go
=> fix: inconsistent status command output

pkg/apis/rollouts/validation/validation_references.go, pkg/apis/rollouts/validation/validation_references_test.go, test/e2e/analysis_test.go, test/e2e/bluegreen_test.go, test/e2e/functional_test.go
=> fix: validate service selctor labels matching rollout template labels

Makefile, test/e2e/analysis_test.go
This is an attempt to fix the E2E failures by increasing the parallelism from **1 -> 4** and increasing the timeout from **20m -> 30m** as we now have a lot of tests.
---
**Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>**
=> fix(e2e): DeFlake E2E Tests #1647

rollout/trafficrouting/nginx/nginx.go, rollout/trafficrouting/nginx/nginx_test.go
Fix https://github.com/argoproj/argo-rollouts/issues/1651
Checklist:
=> fix: nginx traffic router patching wrong ingress resource

docs/features/controller-metrics.md
This PR removes the non-existent metrics from the documentation.
---
**Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>**
=> fix(docs): Remove Non-Existent Metrics From Docs

rollout/trafficrouting.go
=> fix: Promote-full with TrafficRouting waits for all canary pods to come up

utils/replicaset/replicaset.go
This PR fixes a NPE which gets thrown while getting the ReplicaSet labels if the RS itself is `null`. See https://github.com/argoproj/argo-rollouts/issues/1630 for more details.
---
Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>
=> fix: Fixed NPE while getting the ReplicaSet labels

rollout/bluegreen_test.go, rollout/controller_test.go, rollout/restart.go, rollout/sync.go, test/e2e/functional_test.go, utils/conditions/conditions.go
- if the progress condition is not reset, the timeout check
returns true for a healthy rollout
fix: #1624 
Checklist:
=> fix: reset the progress condition when a pod is restarted

controller/metrics/metrics.go, controller/metrics/metrics_test.go, controller/metrics/prommetrics.go
Signed-off-by: Siddharth Maloo <smaloo@salesforce.com>
Checklist:
=> feat: added Argo version info in /metrics endpoint

server/server.go
Fixes https://github.com/argoproj/argo-rollouts/issues/1539
Checklist:
=> fix: sending updates to dashboard when a pod terminates

docs/features/analysis.md
=> docs(analysis): add missing explanation about failureLimit

Makefile, cmd/rollouts-controller/main.go, test/fixtures/e2e_suite.go, utils/defaults/defaults.go
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
=> feat: increase default QPS/Burst to 40/80. Allow values to be tunable

go.mod, go.sum
=> chore: pin sys module in go.mod to resolve a fatal runtime execution in go 1.17

rollout/controller.go
Resolves https://github.com/argoproj/argo-rollouts/issues/913
I finally encountered the e2e flakiness https://github.com/argoproj/argo-rollouts/issues/913 in local development and spent some time studying the sequence of events and logs. I believe the root cause to be a bug in the controller with the informer cache becoming stale, because we don't write back the rollout in the event where `spec.replicas` is defaulted. 
Update: this will only fix one source of e2e flakiness, but there is much more to be done
=> fix: missing rollout informer writeback

rollout/experiment_test.go
PR fixes flackiness in TestAbortRolloutAfterFailedExperiment introduced by https://github.com/argoproj/argo-rollouts/pull/1654
```
go test -run TestAbortRolloutAfterFailedExperiment github.com/argoproj/argo-rollouts/rollout  -count 100
ok  	github.com/argoproj/argo-rollouts/rollout	21.187s
```
=> chore: fix flaky TestAbortRolloutAfterFailedExperiment test

docs/features/analysis.md, experiments/experiment.go, manifests/crds/experiment-crd.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apiclient/rollout/rollout.swagger.json, pkg/apis/api-rules/violation_exceptions.list, pkg/apis/rollouts/v1alpha1/analysis_types.go, pkg/apis/rollouts/v1alpha1/experiment_types.go, pkg/apis/rollouts/v1alpha1/types.go, pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go, test/e2e/analysis_test.go, test/e2e/experiment_test.go, test/e2e/functional/experiment-dry-run-analysis.yaml, test/fixtures/then.go, utils/analysis/helpers.go, utils/analysis/helpers_test.go
Thins PR extends the `dryRun` functionality to the experiments.
https://argoproj.github.io/argo-rollouts/features/analysis/#dry-run-mode
---
**Signed-off-by:** Rohit Agrawal <rohit.agrawal@databricks.com>
=> feat(experiment): Added DryRun analysis mode functionality for experiments

docs/features/analysis.md
=> docs: fix some vague description about analysis arguments

docs/features/notifications.md, experiments/experiment_test.go, go.mod, go.sum, mkdocs.yml, utils/record/record.go
Fixes: #1668 
Checklist:
* [ X ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ X ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ X ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ X ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ X ] My builds are green. Try syncing with master if they are not. 
* [ X ] My organization is added …
=> fix: Enable default triggers for argo rollouts

ui/src/app/components/rollout-actions/rollout-actions.tsx
- keep promote and abort buttons enabled while deploying
- disable them at all other times
- also, only enable retry button when Rollout is degraded
Fixes https://github.com/argoproj/argo-rollouts/issues/1581
Signed-off-by: Ben Poland <ben.poland@faire.com>
Checklist:
=> fix: dashboard promote buttons disabled during deploy

.github/workflows/release.yaml, Dockerfile, Makefile, hack/build-release-plugins.sh
Checklist:
The `quay.io/argoproj/kubectl-argo-rollouts` can now run on arm64 :D.
Closes #1728, which contains all the important details about this.
Wrote a quick demo using the new docker image which I pushed to my own Quay account for testing. We can see in the screenshot that the new Docker image runs smoothly on arm64 and the old one does not.
=> fix(plugin): Fixes arm64 compatibility to plugin docker image. Fixes #1728

docs/getting-started/setup/index.md
Minikube changed the destination namespace for the ingress addon.
=> chore: update docs for minikube 1.19

docs/features/analysis.md
This removes a duplicate sentence in dry-run docs
Checklist:
=> docs: Remove duplicate sentence 

rollout/trafficrouting.go, rollout/trafficrouting_test.go
Fix: https://github.com/argoproj/argo-rollouts/issues/1718
Checklist:
=> fix: traffic routed canary would flap traffic to stable after last step

docs/features/canary.md
=> docs: clarify the setCanaryScale of Dynamic Canary Scale

manifests/notifications-install.yaml, manifests/notifications/kustomization.yaml, manifests/notifications/on-analysis-run-error.yaml, manifests/notifications/on-analysis-run-failed.yaml, manifests/notifications/on-analysis-run-running.yaml, manifests/notifications/on-rollout-aborted.yaml, manifests/notifications/on-rollout-paused.yaml
Fixes: https://github.com/argoproj/argo-rollouts/issues/1694
Checklist:
=> docs: Add notiication templates for rollouts and analysis

rollout/analysis_test.go, rollout/experiment_test.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
This change fixes the issue where the basic canary calculation would possibly round up the canary/stable counts and could exceed `maxSurge: 0`. The issue made it not possible to use rollouts for use cases where the replicas needed to be capped to a fixed size, such as a kafka consumer.
As part of the change, we will now choose between stable/canary replica counts summing up to `spec.replicas` or `spec.replicas + 1` depending on:
* which can give us a better approximation of the desired canary weight
* which will not violate maxSurge
Prior to this fix, we would end up always rounding up to `spec.replicas + 1` unless the desired weight was evenly divisible to 100.
For a deeper understanding of the improvements, see the TestApproximateWeightedNewStableReplicaCounts table test for examples of …
=> fix!: improve basic canary approximation accuracy and honor maxSurge

docs/features/analysis.md
Fixes comment https://github.com/argoproj/argo-rollouts/pull/1629#discussion_r773489730 
Checklist:
=> docs: fix doc for valueFrom fields for analysis args

experiments/experiment_test.go, experiments/replicaset.go
Conflict errors when scaling Experiment ReplicaSets could cause the Experiment to fail. This should cause it to re-reconcile/retry.
Resolves https://github.com/argoproj/argo-rollouts/issues/1775
=> fix: retry Experiment ReplicaSet scaling conflict errors

rollout/bluegreen.go, rollout/canary.go, rollout/context.go, rollout/service.go, rollout/sync.go
Resolves https://github.com/argoproj/argo-rollouts/issues/1696
The panic in https://github.com/argoproj/argo-rollouts/issues/1696 is caused by an unfrequented executed code path that happens during scaling events. The original code of syncReplicasOnly written 3 years ago was only supposed to adjust replica counts and nothing else. But it somehow evolved to do redundant work.
This change is a refactoring that eliminates the redundant work done in syncReplicasOnly such that it goes back to the original behavior of scaling the ReplicaSets and nothing else, which simplifies our logic.
=> refactor: controller could panic in scaling events with analysis

rollout/canary.go, rollout/canary_test.go, rollout/service.go, rollout/service_test.go, utils/replicaset/replicaset.go, utils/replicaset/replicaset_test.go
This change delays the updating of the stable service selector unless the stable replicaset is ~ready~ available. This helps ensure we don't prematurely point the stable service to nothing in the event we are taking over a Service in the migration case, potentially causing downtime.
Resolves https://github.com/argoproj/argo-rollouts/issues/1731
=> fix: delay service injection of selector labels until ReplicaSet available

manifests/dashboard-install.yaml, manifests/dashboard-install/dashboard-clusterrole.yaml, pkg/kubectl-argo-rollouts/cmd/set/set_image.go, pkg/kubectl-argo-rollouts/cmd/set/set_test.go, server/server.go
When running: `kubectl argo rollouts set image` against a Rollout which is using the workloadRef feature, the CLI does not properly set the image on the workload (the Deployment). This change detects if the rollout is referencing a Deployment, then sets the image on the referenced Deployment.
Resolves https://github.com/argoproj/argo-rollouts/issues/1537
=> fix: plugin did not set deployment image when using workloadRef

pkg/kubectl-argo-rollouts/info/info_test.go, pkg/kubectl-argo-rollouts/info/rollout_info.go, pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go, pkg/signals/signal_posix.go, server/server.go
=> fix(ui): Show container images in dashboard for rollouts with a WorkloadRef

rollout/trafficrouting/istio/istio.go
**Signed-off-by:** Rohit Agrawal <rohit.agrawal@databricks.com>
This PR fixes a small error in `reconcileVirtualService(...)` where we try to set the HTTP routes back to the modified VirtualService even if it doesn't exist.
**Checklist:**
=> chore: Fix istio vs reconcile errors

pkg/kubectl-argo-rollouts/cmd/status/status.go, pkg/kubectl-argo-rollouts/cmd/status/status_test.go, pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go
Resolves https://github.com/argoproj/argo-rollouts/issues/1747
Fixes a panic introduced in v1.1.0 plugin which closed a channel prematurely while the sender (view controller) was still sending on it. This change prevents this by deferring the channel close, and also niling out the view controller's callback list when the view controller stops, so that it will not attempt to perform any callbacks when finished.
As part of this fix, I made the plugin less chatty and only showed status changes. Previously, it would print out the phase and message on every rollout change, even if it was the same as before. Example output:
```
$ kubectl-argo-rollouts status my-rollout -w
Progressing - more replicas need to be updated
Paused - CanaryPauseStep
Progressing - more replicas need to be updated …
```
=> fix: plugin panic while watching progress

rollout/trafficrouting.go, rollout/trafficrouting_test.go
On promote-full calculate the weight by (100 * canaryAvailablereplicas) / Replica.
This will make sure we will not have an outage when we do promote full.
fixes: https://github.com/argoproj/argo-rollouts/issues/1681
Signed-off-by: Nissan Hefetz <nissy34@gmail.com>
=> fix: Promote-full with TrafficRouting will dynamically increase weight according to available canary pods. Fixes: #1681

rollout/controller_test.go, rollout/restart.go, rollout/trafficrouting.go, rollout/trafficrouting/smi/smi.go, rollout/trafficrouting_test.go, utils/conditions/conditions.go
Resolves https://github.com/argoproj/argo-rollouts/issues/1665
Resolves https://github.com/argoproj/argo-rollouts/issues/1701
When using dynamicStableScaling, and the rollout was aborted, we would incorrectly increase the weight of the canary if the available stable replicas was flapping. This fix ensures that when we are aborting, we are only ever *decreasing* the weight and never increasing this. 
While testing this fix, I also discovered that a portion of the traffic routing unit tests was not functioning properly because the expected mock functions were not executed properly (Issue https://github.com/argoproj/argo-rollouts/issues/1701)
=> fix: canary replicas/weight could flap during abort with dynamic scaling

.github/dependabot.yml
Dependabot does not currently support a depedency grouping feature so in the
meantime we will have dependabot ignore them.
Signed-off-by: William Van Hevelingen <william.vanhevelingen@acquia.com>
Checklist:
=> chore: Configure dependabot to ignore k8s dependencies

pkg/apiclient/rollout/rollout.swagger.json, pkg/apis/rollouts/v1alpha1/generated.proto, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go, test/e2e/istio_test.go, utils/replicaset/canary.go, utils/rollout/rolloututil.go, utils/rollout/rolloututil_test.go
While debugging e2e flakiness, I determined that **_some_** of the flakiness is actually caused by a bug where the client does not properly detect that the rollout is still in the process of being unpaused. This is probably a rare event but is exacerbated when the client is aggressively monitoring rollout status (such as in e2e tests which are performing watches against the rollout). The scenario is this:
1. rollout becomes automatically paused (e.g. canary pause step). Status becomes:
```yaml
status:
phase: Paused
pauseConditions:
- reason: CanaryPauseStep
controllerPause: true
```
2. client (plugin) unpauses the rollout (by nilling out pauseConditions). Status becomes:
```yaml
status:
phase: Paused
controllerPause: true
```
3. Before the controller has time to update status to …
=> fix: client can detect if rollout is in the process of unpausing

rollout/experiment_test.go
Signed-off-by: hari rongali <hari_rongali@intuit.com>
Checklist:
=> fix: flaky unit test

.github/workflows/release.yaml
Release process failed with:
```
INFO[2022-02-05T02:33:23Z] Plugin yarn generated output at /tmp/bom-yarn.spdx 
level=info msg="Generating SPDX Bill of Materials"
level=info msg="Processing image reference: quay.io/argoproj/argo-rollouts:vv1.2.0-rc1"
level=fatal msg="generating doc: creating SPDX document: generating SPDX package from image ref quay.io/argoproj/argo-rollouts:vv1.2.0-rc1: while downloading images to archive: fetching remote descriptor: GET https://quay.io/v2/argoproj/argo-rollouts/manifests/vv1.2.0-rc1: MANIFEST_UNKNOWN: manifest unknown; map[]"
Error: Process completed with exit code 1.
```
=> chore: fix spdx ci

server/server.go
After upgrading grpc to 1.42.0 any REST API is failing with `stream terminated by RST_STREAM with error code: PROTOCOL_ERROR` error due to https://github.com/grpc-ecosystem/grpc-gateway/issues/2447. The PR implement a workaround for this issue
=> fix: add workaround to fix 'stream terminated by RST_STREAM with error code: PROTOCOL_ERROR'

README.md
Adding community section to README similar to argo-cd repository to help users discover communication channels.
=> docs: add community section to README.md

ui/package.json
Moving some dependencies to devDependencies, because they're causing false-positives for vulnerabilities in Snyk.
=> chore: move dependencies to dev dependencies

Dockerfile
Latest 1.45 version causes this failure in CI (I think due to multi-arch build on arm64):
```
#22 0.471 golangci/golangci-lint info checking GitHub for tag 'v1.45.0'
#22 0.834 golangci/golangci-lint info found version: 1.45.0 for v1.45.0/linux/arm64
#22 2.684 golangci/golangci-lint info installed /go/bin/golangci-lint
#22 14.16 panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
#22 14.16
#22 14.16 goroutine 1 [running]:
#22 14.16 github.com/go-critic/go-critic/checkers.init.22()
#22 14.16       github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x488
```
=> chore: fix golangci-lint to 1.44 to fix build error

server/server.go, ui/src/app/components/rollout/rollout.scss, ui/src/app/components/rollout/rollout.tsx
=> feature: Dashboard displaying the setCanaryScale values

pkg/kubectl-argo-rollouts/info/info_test.go, pkg/kubectl-argo-rollouts/info/rollout_info.go, pkg/kubectl-argo-rollouts/info/testdata/canary/canary-rollout5.yaml, pkg/kubectl-argo-rollouts/info/testdata/canary/canary-rollout6.yaml
This fixes #1812 by pulling the actual weight from the status field instead
of the SetWeight.
=> fix: Use actual weight from status field on rollout object

.github/workflows/docker-publish.yml, Dockerfile
Disabled cache, it is configured to only cache the export layers that are in the final build stages.  Not taking advantage of the cache on disk for the second run of the `kubectl-argo-rollouts` image  This will reduce build times by **half**.  I recommend a second PR to cleanup the existing cache steps from the docker-publish.yml as they are not needed anymore.
I have tested these builds locally.  I'm expecting the complete Workflow should be complete in approximately 20-25 minutes on GitHub runners.
The flowchart below shows how the Dockerfile is processed using cross-compilation. Orange nodes are x86_64 and opaque orange nodes are arm64.
```mermaid
flowchart TB
id1([builder]) --> id2([argo-rollouts-ui]) --> …
```
=> chore: Improve image build speed

.github/workflows/go.yml
We ran into this same issue with argo cd the fix is found [here](https://github.com/argoproj/argo-cd/pull/8988) for ArgoCD
=> fix: build/lint is broken due to dependencies changes

manifests/install.yaml, manifests/namespace-install.yaml, manifests/role/argo-rollouts-clusterrole.yaml
Need pod watch argo rollouts get rollouts
Fixes https://github.com/argoproj/argo-rollouts/issues/1960
Checklist:
=> fix(RBAC): Add watch verb to clusterRole for pods. Fixes #1960

.github/workflows/docker-publish.yml, .github/workflows/release.yaml, Dockerfile, Makefile, hack/build-release-plugins.sh
This is a follow-up to PR#1919.  Cache created from the `controller-image` should be used to build the `plugin-image`.  Buildx uses Buildkit under the hood and uses "Automatic garbage collection" which has a [default policy of 10% of free disk space](https://github.com/moby/moby/blob/master/builder/builder-next/worker/gc_unix.go).  Disabling the garbage collection ensures that the cache is temporarily stored for the duration of the runner.  
I also made a small change to the Dockerfile to provide support for older versions of Docker and Podman which do not support multiple args on a single line.
Checklist:
=> chore: Improve image build speed #1919

docs/features/specification.md, pkg/apiclient/rollout/rollout.swagger.json, pkg/apis/rollouts/v1alpha1/generated.proto, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go
Clarification for the progressDeadlineAbort parameter documentation.
=> chore(doc): Clarify doc for Rollout.spec.progressDeadlineAbort

go.mod, utils/aws/aws.go, utils/defaults/defaults.go
This adds pagination to the FindLoadBalancerByDNSName function this
should allow argo rollouts to work with any number of loadbalancers.
closes issue #1963
=> fix: Add pagination to FindLoadBalancerByDNSName

Makefile, test/e2e/functional_test.go, test/fixtures/e2e_suite.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go
This PR changes the behavior such that we now do not check the stable replicate sets pod availability during a rollout and instead just insure the the replica set has the correct number of replica pods set which would put them in the created or creating state. Fixes issue #995
This implements the logic found in this [comment](https://github.com/argoproj/argo-rollouts/issues/995#issuecomment-1083602885) . 
NOTES: on e2e changes
The changes for the timing config for e2e test has greatly improved the flakey nature of the e2e test both on github runners and while running locally. At 60 seconds I was never really able to reliably get e2e tests to run with the default of 60 seconds. I think to help with onboarding and have good defaults bumping to to 90 seconds makes sense.
I also did some …
=> fix: Change behavior of rollout to not check for availability during rollout and fix flakey e2e tests

docs/features/specification.md
Closes #2018 
Adds WorkloadRef to Rollout spec documentation. While this closes the issue above, another issue should be opened to see if the Rollout spec docs are fully up to date.
Checklist:
=> docs: add WorkloadRef to Rollout spec

rollout/trafficrouting/alb/alb.go, utils/conditions/conditions.go
Turn a missing load balancer log line into a proper event
=> fix: missing lb event

analysis/analysis_test.go, utils/analysis/helpers.go, utils/analysis/helpers_test.go
Metrics running in the Dry-Run mode shouldn't impact the terminal decision even if they error out or fail but currently we ignore the metric state which results in the analysis run being terminated earlier in case there are any Dry-Run failures.
Expected behavior is to take into account the status of the metric i.e. Dry-Run or Wet-Run while making the terminal decision inside `IsTerminating(...)`.
=> fix(analysis): Fix Analysis Terminal Decision For Dry-Run Metrics

rollout/controller.go
=> fix: Failed to process: Object 'Kind' is missing in Errors with rollouts notification

analysis/analysis.go
A small fix to only include the most recent error message for the dry-run metric failures. If we don't do this and there are other wet-metrics in progress then the error message keeps getting appended infinitely. 
---
Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>
=> fix(analysis): Avoid Infinite Error Message Append For Failed Dry-Run Metrics

pkg/apis/rollouts/v1alpha1/types.go, rollout/analysis_test.go, rollout/bluegreen_test.go, rollout/canary_test.go, rollout/controller_test.go, rollout/experiment_test.go, rollout/service_test.go, rollout/sync.go, rollout/trafficrouting_test.go, test/e2e/functional_test.go, utils/conditions/conditions.go, utils/conditions/rollouts_test.go
=> fix: change completed condition so it only triggers on pod hash changes also adds an event for when it  does changes.

docs/features/traffic-management/alb.md, docs/features/traffic-management/nginx.md, ingress/ingress.go, ingress/ingress_test.go, utils/ingress/wrapper.go, utils/ingress/wrapper_test.go
This change adds support for `spec.ingressClassName` while still supporting `kubernetes.io/ingress.class` annotation for backwards compatibility.
Fixes #1277
Signed-off-by: Siavash Safi <git@hosted.run>
Checklist:
=> fix(ingress): Add support for spec.ingressClassName. Fixes #1277

docs/features/kustomize.md, test/kustomize/rollout/kustomization.yaml
=> docs: Update docs for new openapi kustomize support

utils/record/record.go, utils/record/record_test.go
=> fix: enable notifications without when condition

docs/releasing.md
=> docs: Update release docs for versioned formula

analysis/analysis.go, analysis/analysis_test.go
This PR fixes the issue defined in https://github.com/argoproj/argo-rollouts/issues/2151 where `AnalysisRun` doesn't transition to `Successful` from `Running` when only Dry-Run metrics are defined and being evaluated. As per the current logic, we don't set the decision while evaluating the Dry-Run metrics but the proper fix is to set it to `Successful` at least if nothing is set.
=> fix(analysis): Make AnalysisRun end when only Dry-Run metrics are defined. Fixes: #2151

cmd/rollouts-controller/main.go, controller/controller.go
=> chore imports: remove repeated package and reformat imports

.github/workflows/release.yaml, Makefile, hack/build-release-plugins.sh
=> chore(cli): add darwin arm64 to build and release

pkg/kubectl-argo-rollouts/cmd/lint/lint.go, pkg/kubectl-argo-rollouts/cmd/lint/lint_test.go, pkg/kubectl-argo-rollouts/cmd/lint/testdata/valid-nginx-basic-canary.yml
=> fix: nil pointer while linting with basic canary and ingresses

docs/requirements.txt
[Read the docs rendering](https://argo-rollouts.readthedocs.io/en/latest/) as well as the drop-down version menu are broken because of https://github.com/readthedocs/readthedocs.org/issues/9064 and https://github.com/mkdocs/mkdocs/issues/2799
I fixed the issue by pinning the same versions mentioned in the [argocd github repo](https://github.com/argoproj/argo-cd/blob/master/docs/requirements.txt)
Checklist:
=> docs: Fixed read-the-docs rendering

rollout/controller_test.go
TestWriteBackToInformer test is a bit flaky add some extra checks to not panic and gain extra info
=> test(controller): add extra checks to TestWriteBackToInformer

OWNERS
=> Move zachaller to approvers

.github/pull_request_template.md
=> ci: add link to conventional pr check in pr template

Makefile
This will allow the argo rollouts repo to live outside the  GOPATH directory.
=> build: copy proto files from GOPATH so we can clone outside of GOPATH

.github/workflows/docker-publish.yml, .github/workflows/release.yaml
Closes #2330 
This PR implements container images and ```argo-rollouts-checksums.txt``` to be signed using ```sigstore/cosign```  
TLDR: https://docs.sigstore.dev/cosign/git_support
1. [Install Cosign](https://docs.sigstore.dev/cosign/installation) on your workstation. Linux, Homebrew, and container options are available.  Execute the command ```cosign --version``` to verified it has been installed correctly.
2. Create or have a valid GitHub PAT token available.
3. Export your PAT as the environment variable "GITHUB_TOKEN"
4. Execute ```cosign generate-key-pair github://argoproj/argo-rollouts``` This will start the process of creating the GitHub Secrets automatically for you, and prompt you to enter a password.  This Password …
=> chore: sign container images and checksum assets

docs/installation.md
Solves https://github.com/argoproj/argo-rollouts/issues/1939
Checklist:
=> docs: mention supported versions

Makefile
We currently assume that GOPATH is set within the developers environment go has some defaults that get used when no GOPATH is defined. If we use `go env GOPATH` to set the env var for the Makefile we will then also fall back to golang defaults which help contributior experiance.
Checklist:
=> build: set GOPATH in Makefile

pkg/kubectl-argo-rollouts/cmd/dashboard/dashboard.go
=> feat(cli): add port flag for dashboard command. Fixes #2382

examples/istio/istio-subset-split.yaml
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>
Checklist:
While trying out istio with rollouts, I could not find any examples for `istio-subset-split`. However, there is an example for `istio-mirroring`. 
This example would help someone who is starting with  `istio` as traffic manager for `argo-rollouts`.
=> chore: Add example for istio-subset-split

server/server.go, server/server_static.go, server/server_static_test.go, server/static_test/index.html, server/static_test/test-dir/test.css
I did refactor the code for static file serving into its own file.
Overall, I also did simplify the code and fixed former issues (see below).
Golang's mime package comes to the rescue when determining the correct mime type.
- add: tests for static files serving
- fix: when request /index.html, the base path was not modified
- fix: wrong 'err' variable used when log.Errorf("Failed to stat file or dir %s: %v"...) was printed
relates to #2290
PS: I would like to participate the hacktoberfest and would appreciated the 'hacktoberfest-accepted' label, IF you're OK with it :)
PPS: any feedback is welcome.
=> fix(dashboard): correct mime type is returned. Fixes: #2290

examples/notifications/rollout-canary.yaml, examples/traffic-routing-experiment-step/rollout-alb-experiment-step.yaml, examples/traffic-routing-experiment-step/rollout-smi-experiment-step.yaml
Closes https://github.com/argoproj/argo-rollouts/issues/2350
Checklist:
=> docs: update examples to remove deprecated APIs in k8s 1.25

.github/workflows/e2e-test-results.yml, .github/workflows/go.yml
superseeds #1973 and #2251
Checklist:
=> ci: fix some github actions warnings

Makefile
```
The -i flag installs the packages that are dependencies of the target.
The -i flag is deprecated. Compiled packages are cached automatically.
```
Checklist:
=> build: remove deprecated -i for go build

manifests/dashboard-install.yaml, manifests/dashboard-install/dashboard-clusterrole.yaml
Dashboard fails with ```failed restoring revision 21: deployments.apps "ourapp" is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts-dashboard" cannot patch resource "deployments" in API group "apps" in the namespace "ournamespace"``` when trying to rollback `Rollout` defined using existing `Deployment` and `workloadRef` config. Adding `patch` verb for `deployments` should fix it.
Checklist:
=> fix: add patch verb to deployment resource

docs/getting-started/ambassador/index.md
I went through an Ambassador Edge Stack upgrade a few months ago, going from 1.x to 3.x. Got stuck for quite awhile because the ambassador-api-version flag indicated wasn't valid. @zachaller identified that it is the `x.` part that is no longer valid so this removes that text.
Checklist:
=> docs: fix ambassador-api-version flag

docs/installation.md
Mentioning upgrade process because people are asking about this all the time (example https://github.com/argoproj/argo-rollouts/discussions/2308)
Checklist:
=> docs: Explain upgrade process

docs/features/specification.md
Fix wrong syntax of
spec.strategy.canary.steps[setMirrorRoute].match.path.regex and spec.strategy.canary.steps[setMirrorRoute].match.path.prefix
Checklist:
=> docs: correct syntax of canary setMirrorRoute's value

Makefile
noticed today that my `DEV_IMAGE=true make image` was building for production.
Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>
Checklist:
=> fix: dev build can set DEV_IMAGE=true

docs/features/traffic-management/alb.md, examples/helm-blue-green/README.md
fixing docs typo in Helm Argo Rollouts. `Instal` -> `Install`
Checklist:
=> docs: fix typo in helm Argo rollouts

.github/workflows/stale-issues-pr.yml, .github/workflows/waiting-issues.yml
This change is required becuase we are not fully updating all our issues/PR's becuase we are so far behind since turning on this workflow.
Docs on change param:
https://github.com/actions/stale#operations-per-run
=> ci: bump api limit on pr/issue action

USERS.md
yotpo is also using ArgoRollous!
Checklist:
=> chore: Add Yotpo to USERS.md

.github/workflows/release.yaml
=> chore: use docker login to sign images

.github/workflows/release.yaml, docs/releasing.md
=> chore: update stable tag conditionally

USERS.md
Adding our company to the list of users using Argo Rollouts
Signed-off-by: Balaji Siva <balaji@opsmx.com>
Checklist:
=> chore: add opsmx to users

.github/ISSUE_TEMPLATE/config.yml, README.md, docs/FAQ.md, docs/releasing.md, mkdocs.yml, ui/src/app/components/header/header.tsx, ui/src/app/components/rollouts-list/rollouts-list.tsx
=> docs: update docs links to all point to readthedocs

go.mod, go.sum
Dependabot upgrade a dependency that broke our unit tests and possibly features. I submitted an issue [here](https://github.com/antonmedv/expr/issues/310) but also am going to look into why the failing test did not stop the automerge of dependabot.
Here is the automerged PR https://github.com/argoproj/argo-rollouts/pull/2527
=> chore: fix dependabot broken dependency with expr lib

.github/workflows/docker-publish.yml, .github/workflows/release.yaml
The newer [BuildKit v0.11](https://www.docker.com/blog/highlights-buildkit-v0-11-release/) now enables a provenance attestation by default. These attestations are stored as a manifest object of `unknown on unknown` attached to the root image index object.  `"To prevent container runtimes from accidentally pulling or running the image described in the manifest, the platform property of the attestation manifest will be set to unknown/unknown"`  This prevents our current Sbom generation from working properly.  
This PR is a workaround by disabling attestations and sboms by default. These new inputs for the `docker build and push action` require the newer version of build and push.
Note:  I have tested this workaround  locally.
=> chore: disable docker sbom and attestations

docs/best-practices.md
Signed-off-by: William Van Hevelingen <william.vanhevelingen@acquia.com>
Checklist:
=> docs: Add best practice for reducing memory usage

docs/getting-started.md, mkdocs.yml
Signed-off-by: Jiacheng Xu <xjcmaxwellcjx@gmail.com>
Fixes: #2511
- Getting started menu:
- Links at the bottom of the getting started page:
Checklist:
=> docs: fix missing links for getting started documentation Fixes #2511

hack/gen-crd-spec/main.go, hack/gen-docs/main.go, metricproviders/datadog/datadog.go, metricproviders/graphite/api.go, metricproviders/influxdb/influxdb_test.go, metricproviders/kayenta/kayenta.go, metricproviders/kayenta/kayenta_test.go, metricproviders/webmetric/webmetric.go, pkg/kubectl-argo-rollouts/cmd/create/create.go, pkg/kubectl-argo-rollouts/cmd/create/create_test.go, pkg/kubectl-argo-rollouts/cmd/lint/lint.go, pkg/kubectl-argo-rollouts/info/testdata/testdata.go, test/fixtures/common.go, test/util/util.go, utils/defaults/defaults.go
Signed-off-by: fengshunli <1171313930@qq.com>
Checklist:
=> fix: remove outdated ioutil package dependencies

pkg/apis/rollouts/v1alpha1/types.go
fixes: https://github.com/argoproj/argo-rollouts/issues/2568
=> chore: fix typo for json tag on rollbackWindow

Dockerfile, ui/package.json
This PR fixes the build pipeline again because of changes in github runners that upgrade node to version 18 https://github.com/actions/runner-images/issues/7002 this caused 
isses with hash generation functions that were depricated.
This turns on the legacy hash until I can spend time debugging front end deps.
Created an issue to track fixing this all properly https://github.com/argoproj/argo-rollouts/issues/2609
This was the error from pipeline
```
$ rm -rf dist && webpack --config ./src/app/webpack.prod.js
/home/runner/work/argo-rollouts/argo-rollouts/ui/node_modules/loader-runner/lib/LoaderRunner.js:133
if(isError) throw e;
^
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
at …
```
=> chore: bump node version and set openssl-legacy-provider

rollout/controller_test.go
This fixes the flakey unit test  `TestWriteBackToInformer` I was able to easily reproduce the flake buy putting the test into a loop, when I switched out the code to use json marshaling it 3000 iterations passed.
This is possibly somewhat a hack solution for how we are using the fake client with informers. There could also be a bug upstream in k8s fake client.
=> fix: flakey TestWriteBackToInformer test

docs/features/experiment.md, rollout/experiment.go, rollout/experiment_test.go
closes: #2622 
possible fix for: https://github.com/argoproj/argo-rollouts/issues/2608
This rolls back the change introduced in #2397 which allows experiments with no weights to still create services. We want it so that services won't be created if there is no weight set for the experiments.
Checklist:
=> fix: Rollback change on service creation with weightless experiments

.github/workflows/e2e.yaml, test/e2e/crds/istio.yaml, test/e2e/crds/split.yaml
run e2e tests on more current k8s versions, going forward 4 will be the most we support and will start dropping older versions. 
I also updated the crd's from their upstreams for e2e tests.
I also fixed a bug with the tmate logic on manual runs, an empty string passes as true on actions and so we would always fall into debug mode.
=> chore: update e2e k8s versions

README.md, docs/features/traffic-management/apisix.md, examples/apisix/rollout.yaml, pkg/apis/rollouts/validation/validation.go, rollout/trafficrouting/apisix/apisix.go, rollout/trafficrouting/apisix/apisix_test.go, rollout/trafficrouting/apisix/mocks/apisix.go, test/e2e/apisix/rollout-apisix-canary-set-header.yaml, test/e2e/apisix_test.go, test/fixtures/common.go
Fixes https://github.com/argoproj/argo-rollouts/issues/2668
Integrate Apache APISIX Ingress Controller and argo-rollouts using APISIX's CRD
Signed-off-by: shareinto [56471924jing@gmail.com](mailto:56471924jing@gmail.com)
Checklist:
=> feat: Apache APISIX SetHeader support. Fixes #2668

.github/ISSUE_TEMPLATE/bug_report.md, examples/analysis-templates.yaml, examples/cluster-analysis-templates.yaml
docs(example): moved other count up next to interval for visibility
fixes: #2691
Checklist:
* [ n/a ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ n/a ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).
=> docs(example): interval requires count

docs/CONTRIBUTING.md
Closes #1750 
Also documents some cluster setup steps under running e2e test section and updates kubectl install link.
=> docs: update contributions.md to include k3d as recommended cluster, add details on e2e test setup, and update kubectl install link. Fixes #1750

mkdocs.yml
=> docs: fix link to plugins for traffic routers

analysis/analysis.go, analysis/controller_test.go
The logic for error handling of anaysisruns was incorrect, we returned an error from a go routine that did not get used at all. This cause errors to not get bubbled up into the status field of the AR resource. This changes the logic around a bit to make sure we bubble up the error to the AR object as well as log it.
fixes: #2696
=> fix: change logic of analysis run to better handle errors

rollout/controller.go
fixes: #2522
https://github.com/argoproj/argo-rollouts/issues/2522#issuecomment-1492181154
=> fix(controller): Fix for rollouts getting stuck in loop

metricproviders/graphite/api.go, metricproviders/graphite/api_test.go
If metric query contains surrounding whitespace, then it's not trimmed and Graphite host returns `400 Bad Request`
Simplest example of analysis template:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
name: error-rate
namespace: argo-rollouts
spec:
metrics:
- name: error-rate
failureLimit: 1
successCondition: 'len(result) > 0 and result[len(result)-1] < asFloat(10)'
provider:
graphite:
address: https://some-graphite-host.com
query: |
from=-2&target=sumSeries(app.http.*.*.count)
```
When this is parsed from YAML, this query contains a newline in the end, so when it's "trimmed", it still contains a trailing space, so when put into the query, it becomes:
```
format=json&from=-2min&target=sumSeries%28app.http.%2A.%2A.count%29+
```
This leads to `400 Bad …
=> fix(analysis): Graphite query - remove whitespaces

metricproviders/datadog/datadog.go, metricproviders/datadog/datadogV2_test.go
this is more inline with the docs at: https://docs.datadoghq.com/api/latest/metrics/?code-lang=curl#query-timeseries-data-across-multiple-products
fixes: #2771 
Checklist:
=> fix: properly wrap Datadog API v2 request body (#2771)

.github/workflows/docker-publish.yml, .github/workflows/image-reuse.yaml
This PR implements using keyless signing for cosign.  It uses a reusable workflow (image-reuse.yaml) that will also be used in the `release` workflow to generate attestations. 
Changes in `docker-publish` workflow:
1. Concurrency added to reduce the amount of executors used on multiple pushes.
2. Only the `latest` tag will be used, `master` tag has been removed on a push events of the `master` branch.
3. `image-reuse.yaml` is the exact same reusable workflow we are using in Argo CD.
Successful testing of generating attestations for Argo Rollouts has been completed and will come in a separate PR along with all the documentation.
https://github.com/34fathombelow/rollouts-testing/actions/runs/4989497845
https://github.com/34fathombelow/rollouts-testing/releases/tag/v2.0.0-rc3
=> ci: use keyless signing for main and release branches

docs/CONTRIBUTING.md
This is a minor docs improvement.
Checklist:
* [n/a] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [n/a] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).
=> docs: Add some details around running locally to make things clearer new contributors

docs/features/traffic-management/plugins.md
The format for the plugin names shouldn't just be what the git repo name is, it should be the plugin name so I updated that as well.
Checklist:
* [c] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [b] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [y] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [n] I …
=> docs: Add gateway API link, fix Contour plugin naming

rollout/pause_test.go
1. The `TestHasAddPause` checks the behavior of the `HasAddPause()` function in the pauseContext struct. It creates a `pauseContext` instance with an empty v1alpha1.RolloutStatus and an empty list of pause conditions. It sets one `addPauseReason` with the value `v1alpha1.PauseReasonCanaryPauseStep` with an empty list for `removePauseReasons`. The test then calls the function on the `pauseContext` and asserts that the result is true.
2. The test `TestHasAddPauseNoReasons` is basically the unhappy path for the `HasAddPause()` function. It creates a `pauseContext` instance with an empty `v1alpha1.RolloutStatus` and an empty list of pause conditions. It sets both the `addPauseReasons` and `removePauseReasons` lists as empty. The test then calls the function and asserts that the result is …
=> chore: Add tests for pause functionality in rollout package

utils/experiment/experiment.go, utils/plugin/downloader_test.go, utils/replicaset/canary.go, utils/replicaset/canary_test.go, utils/rollout/rolloututil_test.go
=> chore: add unit test

docs/analysis/plugins.md, docs/features/traffic-management/google-cloud.md, docs/features/traffic-management/index.md, docs/features/traffic-management/plugins.md, mkdocs.yml
Closes https://github.com/argoproj/argo-rollouts/issues/1079
Checklist:
=> docs: support for Google Cloud Load balancers

manifests/crds/rollout-crd.yaml, manifests/install.yaml, pkg/apiclient/rollout/rollout.swagger.json, pkg/apis/rollouts/v1alpha1/generated.proto, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go
This field was added as non optional, when a rollout exists with the upper level item included in status new apply's of the resource fail because this status field is missing on them, making it optional fixes this.
This field was introduced in https://github.com/argoproj/argo-rollouts/pull/2604
=> fix: make new alb fullName field  optional for backward compatability

USERS.md, docs/features/specification.md
=> docs: Fix typo in header routing specification docs

mkdocs.yml
Datadog (the company) stopped capitalizing the "d" in "dog" over 13 years ago; the correct capitalization is now "Datadog".
See datadog/documentation#8028 for more context.
---
Checklist:
=> docs: use correct capitalization for "Datadog" in navigation sidebar

docs/getting-started/appmesh/index.md, examples/appmesh/canary-service.yaml
=> docs: Fix AWS App Mesh getting started documentation to avoid connection pooling problems

docs/features/traffic-management/index.md, docs/features/traffic-management/kong.md, mkdocs.yml
Closes https://github.com/argoproj/argo-rollouts/issues/782
Checklist:
=> docs: support for Kong ingress

docs/analysis/datadog.md
=> docs: Update datadog.md - clarify formulas #2813

docs/features/specification.md
Add blueGreen activeMetadata / previewMetadata as its part of the spec.
This was added back in https://github.com/argoproj/argo-rollouts/pull/974 , its part of the docs in https://github.com/argoproj/argo-rollouts/blob/master/docs/features/ephemeral-metadata.md but not documented as part of the spec
Checklist:
=> docs: Update docs of Rollout spec to add active/previewMetadata

docs/features/kustomize/rollout_cr_schema.json, pkg/apiclient/rollout/rollout.swagger.json, pkg/apis/rollouts/v1alpha1/generated.proto, pkg/apis/rollouts/v1alpha1/openapi_generated.go, pkg/apis/rollouts/v1alpha1/types.go
add analysis template merge key information
Checklist:
=> feat: add merge key to analysis template

analysis/analysis.go, analysis/analysis_test.go
Make sure we resolve args before creating the provider for garbage collection, this lets providers such as prometheus check that the url is valid if it contains any args.
Checklist:
=> fix: resolve args to metric in garbage collection function

Makefile
add `make help`  command, result:
Checklist:
=> chore: add make help cmd

docs/CONTRIBUTING.md
Classifying this as chore
Checklist:
* [n/a] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).
=> docs(example): Add example on how to execute subset of e2e tests

controller/metrics/client.go
The `name` label in the `controller_clientset_k8s_request_total` metric
produce an excessive amount of cardinality for `events` and `replicasets`.
This can lead to hundreds of thousands of unique metrics over a couple 
weeks in a large deployment. Set the name to "N/A" for these client request 
types.
Checklist:
=> fix(controller): Remove name label from some k8s client metrics

rollout/trafficrouting/istio/istio.go, rollout/trafficrouting/istio/istio_test.go
=> fix: get new httpRoutesI after removeRoute() to avoid duplicates. Fixes #2769

.github/workflows/gh-pages.yaml
Needed because of:
https://github.com/actions/setup-go/issues/326
=> chore: quote golang version string to not use go 1.2.2

metricproviders/cloudwatch/cloudwatch.go, metricproviders/cloudwatch/cloudwatch_test.go
=> fix: cloudwatch metrics provider multiple dimensions

hack/installers/install-dev-tools.sh, test/fixtures/when.go
gotestsum now fails on nil pointers by default which is why this test issue is being fixed here as well
Change order of defer to prevent using closed channel
So deferes are called in a last-in-first-out order this means,
that we would close the channel before canceling the context which could
lead to a nil pointer usage. Let's just manually control order. We will also deregister the callbacks.
=> chore: bump gotestsum and fix flakey test causing nil channel send

docs/installation.md
We have many issues opened regarding the compatible issue of argo-rollouts and k8s. Based on @zachaller comment on this #2718 issue, I think we all agree:
1. the old docs is unclear and not true, argo-rollouts doesn't only support k8s N and N-1 version, sometime it support N-3 version 
2. the code is truth; as long as it's tested, we should be able to say argo-rollouts X version is compatible with k9s Y version
Resolves #2718
Checklist:
=> docs: update supported k8s version

cmd/rollouts-controller/main.go
When reading the code I found this typo in the resource kind. I'm not sure how huge of an impact this bug has yet, as I'm not very familiar with the codebase and project.
Checklist:
* There are no tests I could adjust according to the fix
* I'm doing it personally
=> fix(controller): typo fix ("Secrete" -> "Secret") in secret informer

rollout/trafficrouting/alb/alb.go, rollout/trafficrouting/alb/alb_test.go
=> feat(trafficrouting): use values array for multiple accepted values under same header name

docs/plugins.md, metricproviders/plugin/client/client.go, rollout/trafficrouting/plugin/client/client.go, test/e2e/appmesh_test.go, utils/plugin/plugin.go, utils/plugin/plugin_test.go, utils/plugin/types/types.go
Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)
fix #2991 
Checklist:
=> feat: add command args for plugin

docs/features/kustomize.md, examples/notifications/kustomization.yaml, manifests/namespace-install/kustomization.yaml, manifests/notifications/kustomization.yaml, test/kustomize/rollout/kustomization.yaml
This update ensures documentation and test examples reflect the use
of the newer `patches` method, transitioning away from the deprecated
`patchesStrategicMerge`. This aligns with current best practices and
recommendations from the kustomize project.
Signed-off-by: Daniel Wright <danielwright@bitgo.com>
Closes #3009
Checklist:
=> docs: replace `patchesStrategicMerge` with `patches` in tests/docs

Makefile
This came up when trying to run the codegen. Need the GOPATH env var to be set.
Checklist:
=> fix: Add the GOPATH to the go-to-protobuf command

docs/FAQ.md
=> docs: clarify external clusters

experiments/controller_test.go, experiments/experiment_test.go, experiments/replicaset_test.go, rollout/analysis_test.go, rollout/bluegreen_test.go, rollout/canary_test.go, rollout/controller.go, rollout/controller_test.go, rollout/experiment_test.go, rollout/service_test.go, test/e2e/istio_test.go
Resolves https://github.com/argoproj/argo-rollouts/issues/2982
It was possible that if someone ran `kubectl argo rollouts abort` against a rollout that was fully promoted, it could get the controller into a reconciliation hot loop where it kept adding and removing scale-down-deadline on a replicaset.
This fix will detect if we are both aborted but also fully promoted, and will remove the abort condition. If we are in a fully promoted state, then I do not think it makes sense for a rollout to ever be aborted.
When testing, I reproduced the hot loop, then ran my version of the controller and it prevented the loop.
This PR also improves a bunch of tests to use `assert.JSONEq` instead of `assert.Equal`, which will produce much better diffs upon errors. e.g.:
```
--- Expected
+++ Actual
@@ …
```
=> fix: prevent hot loop when fully promoted rollout is aborted

metricproviders/kayenta/kayenta.go
Updating `getCanaryConfigId` func:
`Error Handling:` It now handles errors more cleanly.
`Resource Management:` It closes the HTTP response body to prevent resource leaks.
Last but not least it simplifies things by reducing nesting and using the defer statement for cleanup.
Checklist:
=> chore: updating getCanaryConfigId to be more efficient with better error handling

rollout/sync.go
Resolves https://github.com/argoproj/argo-rollouts/issues/2931
During a scaling event, we will now only perform scaling against our ReplicaSets, and only reconcile:
* `status.availableReplicas`
* `status.HPAReplicas`
This fixes a bug where we would lose some information in status (because we did not perform the normal full logic of reconciliation).
Checklist:
=> fix: inopportune scaling events would lose some status fields

controller/controller.go
A bug was introduced with self service notifications that due to the addition of the add to informer events. This created a race condition on controller startup. We would end up populating our notification api map with an empty value because it could not find the configmap because the informer was synced after starting up of the rollout informer which called defaultEventf function to create the add to informer events.
This PR changes the order that informers are started and waits for the notification informers to sync before starting other informers.
Checklist:
=> fix: sync notification controller configmaps/secrets first

utils/record/record.go, utils/record/record_test.go
Notifications would stop processing if any error happened on a single notification 'API' configuration, we should continue processing other notifications so that we do not miss sending a notification that is properly configured.
This also fixes an incorrect prometheus stat, we where only incrementing errors and success counts on api creations not at the sending and erroring of the actually execution of the notification.
=> fix: missing notification on error

docs/features/anti-affinity/anti-affinity.md
**ISSUE DETAILS**
Image is present between the incomplete sentence. To see the issue  go to this link : https://argo-rollouts.readthedocs.io/en/stable/features/anti-affinity/anti-affinity/#enabling-anti-affinity-in-rollouts and check the above image.
Commits:
3c83b2d0ef7398c7f9376480e6f8362eb36c74a5
905af66ffbc576f21767619d12219eea0c5ae808
Checklist:
=> docs: Ensure image not present between incomplete sentence.

CONTRIBUTING.md
Add a root CONTRIBUTING.md that directs to docs/CONTRIBUTING.md
- having a `CONTRIBUTING.md` at the root of the repo is a common convention
- I looked at the root of the repo initially, didn't find it, then checked the website, but potential contributors may think it doesn't exist as a result
Shamelessly copied from https://github.com/argoproj/argo-workflows/pull/10969 (thank you @agilgur5)
Checklist:
=> docs: add CONTRIBUTING.md at root of repo, directing to docs/

docs/analysis/datadog.md
Was pointed out with the docs live from merge https://github.com/argoproj/argo-rollouts/pull/2997, but we're still only at 1.6 this can be confusing for users. 
Added the following: 
Checklist:
=> docs(analysis): Add note about availability of new datadog v2 functionality

.readthedocs.yaml
https://github.com/readthedocs/readthedocs.org/issues/8861#issuecomment-1025568797
=> fix: docs require build.os to be defined

USERS.md, rollout/trafficrouting/istio/istio.go, rollout/trafficrouting/istio/istio_test.go
This reverts commit 04e11195fb4046e897574478c51fb14692a07578.
fixes: https://github.com/argoproj/argo-rollouts/issues/3141
=> fix: Revert "fix: istio destionationrule subsets enforcement (#3126)"

docs/features/traffic-management/smi.md
Before: "Name of service that sends traffic only to the stable po ds"
After: "Name of service that sends traffic only to the stable pods"
Checklist:
=> docs: fix typo in smi.md

rollout/ephemeralmetadata_test.go
=> chore: add test for reconcileEphemeralMetadata()

ui/package.json, ui/yarn.lock
Before this change both version 2.29.1 and version 2.29.4 of momentjs were brougth in. The bump from v2.29.1 -> v2.29.4 remediates two CVEs: CVE-2022-24785 [1] and CVE-2022-31129 [2].
The most notable change comes with the bump from v2.29.1 -> v2.29.2 which introduces a breaking change to remediate CVE-2022-24785: Forward slash and backward slash is no longer allowed in locale names. Locales containing either of those characters will not be loaded from the filesystem any longer [3].
Other than that it looks like there's only patch fixes which can be seen in the full changelog [4].
[1] https://github.com/moment/moment/security/advisories/GHSA-8hfj-j24r-96c4
[2] https://github.com/moment/moment/security/advisories/GHSA-wc69-rhjr-hc9g
[3] …
=> build(deps): always resolve momentjs version 2.29.4

rollout/replicaset.go
We do this in addScaleDownDelay as well this was just missing and so we are writing the same value we pass into the function instead of the updated rs.
=> fix: make sure we use the updated rs when we write back to informer

pkg/apis/rollouts/validation/validation.go, pkg/apis/rollouts/validation/validation_test.go
leave the validation of setHeaderRoute to the plugin when plugins is not empty.
resolving #2899
Checklist:
=> chore: leave the validation of setHeaderRoute to the plugin when plugins is not empty.

docs/analysis/prometheus.md
The existing key "name" results in an error. The expected key is "key" as defined in the struct:
https://github.com/argoproj/argo-rollouts/blob/99ae20c0ffdfd2543856561fd528fcd51b4fb0a5/pkg/apis/rollouts/v1alpha1/analysis_types.go#L567
Checklist:
=> docs: Fixed the key for headers in prometheus based argo analysis

ui/yarn.lock
Checklist:
This PR addresses a CVE for follow-redirects: https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-6141137
It's a transitive dependency only but better to just update it anyway.
=> chore: update follow-redirects to 1.15.5

rollout/sync.go
don't log an empty rs.Name because when we error out we end up getting a defaulted replicaset.
=> fix: log rs name when update fails

manifests/base/argo-rollouts-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml
Checklist:
---
Though there was a constraint to use deployment strategy `Recreate` due to race condition https://github.com/argoproj/argo-rollouts/issues/38, now it seems we don't have to care about deployment strategy as below.
https://cloud-native.slack.com/archives/C01U781DW2E/p1640199673233000
[argo-helm](https://github.com/argoproj/argo-helm) got [the PR](https://github.com/argoproj/argo-helm/pull/2412) that let controller's deployment strategy configurable, so I wonder we can change the default strategy as `RollingUpdate`. 🙋
=> chore: change controller's deploy strategy to RollingUpdate due to leader election

cmd/rollouts-controller/main.go, controller/controller.go, controller/metrics/metrics.go, utils/record/record.go
This PR introduces the ability to run only the AnalysisRun controller, without needing the Rollout and Experiment CRDs to be installed in the cluster. This allows users/projects to adopt Argo Rollouts for the analysis piece alone.
Usage:
```
./rollouts-controller --controller=analysis
```
Checklist:
=> feat: support ability to run only the analysis controller

rollout/canary.go, test/e2e/canary_test.go, test/e2e/functional/rollout-canary-with-pause.yaml
=> fix: stuck rollout when 2nd deployment happens before 1st finishes

experiments/experiment_test.go, rollout/trafficrouting.go, rollout/trafficrouting_test.go
As of now, in canary deployment with weighted experiment, the rollout throws nil pointer exception, when in an experiment step, one template contains weight and the other doesn't. For example: 
Hence handling a nil pointer check and also a UT verification for port name .
Checklist:
=> fix: append weighted destination only when weight is mentioned 

docs/installation.md
The docs currently describe how to enable shell auto completion for the rollouts CLI when run as a standalone binary, but the don't describe how to get auto completion to work when used from `kubectl`.
This PR updates the docs with instructions on how this can be done, based on the information here: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2379-kubectl-plugins#shell-completion-support
This works with `kubectl` version 1.26 and newer.
Checklist:
=> docs: Update shell autocompletion instructions

USERS.md, docs/CONTRIBUTING.md, docs/generated/notification-services/alertmanager.md, docs/generated/notification-services/awssqs.md, docs/generated/notification-services/email.md, docs/generated/notification-services/github.md, docs/generated/notification-services/googlechat.md, docs/generated/notification-services/grafana.md, docs/generated/notification-services/mattermost.md, docs/generated/notification-services/newrelic.md, docs/generated/notification-services/opsgenie.md, docs/generated/notification-services/overview.md, docs/generated/notification-services/pagerduty.md, docs/generated/notification-services/pagerduty_v2.md, docs/generated/notification-services/pushover.md, docs/generated/notification-services/rocketchat.md, docs/generated/notification-services/slack.md, docs/generated/notification-services/teams.md, docs/generated/notification-services/telegram.md, docs/generated/notification-services/webex.md, docs/generated/notification-services/webhook.md, go.mod, go.sum, hack/gen-docs/main.go
Fixes https://github.com/argoproj/argo-rollouts/issues/3049
1. Updates in this latest version https://github.com/argoproj/notifications-engine/commit/7a069766e95476e1074eeed6145085160e2fec63 of `notifications-engine`:
- https://github.com/argoproj/notifications-engine/pull/259
- **SQS**:
- https://github.com/argoproj/notifications-engine/pull/261
- **GitHub**:
- https://github.com/argoproj/notifications-engine/pull/260
- https://github.com/argoproj/notifications-engine/pull/235
- **Slack**:
- https://github.com/argoproj/notifications-engine/pull/242
- **Opsgenie**:
- https://github.com/argoproj/notifications-engine/pull/267
- https://github.com/argoproj/notifications-engine/pull/268
- **Telegram**:
- https://github.com/argoproj/notifications-engine/pull/265
2. Updating `notifications` …
=> chore: Update notifications engine to 7a06976

rollout/trafficrouting/plugin/client/client.go
Update the plugin init error message to include the correct response error
Checklist:
=> fix: include the correct response error in the plugin init error message

docs/migrating.md
the ordered list was 1-2-3-1
fixed the indentation
Checklist:
=> docs: minor readability on migration

rollout/analysis.go, rollout/analysis_test.go
Partially addresses https://github.com/argoproj/argo-rollouts/issues/3441
Checklist:
=> fix(controller): treat spec.canary.analysis.template empty list as spec.canary.analysis not set

docs/features/bluegreen.md
=> docs: typo in BlueGreen

utils/replicaset/canary.go, utils/replicaset/canary_test.go
when we set the max weight as 100000000, and when the replicas set to > 20. then the trafficWeightToReplicas will be a negative value.
and cause the rollout to stuck in the "min" replicas.
Checklist:
=> fix: fix the issue that when max weight is 100000000, and the replicas> 20,  the trafficWeightToReplicas will return negative value.

ui/package.json, ui/src/app/webpack.common.js
Fixes https://github.com/argoproj/argo-rollouts/issues/2609
Checklist:
This is volunteer work to remove obsolete cryptography from all open source projects. See https://github.com/sponsors/xnox for more details.
=> chore: set webpack hashFunction to modern sha256, remove legacy-provider. Fixes #2609

analysis/controller_test.go, experiments/controller_test.go, pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go, pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller_test.go, rollout/canary_test.go, rollout/controller_test.go, rollout/sync_test.go, rollout/trafficrouting/ambassador/ambassador_test.go, rollout/trafficrouting/apisix/apisix_test.go, rollout/trafficrouting/traefik/traefik_test.go, utils/record/record.go, utils/record/record_test.go, utils/time/now.go
Fixes #3478
See parent issue for reproduction steps.
With this set of changes, `go test -race (...)` now passes:
```
go test -race `go list ./... | grep -v ./test/cmd/metrics-plugin-sample`
```
(I also used [this shell script](https://gist.github.com/jgwest/7048a765d398519837f990120cf3fdd0) to run the tests over and over for several hours, to ensure there are not remaining intermittent failures).
- Unsynchronized read/write to 'callbacks' within `pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go`
- Fix: Add mutexes where needed.
- Unsynchronized read/writes to 'rolloutUpdates' within `pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go`:
- Fix: Add mutexes where needed.
- Unsynchronized read/write to 'enqueuedObjects' in various test functions
- Fix: Add mutexes where needed.
- …
=> chore: fix unit test data races (#3478)

controller/metrics/prommetrics.go, rollout/canary_test.go, rollout/service_test.go
Fix the lint errors reported when running `make lint` locally. 
Checklist:
=> chore: fix lint errors reported by golangci-lint

USERS.md, ui/src/app/components/pods/pods.tsx, ui/src/app/components/rollout-grid-widget/rollout-grid-widget.tsx
This commit adds two improvements to the Pods view:
* Show spinner (pending status) while the pod is running but not ready (like ArgoCD UI does)
* Show the `ready` property on the tooltip
The motivation is that having them _green_ is a bit confusing when they are not ready to serve traffic, especially during the step of `setWeight` in a canary.
Some screenshots of the changes:
Checklist:
=> feat(dashboard): improve pods visibility

cmd/rollouts-controller/main.go
We set the logger for klog and the client-go library uses it. This fix sets the formatter for the logger so that the logs from klog stay consistent with the log format set by the user.
Before:
Logs from client-go don't follow the right format
```
cbanavik@cbanavik-mac argo-rollouts % go run cmd/rollouts-controller/main.go --logformat="json"
{"level":"info","msg":"Argo Rollouts starting","time":"2024-04-02T13:16:31+05:30","version":
{"level":"info","msg":"Leaderelection get id cbanavik-mac_11377322-2859-434d-8f46-121b1438e6b2","time":"2024-04-02T13:16:31+05:30"}
{"level":"info","msg":"Starting Metric Server at 0.0.0.0:8090","time":"2024-04-02T13:16:31+05:30"}
INFO[0000] attempting to acquire leader lease argo-rollouts/argo-rollouts-controller-lock... 
{"level":"info","msg":"New leader …
```
=> fix: set formatter for klog logger

utils/plugin/downloader.go, utils/plugin/downloader_test.go
=> fix(controller): Corrects the logic of comparing sha256 has. Fixes #3519

USERS.md
=> docs: Add Amadeus to Users.md

docs/concepts.md
=> docs: provide recommendation for strategies

ui/src/app/components/rollout/rollout.scss
I feel that having the current (running) step in orange color is misleading, as orange
usually means warning.
This commit changes the color to the `$argo-running-color`.
After:
Checklist:
=> feat(dashboard): change the color of the current rollout step

ui/yarn.lock
First rollout PR here.  There is no rollouts issue opened for this.
Rollouts is pulling in both 2.0.0 (via resolve-url-loader) and 2.0.4.  This change makes it pull only 2.0.4.
2.0.0 has the vulnerability CVE-2022-37599, so we could simply avoid pulling 2.0.0 and use 2.0.4 since it is a z version update.
Checklist:
=> fix: Update loader-utils to 2.0.4

rollout/trafficrouting.go, rollout/trafficrouting/alb/alb.go, rollout/trafficrouting/alb/alb_test.go, rollout/trafficrouting_test.go, utils/rollout/rolloututil.go, utils/rollout/rolloututil_test.go
At the end of the rollout when we auto set the weight to the max (100%) etc. we should verify the weight. If we don't this can actually cause issues even with target group verification at the end of the rollout. The reason is the ALB controller can be slow to update for many reasons, which means we can actually verify target groups successfully and start tearing down old pods before we have shifted the weight over to the new service.
=> fix: verify the weight of the alb at the end of the rollout

rollout/canary.go, rollout/service.go, rollout/trafficrouting/alb/alb.go, rollout/trafficrouting/istio/istio.go, rollout/trafficrouting/service_helper.go, rollout/trafficrouting/service_helper_test.go, test/e2e/aws_test.go, test/e2e/functional/albmesh-pingpong-stablecanary-rollout.yaml
…StableAndCanaryServices returns based on isPingpongPreferred. Only when it is ALB controller, then isPringpongPreferred is true.
Checklist:
=> fix: when Rollout has pingpong and stable/canary service defined, only alb traffic management uses pingpong.

manifests/base/argo-rollouts-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml
The latest manifests (v1.7.0-rc1) throws the following error during plugin download. The reason probably is the stricter security context introduced in #3424. I added a new volume for downloaded plugin files.
```
time="2024-04-30T06:38:26Z" level=fatal msg="Failed to download plugins: failed to create plugin folder for plugin (argoproj-labs/gatewayAPI): (mkdir /home/argo-rollouts/plugin-bin: read-only file system)"
```
~It seems files in `emptyDir` is not executable even if `securityContext.fsGroup` is set. I'm still investigating.~ Fixed by adding `tmp` volume.
Checklist:
=> fix: Add volume for plugin and tmp folder

docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_dashboard.md, docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_get_rollout.md, docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_list_experiments.md, docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_list_rollouts.md, docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_set_image.md, docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_status.md, docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_terminate.md, docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_terminate_analysisrun.md, docs/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_undo.md, pkg/kubectl-argo-rollouts/cmd/dashboard/dashboard.go, pkg/kubectl-argo-rollouts/cmd/get/get_rollout.go, pkg/kubectl-argo-rollouts/cmd/lint/lint.go, pkg/kubectl-argo-rollouts/cmd/list/list_experiments.go, pkg/kubectl-argo-rollouts/cmd/list/list_rollouts.go, pkg/kubectl-argo-rollouts/cmd/set/set_image.go, pkg/kubectl-argo-rollouts/cmd/status/status.go, pkg/kubectl-argo-rollouts/cmd/terminate/terminate.go, pkg/kubectl-argo-rollouts/cmd/undo/undo.go
=> chore: fix and add more cli usage case

.github/workflows/go.yml
Codecov is going through a change requiring tokens, they are suppose to auto figure out if it's a PR and do a tokenless but they are having issue making it flaking this has been going on for a while now. Let's not fail pipeline on failures for the time being.
https://github.com/DSpace/DSpace/issues/9630
https://github.com/codecov/engineering-team/issues/1574#issuecomment-2059856841
=> chore: don't fail code-cov on failure

docs/assets/versions.js
Checklist:
the [docs site]( https://argoproj.github.io/argo-rollouts/ ) version selector dropdown is broken
Fixed the version selector.  Also added version information warning as with ArgoCD
=> fix: docs site version selector broken

manifests/install.yaml, manifests/namespace-install.yaml, manifests/role/argo-rollouts-clusterrole.yaml
Fixes: #3672 
Add the `update` verb in the ClusterRole permissions to allow argo-rollouts to update deployments. This fixes the issue with the scaleDown feature not working due to missing permissions. (#3672)
Checklist:
=> fix: add update verb to ClusterRole permissions for scaleDown feature. Fixes #3672

rollout/analysis.go, rollout/analysis_test.go
This PR should fix an issue with Background (and other) Analysis runs from running when rolling back to a revision within a Rollback Window. I'm not incredibly well versed with how testing is done within this project or golang in general, so any assistance in that area would be appreciated. That being said I did give it a best effort.
I originally discovered the issue described in #3669 in v1.6.6, where by rolling back an application within a rollback window unexpectedly ran a background analysis which could fail, causing a rapid scale up and down of the application's replicaset. To reconcile that issue the failed background analysis run needed to be deleted. I am unable to easily reproduce that issue, but considering that we didn't expect any background analysis to run when rolling back …
=> fix(analysis): Take RollbackWindow into account when Reconciling Analysis Runs. Fixes #3669

metricproviders/datadog/datadog.go, metricproviders/datadog/datadogV2_test.go
the field is required by the v2 API and we currently leave it empty string.
@zachaller you removed it in https://github.com/argoproj/argo-rollouts/pull/3643 and that is fine. this PR will not add it back to the schema and not break the v1 API. 
without this change and without aggregator set on a v2 metric, one gets:
```
received non 2xx response code: 400 {"errors":["Value of parameter
'aggregator' should be any of these [None, 'avg', 'min', 'max',
'sum', 'last', 'mean', 'area', 'l2norm', 'percentile', 'stddev']"]}
```
If we set it to None, according to datadog docs it will default to `avg`. According to rollouts docs, we should default to `last` (which makes sense for analysis)
https://docs.datadoghq.com/api/latest/metrics/#query-scalar-data-across-multiple-products
Checklist:
=> fix(analysis): explicitly set datadog aggregator to last only on v2

.github/workflows/testing-results.yml
example had a type of run_id, fix it to the proper run-id
=> fix: e2e test results processing change key name to run-id

.github/workflows/testing-results.yml
This used to be done like this: https://github.com/argoproj/argo-rollouts/blob/5dbd7a8efc6922d2f8875a457c791f01ddebcb46/.github/workflows/e2e-test-results.yml#L20-L33
Changed the code to use the action provided by github which is the suggested way. Docs on required permission: https://github.com/actions/download-artifact#download-artifacts-from-other-workflow-runs-or-repositories
=> fix: add secrets so we can download across workflows

.github/workflows/testing-results.yml, .github/workflows/testing.yaml
Report the status of E2E and unit tests seperatly to maintain the same behavior as before, a comment for each one on the PR.
=> fix: separate  e2e and unit test reporting uploads

docs/FAQ.md, docs/best-practices.md
Addresses some concerns about best practices as raised in https://github.com/argoproj/argo-rollouts/discussions/3752 and https://github.com/argoproj/argo-rollouts/discussions/3529
Checklist:
=> docs: added clarifications for short releases

rollout/trafficrouting/traefik/traefik.go
When the var(apiGroupToResource) is executed and we set the traefik api to traefik.io, using the cli flag, the value is not yet setted with SetTraefikAPIGroup(). So the value for traefik.io is not in the map. I changed to a function that is only executed when it is called.
This try to fix the #3615 issue.
Checklist:
=> fix(controller): Get the right resourceName for traefik.io.Fixes #3615

docs/features/ephemeral-metadata.md
A small grammatical fix.
Checklist:
=> docs: Update ephemeral-metadata.md with a small fix

metricproviders/prometheus/prometheus.go, metricproviders/webmetric/webmetric.go
The current code creates a new http.Transport for each http.Client that is created, which leads to a leak in TCP connections due to keep-alive.
Instead, reuse the same http.Transport between requests. According to the http.Transport docs, this is safe for concurrent use.
Checklist:
=> fix(metricprovider): reuse http.Transport for http.Client

cmd/rollouts-controller/main.go, controller/controller.go, controller/profiling.go
This PR enables pprof profiling on the Argo Rollouts controller via the `--enable-pprof` flag.  
Issue: [#3757](https://github.com/argoproj/argo-rollouts/issues/3757)
Checklist:
=> feat(controller): enable pprof profiling support

ui/src/app/components/analysis-modal/transforms.ts
Fixes #2758 using `json5` which is already a dependency here.
[Here's a Repl playground that demonstrates it's fixing the issue. ](https://replit.com/@AppliNH/CalmUnpleasantProcesses#index.ts)
Checklist:
=> fix(dashboard): parse analysis values with JSON5 to handle NaN. Fixes #2758

rollout/analysis_test.go, rollout/bluegreen.go, rollout/bluegreen_test.go, rollout/canary.go, rollout/canary_test.go, rollout/context.go, rollout/controller.go, rollout/controller_test.go, rollout/replicaset_test.go, rollout/service.go, rollout/service_test.go, rollout/sync.go, rollout/trafficrouting_test.go, test/e2e/canary_test.go, test/e2e/functional_test.go, test/e2e/istio_test.go, utils/replicaset/replicaset.go
There are 3 main changes in this PR:
1. Move Rollouts validation up earlier in the reconcile process into the rollout context creation function.
2. Move replica set creation code up earlier in the reconciliation process into the rollout context creation function.
3. Change replica set creation so that it dose not depend on the calling code to pass a bool into the function but instead automatically determines if replica sets need to be created.
=> chore: move ReplicaSet creation and Rollout validation earlier during the reconciliation process.

rollout/trafficrouting/nginx/nginx.go, rollout/trafficrouting/nginx/nginx_test.go
The current patch applied for nginx canaries does not play nicely with other controller that may be modifying Ingress annotations. In our case, the Rancher `field.cattle.io/publicEndpoints` is repeatedly added/removed, resulting in a significant amount of updates to Ingress resources in the cluster. 
With this fix, before building and applying the canary ingress patch, all annotations from the existing canary ingress will be copied over to the desired Ingress. 
fixes: https://github.com/argoproj/argo-rollouts/issues/1070
Checklist:
=> fix: retain non-nginx canary annotations. Fixes: #1070

docs/installation.md
=> docs: fix a link to e2e.yaml

docs/analysis/job.md
Was trying to run metric jobs in a different namespace. Wasn't documented how to do that. Now it is. 
Checklist:
=> docs: Update metric job docs with some of the available config options

rollout/sync.go
=> fix: stop rollout from entering degraded state during blueGreen pause. Fixes #3843

docs/features/specification.md
Checklist:
description:
The "Rollout Specification" document does not include an explanation of maxTrafficWeight in the section on setCanaryScale. Specifically, the description regarding setting the setCanaryScale weight mentions it as a "percentage of spec.replicas", but in reality, it functions as "spec.replicas * (setWeight / maxTrafficWeight)". Therefore, I would like to propose updating the documentation to reflect this behavior.
=> docs: Update specification document

metricproviders/datadog/datadog.go, metricproviders/datadog/datadogV2_test.go
Checklist:
When Datadog returns a values list with JSON `null` value, instead of an empty slice, it gets unmarshalled to a float64 value of 0, which is not what should happen (should be treated as if an empty slice). This is because `values` is a `[]float64`. Switching it to `[]*float64` fixes this issue. 
I've encountered this issue when doing zero/zero division. For example in `a/(a+b)`, where `a` and `b` are both zeros, the `a/(a+b)` formula returns `null`. I'm sure this could happen in other cases but I'm not aware of them.
For reference, this is what the datadog response would look like:
```json
{
"data": {
"attributes": {
"columns": [
{
"meta": {
"unit": null
},
"name": "a/(a+b)",
"type": "number",
"values": [
null
]
}
]
},
"type": "scalar_response"
}
}
```
For the numerator and …
=> fix(metricprovider): fix handling null values in datadog

rollout/sync.go, rollout/sync_test.go
This bug can cause rollouts to get stuck in a tight loop of thinking it's constantly in a scaling event. Argo rollouts does not ever update the `/desired-replicas` annotation on ReplicaSets that are not stable or desired (newRs) there can be races where a ReplicaSet will get marked as old with a value in `/desired-replicas` that dose not match `spec.replicas` on the rollout this could either be due to a scaling event right after that rs gets moved to old or a code path that does not update the rs before marking it as old.
This change makes this loop not possible because we will not check all replicasets but instead only check stable and newRs which are the only ones we scale on scaling events.
Example state of issue below: We have an old replicaset that does not match spec.replicas of the …
=> fix: check isScalingEvent only on stable and newRS

docs/features/traffic-management/plugins.md
=> docs: GTW API support changed to Gloo Gateway instead of GloodMesh

pkg/apis/rollouts/validation/validation.go, pkg/apis/rollouts/validation/validation_test.go, pkg/kubectl-argo-rollouts/cmd/lint/lint_test.go
Even though weighted experiment calls are correctly delegated to Traffic Router plugins, the validation is currently not allowing to register a TrafficRouting plugin when weighted experiments are present.
It seems that this validation was added before plugin architecture supported `additionalDestinations`, so it made sense then. Ideally a plugin would have a way to announce it's capabilities, but given right now API does not have anything suitable for that - this PR provides a simple way to unblock using plugins that support weighted experiments.
Checklist:
=> fix(controller): weighted experiment validation should allow delegating to trafficRouter plugins

rollout/trafficrouting.go, rollout/trafficrouting_test.go
Attempts to address some concerns with behavior in:
- https://github.com/argoproj/argo-rollouts/issues/3617
It seems like we are forgetting to remove the managed routes when the following occurs:
1. Rollout is stable on V1
2. Rollout is updated with V2, and begins to progress
3. Managed routes are defined (e.g. to send traffic with specific header values to the canary service)
4. Rollout is updated with V3, and must start back at the beginning again where V1 is still considered stable (ditching any ongoing progress with V2)
5. Canary service selector is swapped to V3 replicaset
6. Traffic weights are set back to 0 
It does not seem like any managed routes are considered between steps 4-6. I believe this code that I've made an addition to is where this would need to occur, but would love …
=> fix: remove condition where header routes can stay directed at empty service in preemption

.github/pull_request_template.md
Update the link in [PR template](https://github.com/argoproj/argo-rollouts/blob/master/.github/pull_request_template.md) to the [CONTRIBUTING.md](https://github.com/argoproj/argoproj/blob/43fae0ccbe93ca8ebc482198ecf07199d8bdd96c/community/CONTRIBUTING.md) which has a description of `DCO`.
Checklist:
=> chore: update the link of DCO in PR template

server/server.go
Fixes: #2095
Every time `GetRolloutInfo` route is called it creates a new `RolloutViewController`, but the context passed into the view controller was never cancelled. This resulted in the informers never being cleaned up which manifested as a memory leak. Cancelling the view controllers context after the request has processed eliminates the "memory leak".
The graph below shows our production instance (pod named `argo-rollouts-dashboard-8dfdc4bd6-vkhkp`) vs the test instance with the fix applied (pod named `argo-rollouts-dashtest`). Both instances were receiving API requests every 15seconds.
Checklist:
=> fix(dashboard): Cleanup viewcontroller after each request. Fixes #2095

controller/controller.go, controller/controller_test.go, docs/analysis/plugins.md, docs/features/traffic-management/plugins.md, utils/plugin/downloader.go, utils/plugin/downloader_test.go, utils/plugin/types/types.go
In our company, we have a use case where we need to create a new plugin as a metric provider. For security reasons the plugin needs to be private and cannot be uploaded to a public storage. 
Therefore, we have the need to use credentials for downloading the plugin securely. 
We have followed k8s secretRef pattern to specify how the credentials are passed. 
Additionally, we had an issue with 404 status code. The downloader says that the plugin is downloaded correctly but it’s not true. 
Fixes: #3708
Checklist:
=> feat(metricprovider): credentials to download plugin

.github/workflows/go.yml, .golangci.yml, Dockerfile, metricproviders/job/job_test.go, pkg/apis/rollouts/validation/validation_references.go, pkg/kubectl-argo-rollouts/cmd/list/list_experiments.go, pkg/kubectl-argo-rollouts/cmd/list/list_rollouts.go, pkg/kubectl-argo-rollouts/cmd/undo/undo.go, rollout/restart_test.go, rollout/trafficrouting/alb/alb_test.go, rollout/trafficrouting/ambassador/ambassador.go, utils/analysis/factory_test.go
=> chore: update golangci-lint to v1.61.0

.github/workflows/testing.yaml
=> ci: add testing for k8s 1.30 and 1.31

docs/features/analysis.md
=> docs(analysis): add docs for consecutiveSuccessLimit

rollout/controller.go
This change keeps the logic working the same way as it did in 1.7.x where we did not return any errors on validation issues because we re-queue at 20 seconds instead. There are some interesting logic issues here that have existed for ever that I commented some possible improvement's on but have not done.
=> fix: don't over reconcile on error

.readthedocs.yaml
Updating Read-the-docs conf. New syntax will be required in January 2025 
See  https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
=> docs: new syntax for docs conf

docs/features/ephemeral-metadata.md
=> docs:  mention the Kubernetes Downward API in the ephemeral metadata documentation page

USERS.md, controller/profiling.go
=> fix(controller): Fixed broken pprof links #4037

utils/replicaset/canary.go, utils/replicaset/canary_test.go
We're seeing issues with rollout sync failing due to errors like this:
```
roCtx.reconcile err Operation cannot be fulfilled on pods \"REDACTED\": the object has been modified; please apply your changes to the latest version and try again"
```
It seems that we're trying to delete the metadata on every pod every sync, even if the pod doesn't have the keys. This means that in environments with high pod churn, this loop can get stuck for a very long time. This simply adds a check to make sure the key is actually present in the metadata before we delete it and mark it as modified.
Before the fix with the new test:
```
go test ./utils/replicaset/...
--- FAIL: TestSyncEphemeralPodMetadata (0.00s)
canary_test.go:1353:
Error Trace:	/Users/jrodgers/argo-rollouts/utils/replicaset/canary_test.go:1353 …
```
=> fix: check ephemeral metadata is set before delete

docs/analysis/datadog.md
Checklist:
Currently in https://argoproj.github.io/argo-rollouts/analysis/datadog/ the following would occur
this PR addresses it by fixing the rendering of the YAML.
=> docs: fix markdown rendering

experiments/replicaset.go, experiments/replicaset_test.go, rollout/canary_test.go, rollout/experiment.go, rollout/experiment_test.go
Enhancement ticket: https://github.com/argoproj/argo-rollouts/issues/4113 
This can be useful for complying to Tagging Policy imposed at cluster level since there is no mechanism to add custom labels to Experiments and their associated ReplicaSets.
Indeed, this could enable automatic reporting but also give required information for investigation.
Checklist:
=> fix(experiments): propagate rolouts labels to experiments and replicasets

rollout/ephemeralmetadata.go
When we err rs can be nil, so lets not use it in the logging.
=> fix: nil pointer on logging

cmd/rollouts-controller/main.go, controller/controller.go, controller/controller_test.go, go.mod, rollout/controller.go, rollout/controller_test.go, rollout/ephemeralmetadata.go, rollout/ephemeralmetadata_test.go
Right now, every pod has it's ephemeral updated serially. When dealing with a large number of pods, this can get to be quite slow, especially when you have things like validating/mutating webhooks that have to run for every request.
This updates it to simply use an errgroup with a default concurrency of 10 to update the pods in parallel, which should greatly speed things up 🎉  
Checklist:
=> feat: reconcile pod ephemeral metadata in parallel

.gitignore, experiments/controller.go, experiments/experiment.go, utils/experiment/experiment.go, utils/experiment/experiment_test.go
This fix (feat?) resolves the issue raised in #4009. 
I think this meets what users would expect from the use of an Experiment as a Step in a Rollout. 
As a user, if I setup notifications on AnalysisRun events, I would expect an AnalysisRun that fails should generate a notification. To be clear, this is ONLY when the Analysis Run belongs to an Experiment, which itself belongs to the Rollout (As a Step in that Rollout).  https://argo-rollouts.readthedocs.io/en/stable/features/experiment/#integration-with-rollouts
Please let me know if you would like to discuss this further, but this feels like a 'safe' change. It should even be good to backport to 1.7x (which is what I developed it against).  
I could use some guidance around testing this - I didn't see any prior integration test for this …
=> fix(experiments): fire rollout event on experiment step

metricproviders/datadog/datadog.go, metricproviders/datadog/datadog_test.go
Fix https://github.com/argoproj/argo-rollouts/issues/4103
Checklist:
=> fix(metricprovider): not require address in kubernetes secret for Datadog. Fixes #4103

rollout/canary.go, rollout/service_test.go, rollout/trafficrouting_test.go
BREAKING CHANGE
We are changing rollouts `.status.selector` field to report only the stable replicaset for traffic routed canaries that do not use dynamicStableScale. This is needed in order to be able to use HPA's reliably. A little explanation on how HPA. calculate desired pods. There are two methods and formulas for calculating desired pods counts we will be focusing on `Value` type metrics.
The formula for `Value` type metrics is as follows `desiredReplicas = ceil[currentReplicas * ( currentMetricValue / desiredMetricValue )]` The `currentReplicas` count comes from the selector defined in `.status.selector` for Argo Rollouts. Before we merge this PR this would be all pods under the Rollout. This causes issues because as we shift traffic to the desired state we end up with a whole …
=> fix!: subresource scale selector changed for traffic routed canary

rollout/trafficrouting/istio/istio.go, rollout/trafficrouting/istio/istio_test.go
Fixes https://github.com/argoproj/argo-rollouts/issues/3884
Checklist:
=> fix(trafficrouting): patch VirtualService when there is only one named route

rollout/trafficrouting.go, rollout/trafficrouting_test.go
This PR introduces a guardrail in the rollouts controller to help prevent unexpected downtime during rollouts. The guardrail adds an additional check to ensure that the number of replicas in the stable ReplicaSet is sufficient before any traffic switch occurs.
For example, if the desired weight for canary replicas is set to 60%, and there are 10 replicas in total, the code will verify that, before diverting 60% of the traffic to the canary replicas, at least 40% of the replicas (i.e., 4 in this case) are available in the stable ReplicaSet.
This check is crucial to prevent potential downtime. A common scenario where downtime can occur is when a rollout is already in progress, and a new deployment is triggered. In such cases, if the stable replicas are insufficient, it could lead to service …
=> fix: guardrail to not overload stable replicaset

rollout/analysis.go, test/e2e/analysis_test.go, test/e2e/functional/analysistemplate-web-background-inconclusive.yaml, test/e2e/functional/rollout-background-analysis-inconclusive.yaml, test/fixtures/then.go, test/fixtures/when.go
The current patch is applied for background analysis runs. It fixes unexpected promotion of a Rollout on the canary pause step and background analysis run with `Inconclusive` results. Instead of promoting on `Inconclusive` result reconciler must keep `Pause` phase/status of the Rollout for manual intervention (promote/abort) similarly to step analysis runs.
In addition, the PR adds an end-to-end test for this specific edge case.
Fixes: #3850 
Current behavior:
```
Name:            rollout-background-analysis-inconclusive
Namespace:       user-ypopivniak
Status:          ✔ Healthy
Strategy:        Canary
Step:          2/2
SetWeight:     100
ActualWeight:  100
Images:          nginx:1.19-alpine (stable)
Replicas:
Desired:       2
Current:       2
Updated:       2
Ready:         2 …
```
=> fix(analysis): prevent promotion on inconclusive background run. Fixes: #3850

rollout/bluegreen_test.go, rollout/replicaset.go
Reverts argoproj/argo-rollouts#4072
This PR breaks normal bluegreen deployments, need to see why no e2e or unit tests caught this as well. Will need to implement the bug fix in a different manor.
The issue with this PR is we remove the annotation before scaling down the replicaset so we get in a loop of continuously adding the scale down annotation without actually scaling down the replicaset.
=> fix: Revert "fix(controller):  rollout stuck in `Progressing`. fixes #3988"

rollout/bluegreen.go, rollout/canary.go, rollout/restart.go, rollout/restart_test.go
A user had hit downtime when they were simultaneously restarting their rollout, while it was in the middle of an update. An unfortunate timing problem can result in the controller both:
1. restarting a pod that is older than restartedAt
2. scaling down the old ReplicSet as part of a normal canary update
The scaling down in step 2, had brought the total number of available pods below maxUnavailable.
Here is an example sequence of logs that happened in a single reconciliation. 
The rollout had:
* `replicas: 2`
* `maxUnavailable: 0`
* 3 available pods 
1. Reconciliation starts:
```
{"_time":"2025-02-24T20:51:19.551+0000","log":"level=info msg=\"Started syncing rollout\" generation=2504 namespace=my-namespace resourceVersion=7387666133 rollout=my-rollout"}
```
2. Restarter restarts …
=> fix: restarts during updates could cause downtime

.github/workflows/go.yml
to fix lint errors in recent PRs
Checklist:
=> chore(deps): bump golangci-lang from v1.61.0 to v1.64.8

docs/features/kustomize/rollout-transform.yaml
Reading the yaml of `rollout-transform.yaml` and found that the link is 404. 
Checklist:
=> fix: follow the kustomize directory structure changes for link

go.mod, go.sum
=> chore(deps): bump golang.org/x/oauth2 from 0.24.0 to 0.29.0 to fix CVE-2025-22868

go.mod, go.sum
Checklist:
Fixes https://github.com/argoproj/argo-rollouts/issues/4235 
Need to cherry pick this back for the 1.8.z and 1.7.z releases
See also the change already made in Argo CD to resolve a high-severity vulnerability: https://github.com/argoproj/argo-cd/pull/22466
=> chore(deps): bump github.com/golang-jwt/jwt to 4.5.2 (#4235)

docs/features/bluegreen.md
Blue green with ALB ingress can not guarantee 100% uptime during a rollout.
=> docs: blue green w/ ALB not supported without downtime

ui/src/app/components/rollout/containers.tsx
When rewriting containers from the UI dashboard, if port numbers are included, as in the image, they cannot be deployed properly. 
(e.g. `10.0.2.15:5000/my-app:v1` → image=`10.10.2.15`, tag=`5000/my-app`)
This is because the input is simply split with a colon.
In this PR, the image and tag are extracted by the colon at the end of the input string.
Checklist:
=> fix(dashboard): fix container image input

docs/concepts.md
docs(concepts): fix traffic manager wording
- Fixed a duplicated word in the traffic manager note in docs/concepts.md.
The sentence now reads: "Note that the traffic manager can be any compatible
Service Mesh or Ingress Controller or Gateway API implementation (via a plugin)."
=> docs: fix traffic manager note

cmd/rollouts-controller/main.go, manifests/install.yaml, manifests/namespace-install.yaml, manifests/role/argo-rollouts-clusterrole.yaml, rollout/trafficrouting/alb/alb.go, rollout/trafficrouting/alb/alb_test.go, utils/aws/aws.go, utils/aws/aws_test.go, utils/defaults/defaults.go, utils/defaults/defaults_test.go
The Argo Rollouts controller fails to perform target weight verification and, as a result, cannot scale down the old ReplicaSet during canary rollouts when the target group verification option `--aws-verify-target-group` is enabled on AWS EKS Auto Mode. This issue is caused by a [change in the AWS API version used by EKS Auto Mode](https://docs.aws.amazon.com/eks/latest/userguide/auto-configure-alb.html#_considerations) — from `elbv2.k8s.aws/v1beta1` to `eks.amazonaws.com/v1` — which prevents the controller from retrieving the target group resources.
This PR exposes the following CLI flags to allow users to dynamically configure the AWS API versions, similar to other flags that expose provider-specific API versions (e.g., for Ambassador, Istio, Traefik):
* …
=> fix(cli): expose AWS API versions in controller CLI. Fixes #4334

Makefile
This is a missing change from #4212
=> chore: make api-proto to support go module style

.github/workflows/testing.yaml
=> build: tmate.io is no longer active

.github/ISSUE_TEMPLATE/enhancement_proposal.md
Change the issue template wording to match with the enhancement proposal issue type, as the current wording is intended for a bug report.
- From: **Impacted by this bug?** Give it a 👍. We prioritize the issues with the most 👍.
- To:  **Need this enhancement?** Give it a 👍. We prioritize the issues with the most 👍.
Checklist:
=> chore: Change enhancement proposal issue wording
